<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

/**
 * Builds a {@see Address1}.
 */
final class Address1Builder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>           $city
     * @param Option<string>           $stateOrProvinceCode
     * @param Option<string>           $postalCode
     * @param Option<string>           $countryCode
     * @param Option<bool>             $residential
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private Option $city,
        private Option $stateOrProvinceCode,
        private Option $postalCode,
        private Option $countryCode,
        private Option $residential,
        private array $additionalProperties,
    ) {
    }

    /**
     * Specify name of city, town, etc.
     *
     * Example: Beverly Hills
     */
    public function setCity(string $city): self
    {
        $this->city = Some::create($city);

        return $this;
    }

    /**
     * Specify State or province code. Maximum length is 2.State code is required for US, CA, PR and
     * not required for other countries. Conditional. Max length is 2.
     *
     * Example: CA
     *
     * <a onclick='loadDocReference("canadaprovincecodes")'>Click here to see State Or Province
     * Codes</a>
     */
    public function setStateOrProvinceCode(string $stateOrProvinceCode): self
    {
        $this->stateOrProvinceCode = Some::create($stateOrProvinceCode);

        return $this;
    }

    /**
     * Specify the postal code. This is optional for non postal- aware countries. Maximum length is
     * 10.
     *
     * Example: 65247
     *
     * <a onclick='loadDocReference("postalawarecountries")'>Click here to see Postal aware
     * countries</a>
     */
    public function setPostalCode(string $postalCode): self
    {
        $this->postalCode = Some::create($postalCode);

        return $this;
    }

    /**
     * The two-letter country code. Maximum length is 2.
     *
     * Example: US
     *
     * <a onclick='loadDocReference("countrycodes")'>Click here to see Country Codes</a>
     */
    public function setCountryCode(string $countryCode): self
    {
        $this->countryCode = Some::create($countryCode);

        return $this;
    }

    /**
     * Indicate whether this address is residential (as opposed to commercial).
     */
    public function setResidential(bool $residential): self
    {
        $this->residential = Some::create($residential);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): Address1
    {
        return new Address1(
            $this->city,
            $this->stateOrProvinceCode,
            $this->postalCode,
            $this->countryCode,
            $this->residential,
            $this->additionalProperties,
        );
    }
}
