<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Override;
use Prefabcortex\FedexRatesAndTransitTimesApi\Exception\MalformedDataException;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\None;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_string;
use function sprintf;

final readonly class AlcoholDetail implements SelfNormalizingModel
{
    /**
     * @param AlcoholDetailAlcoholRecipientType|UnknownEnumValue<string> $alcoholRecipientType
     * @param Option<string>                                             $shipperAgreementType
     * @param array<int|string, mixed>                                   $additionalProperties
     */
    public function __construct(
        private AlcoholDetailAlcoholRecipientType|UnknownEnumValue $alcoholRecipientType,
        private Option $shipperAgreementType,
        private array $additionalProperties,
    ) {
    }

    public static function builder(AlcoholDetailAlcoholRecipientType $alcoholRecipientType): AlcoholDetailBuilder
    {
        return new AlcoholDetailBuilder($alcoholRecipientType, None::create(), []);
    }

    /**
     * Specify the recipient type for the alcohol shipment.
     *
     * @return AlcoholDetailAlcoholRecipientType|UnknownEnumValue<string>
     */
    public function getAlcoholRecipientType(): AlcoholDetailAlcoholRecipientType|UnknownEnumValue
    {
        return $this->alcoholRecipientType;
    }

    /**
     * Specify the shipper entity type.
     *
     * Example: Fulfillment house, Retailer or a Winery.
     *
     * @return Option<string>
     */
    public function getShipperAgreementType(): Option
    {
        return $this->shipperAgreementType;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $alcoholRecipientType = null;
        $shipperAgreementType = None::create();
        if (array_key_exists('alcoholRecipientType', $data)) {
            $alcoholRecipientTypeRaw = $data['alcoholRecipientType'];
            if (!is_string($alcoholRecipientTypeRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "alcoholRecipientType" must be string, got %s.',
                        get_debug_type($alcoholRecipientTypeRaw),
                    ),
                );
            }
            $alcoholRecipientType = AlcoholDetailAlcoholRecipientType::tryFrom($alcoholRecipientTypeRaw)
                ?? UnknownEnumValue::of($alcoholRecipientTypeRaw);
        }
        if (array_key_exists('shipperAgreementType', $data) && $data['shipperAgreementType'] !== null) {
            $shipperAgreementTypeRaw = $data['shipperAgreementType'];
            if (!is_string($shipperAgreementTypeRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "shipperAgreementType" must be string, got %s.',
                        get_debug_type($shipperAgreementTypeRaw),
                    ),
                );
            }
            $shipperAgreementType = Some::create($shipperAgreementTypeRaw);
        }
        $additionalProperties = array_diff_key($data, ['alcoholRecipientType' => true, 'shipperAgreementType' => true]);
        if ($alcoholRecipientType === null) {
            throw new MalformedDataException('Required property "alcoholRecipientType" is missing from the document.');
        }

        return new self($alcoholRecipientType, $shipperAgreementType, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $dataArray['alcoholRecipientType'] = $this->alcoholRecipientType->value;
        $shipperAgreementTypeOption = $this->shipperAgreementType;
        if ($shipperAgreementTypeOption->isDefined()) {
            $shipperAgreementType = $shipperAgreementTypeOption->get();
            $dataArray['shipperAgreementType'] = $shipperAgreementType;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): AlcoholDetailBuilder
    {
        return new AlcoholDetailBuilder(
            $this->alcoholRecipientType,
            $this->shipperAgreementType,
            $this->additionalProperties,
        );
    }
}
