<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

/**
 * Builds a {@see Alert}.
 */
final class AlertBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>                                  $code
     * @param Option<AlertAlertType|UnknownEnumValue<string>> $alertType
     * @param Option<string>                                  $message
     * @param array<int|string, mixed>                        $additionalProperties
     */
    public function __construct(
        private Option $code,
        private Option $alertType,
        private Option $message,
        private array $additionalProperties,
    ) {
    }

    /**
     * Specifies the alert code.
     */
    public function setCode(string $code): self
    {
        $this->code = Some::create($code);

        return $this;
    }

    /**
     * Specifies the alert type.
     */
    public function setAlertType(AlertAlertType $alertType): self
    {
        $this->alertType = Some::create($alertType);

        return $this;
    }

    /**
     * Specifies the alert message.
     */
    public function setMessage(string $message): self
    {
        $this->message = Some::create($message);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): Alert
    {
        return new Alert($this->code, $this->alertType, $this->message, $this->additionalProperties);
    }
}
