<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

/**
 * Builds a {@see BatteryClassificationDetail}.
 */
final class BatteryClassificationDetailBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<BatteryClassificationDetailMaterial|UnknownEnumValue<string>>          $material
     * @param Option<BatteryClassificationDetailRegulatorySubType|UnknownEnumValue<string>> $regulatorySubType
     * @param Option<BatteryClassificationDetailPacking|UnknownEnumValue<string>>           $packing
     * @param array<int|string, mixed>                                                      $additionalProperties
     */
    public function __construct(
        private Option $material,
        private Option $regulatorySubType,
        private Option $packing,
        private array $additionalProperties,
    ) {
    }

    /**
     * Describes the material composition of the battery or cell. Example: LITHIUM_METAL.
     */
    public function setMaterial(BatteryClassificationDetailMaterial $material): self
    {
        $this->material = Some::create($material);

        return $this;
    }

    /**
     * Specify the regulation specific classification for the battery or cell.
     */
    public function setRegulatorySubType(BatteryClassificationDetailRegulatorySubType $regulatorySubType): self
    {
        $this->regulatorySubType = Some::create($regulatorySubType);

        return $this;
    }

    /**
     * Indicate the packing arrangement of the battery or cell with respect to other items within
     * the same package. Example: CONTAINED_IN_EQUIPMENT.
     */
    public function setPacking(BatteryClassificationDetailPacking $packing): self
    {
        $this->packing = Some::create($packing);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): BatteryClassificationDetail
    {
        return new BatteryClassificationDetail(
            $this->material,
            $this->regulatorySubType,
            $this->packing,
            $this->additionalProperties,
        );
    }
}
