<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

/**
 * Builds a {@see BrokerDetailRateReply}.
 */
final class BrokerDetailRateReplyBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param BrokerDetailRateReplyType|UnknownEnumValue<string> $type
     * @param Option<Brokeraddress>                              $brokerAddress
     * @param array<int|string, mixed>                           $additionalProperties
     */
    public function __construct(
        private BrokerDetailBrokerRateReply $broker,
        private BrokerDetailRateReplyType|UnknownEnumValue $type,
        private Option $brokerAddress,
        private array $additionalProperties,
    ) {
    }

    public function setBroker(BrokerDetailBrokerRateReply $broker): self
    {
        $this->broker = $broker;

        return $this;
    }

    /**
     * This is Broker Type.
     */
    public function setType(BrokerDetailRateReplyType $type): self
    {
        $this->type = $type;

        return $this;
    }

    /**
     * This is the broker address used for this shipment.
     */
    public function setBrokerAddress(Brokeraddress $brokerAddress): self
    {
        $this->brokerAddress = Some::create($brokerAddress);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): BrokerDetailRateReply
    {
        return new BrokerDetailRateReply($this->broker, $this->type, $this->brokerAddress, $this->additionalProperties);
    }
}
