<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

/**
 * Builds a {@see Brokeraddress}.
 */
final class BrokeraddressBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<list<string>>     $streetLines
     * @param Option<string>           $city
     * @param Option<string>           $stateOrProvinceCode
     * @param Option<string>           $postalCode
     * @param Option<string>           $countryCode
     * @param Option<bool>             $residential
     * @param Option<string>           $classification
     * @param Option<string>           $geographicCoordinates
     * @param Option<string>           $urbanizationCode
     * @param Option<string>           $countryName
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private Option $streetLines,
        private Option $city,
        private Option $stateOrProvinceCode,
        private Option $postalCode,
        private Option $countryCode,
        private Option $residential,
        private Option $classification,
        private Option $geographicCoordinates,
        private Option $urbanizationCode,
        private Option $countryName,
        private array $additionalProperties,
    ) {
    }

    /**
     * This is the combination of number, street name, etc.
     *
     * Note: At least one line is required and streetlines more than 3 will be ignored. Empty lines
     * should not be included. Maximum Length per line is 35.
     *
     * Example: [10 FedEx Parkway, Suite 302, .etc.]
     *
     * @param list<string> $streetLines
     */
    public function setStreetLines(array $streetLines): self
    {
        $this->streetLines = Some::create($streetLines);

        return $this;
    }

    /**
     * This is city name.
     *
     * Example: Beverly Hills
     */
    public function setCity(string $city): self
    {
        $this->city = Some::create($city);

        return $this;
    }

    /**
     * This is the state Or Province Code. State code is required for US, CA, PR and not required
     * for other countries. Conditional. Max length is 2.
     *
     * Example: CA
     *
     * <a onclick='loadDocReference("canadaprovincecodes")'>Click here to see State Or Province
     * Code</a>
     */
    public function setStateOrProvinceCode(string $stateOrProvinceCode): self
    {
        $this->stateOrProvinceCode = Some::create($stateOrProvinceCode);

        return $this;
    }

    /**
     * This is the postal code.
     *
     * Example: 90210
     *
     * <a onclick='loadDocReference("postalawarecountries")'>Click here to see Postal aware
     * countries</a>
     */
    public function setPostalCode(string $postalCode): self
    {
        $this->postalCode = Some::create($postalCode);

        return $this;
    }

    /**
     * This is the country code.
     *
     * US
     *
     * <a onclick='loadDocReference("countrycodes")'>Click here to see Country Codes</a>
     */
    public function setCountryCode(string $countryCode): self
    {
        $this->countryCode = Some::create($countryCode);

        return $this;
    }

    /**
     * Indicate whether this address is residential (as opposed to commercial).
     *
     * Valid values are TRUE and FALSE.
     */
    public function setResidential(bool $residential): self
    {
        $this->residential = Some::create($residential);

        return $this;
    }

    /**
     * Specify the classification of the address.
     *
     * Example: residential
     */
    public function setClassification(string $classification): self
    {
        $this->classification = Some::create($classification);

        return $this;
    }

    /**
     * Specify the geographic coordinates.
     *
     * Example: geographicCoordinates
     */
    public function setGeographicCoordinates(string $geographicCoordinates): self
    {
        $this->geographicCoordinates = Some::create($geographicCoordinates);

        return $this;
    }

    /**
     * Specify the urbanization code.
     */
    public function setUrbanizationCode(string $urbanizationCode): self
    {
        $this->urbanizationCode = Some::create($urbanizationCode);

        return $this;
    }

    /**
     * Specify the country name.
     *
     * Example: India
     */
    public function setCountryName(string $countryName): self
    {
        $this->countryName = Some::create($countryName);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): Brokeraddress
    {
        return new Brokeraddress(
            $this->streetLines,
            $this->city,
            $this->stateOrProvinceCode,
            $this->postalCode,
            $this->countryCode,
            $this->residential,
            $this->classification,
            $this->geographicCoordinates,
            $this->urbanizationCode,
            $this->countryName,
            $this->additionalProperties,
        );
    }
}
