<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Override;
use Prefabcortex\FedexRatesAndTransitTimesApi\Exception\MalformedDataException;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\None;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_string;
use function sprintf;

final readonly class CODTransportationChargesDetail implements SelfNormalizingModel
{
    /**
     * @param Option<CODTransportationChargesDetailRateType|UnknownEnumValue<string>>        $rateType
     * @param Option<CODTransportationChargesDetailRateLevelType|UnknownEnumValue<string>>   $rateLevelType
     * @param Option<CODTransportationChargesDetailChargeLevelType|UnknownEnumValue<string>> $chargeLevelType
     * @param Option<CODTransportationChargesDetailChargeType|UnknownEnumValue<string>>      $chargeType
     * @param array<int|string, mixed>                                                       $additionalProperties
     */
    public function __construct(
        private Option $rateType,
        private Option $rateLevelType,
        private Option $chargeLevelType,
        private Option $chargeType,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): CODTransportationChargesDetailBuilder
    {
        return new CODTransportationChargesDetailBuilder(
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            [],
        );
    }

    /**
     * Specify COD Rate Type.
     *
     * @return Option<CODTransportationChargesDetailRateType|UnknownEnumValue<string>>
     */
    public function getRateType(): Option
    {
        return $this->rateType;
    }

    /**
     * Specify whether the rate applied on bundle or indiividual package.
     *
     * @return Option<CODTransportationChargesDetailRateLevelType|UnknownEnumValue<string>>
     */
    public function getRateLevelType(): Option
    {
        return $this->rateLevelType;
    }

    /**
     * Specify whether the charges applied on current or all packages.
     *
     * @return Option<CODTransportationChargesDetailChargeLevelType|UnknownEnumValue<string>>
     */
    public function getChargeLevelType(): Option
    {
        return $this->chargeLevelType;
    }

    /**
     * Specify the Charges Type.
     *
     * @return Option<CODTransportationChargesDetailChargeType|UnknownEnumValue<string>>
     */
    public function getChargeType(): Option
    {
        return $this->chargeType;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $rateType = None::create();
        $rateLevelType = None::create();
        $chargeLevelType = None::create();
        $chargeType = None::create();
        if (array_key_exists('rateType', $data) && $data['rateType'] !== null) {
            $rateTypeRaw = $data['rateType'];
            if (!is_string($rateTypeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "rateType" must be string, got %s.', get_debug_type($rateTypeRaw)),
                );
            }
            $rateType = Some::create(
                CODTransportationChargesDetailRateType::tryFrom($rateTypeRaw) ?? UnknownEnumValue::of($rateTypeRaw),
            );
        }
        if (array_key_exists('rateLevelType', $data) && $data['rateLevelType'] !== null) {
            $rateLevelTypeRaw = $data['rateLevelType'];
            if (!is_string($rateLevelTypeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "rateLevelType" must be string, got %s.', get_debug_type($rateLevelTypeRaw)),
                );
            }
            $rateLevelType = Some::create(
                CODTransportationChargesDetailRateLevelType::tryFrom($rateLevelTypeRaw)
                    ?? UnknownEnumValue::of($rateLevelTypeRaw),
            );
        }
        if (array_key_exists('chargeLevelType', $data) && $data['chargeLevelType'] !== null) {
            $chargeLevelTypeRaw = $data['chargeLevelType'];
            if (!is_string($chargeLevelTypeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "chargeLevelType" must be string, got %s.', get_debug_type($chargeLevelTypeRaw)),
                );
            }
            $chargeLevelType = Some::create(
                CODTransportationChargesDetailChargeLevelType::tryFrom($chargeLevelTypeRaw)
                    ?? UnknownEnumValue::of($chargeLevelTypeRaw),
            );
        }
        if (array_key_exists('chargeType', $data) && $data['chargeType'] !== null) {
            $chargeTypeRaw = $data['chargeType'];
            if (!is_string($chargeTypeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "chargeType" must be string, got %s.', get_debug_type($chargeTypeRaw)),
                );
            }
            $chargeType = Some::create(
                CODTransportationChargesDetailChargeType::tryFrom($chargeTypeRaw)
                    ?? UnknownEnumValue::of($chargeTypeRaw),
            );
        }
        $additionalProperties = array_diff_key(
            $data,
            ['rateType' => true, 'rateLevelType' => true, 'chargeLevelType' => true, 'chargeType' => true],
        );

        return new self($rateType, $rateLevelType, $chargeLevelType, $chargeType, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $rateTypeOption = $this->rateType;
        if ($rateTypeOption->isDefined()) {
            $rateType = $rateTypeOption->get();
            $dataArray['rateType'] = $rateType->value;
        }
        $rateLevelTypeOption = $this->rateLevelType;
        if ($rateLevelTypeOption->isDefined()) {
            $rateLevelType = $rateLevelTypeOption->get();
            $dataArray['rateLevelType'] = $rateLevelType->value;
        }
        $chargeLevelTypeOption = $this->chargeLevelType;
        if ($chargeLevelTypeOption->isDefined()) {
            $chargeLevelType = $chargeLevelTypeOption->get();
            $dataArray['chargeLevelType'] = $chargeLevelType->value;
        }
        $chargeTypeOption = $this->chargeType;
        if ($chargeTypeOption->isDefined()) {
            $chargeType = $chargeTypeOption->get();
            $dataArray['chargeType'] = $chargeType->value;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): CODTransportationChargesDetailBuilder
    {
        return new CODTransportationChargesDetailBuilder(
            $this->rateType,
            $this->rateLevelType,
            $this->chargeLevelType,
            $this->chargeType,
            $this->additionalProperties,
        );
    }
}
