<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

/**
 * Builds a {@see Commodity}.
 */
final class CommodityBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>           $description
     * @param Option<Weight2>          $weight
     * @param Option<int>              $quantity
     * @param Option<Money>            $customsValue
     * @param Option<Money>            $unitPrice
     * @param Option<int>              $numberOfPieces
     * @param Option<string>           $countryOfManufacture
     * @param Option<string>           $quantityUnits
     * @param Option<string>           $name
     * @param Option<string>           $harmonizedCode
     * @param Option<string>           $partNumber
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private Option $description,
        private Option $weight,
        private Option $quantity,
        private Option $customsValue,
        private Option $unitPrice,
        private Option $numberOfPieces,
        private Option $countryOfManufacture,
        private Option $quantityUnits,
        private Option $name,
        private Option $harmonizedCode,
        private Option $partNumber,
        private array $additionalProperties,
    ) {
    }

    /**
     * Indicate the description of the dutiable packages.
     *
     * Maximum Length is 450.
     *
     * Example: DOCUMENTS
     *
     * <a onclick='loadDocReference("vaguecommoditydescriptions")'>Click here to see Vague commodity
     * descriptions</a>
     */
    public function setDescription(string $description): self
    {
        $this->description = Some::create($description);

        return $this;
    }

    /**
     * Specify the Total weight of this commodity. This element is used to estimate duties and
     * taxes.
     */
    public function setWeight(Weight2 $weight): self
    {
        $this->weight = Some::create($weight);

        return $this;
    }

    /**
     * Specify the total number of units (using quantityUnits as the unit of measure) of this
     * commodity present in the shipment. This element is used to estimate duties and taxes.
     *
     * Example: 1
     */
    public function setQuantity(int $quantity): self
    {
        $this->quantity = Some::create($quantity);

        return $this;
    }

    /**
     * Specify the required Customs value for this commodity.
     */
    public function setCustomsValue(Money $customsValue): self
    {
        $this->customsValue = Some::create($customsValue);

        return $this;
    }

    public function setUnitPrice(Money $unitPrice): self
    {
        $this->unitPrice = Some::create($unitPrice);

        return $this;
    }

    /**
     * Specifies the number of pieces for this commodity.
     *
     * Example: 10
     */
    public function setNumberOfPieces(int $numberOfPieces): self
    {
        $this->numberOfPieces = Some::create($numberOfPieces);

        return $this;
    }

    /**
     * This is commodity country of manufacture. This is required. Maximum allowed length is 4.
     *
     * Example: US
     *
     * <a onclick='loadDocReference("countrycodes")'>Click here to see Country Codes</a>
     */
    public function setCountryOfManufacture(string $countryOfManufacture): self
    {
        $this->countryOfManufacture = Some::create($countryOfManufacture);

        return $this;
    }

    /**
     * Indicate quantiy unit used. Used to estimate duties and taxes.
     *
     * Example: PCS
     *
     * <a onclick='loadDocReference("harmonizedsystemcodeunitofmeasure-table1")'>click here to see
     * Commodity Unit Measures</a>
     */
    public function setQuantityUnits(string $quantityUnits): self
    {
        $this->quantityUnits = Some::create($quantityUnits);

        return $this;
    }

    /**
     * Indicate the Commodity name.
     *
     * Example: DOCUMENTS
     */
    public function setName(string $name): self
    {
        $this->name = Some::create($name);

        return $this;
    }

    /**
     * This is to specify the Harmonized Tariff System (HTS) code to meet U.S. and foreign
     * governments' customs requirements. These are mainly used to estimate the duties and taxes.
     *
     * Example: A six digit code for Almonds fresh or dried is 080211. The HTS code for pistachios
     * in shell is 080251. The HTS code for fish is HS203.
     *
     * To research the classification for your commodity, use the FedEx Global Trade Manager online
     * at <a href='http://www.fedex.com/gtm' target='_blank'>fedex.com/gtm</a>. You can find the
     * commodities and its respective codes by logging into FedEx and selecting harmonized code
     * option. You will find country-specific information to determine whether your commodity is
     * considered to be a document or non-document for your destination.
     *
     * For additional information about harmonized code, refer to <a
     * href='https://www.usitc.gov/documents/hts_external_guide.pdf' target='_blank'>harmonized
     * code</a>.
     */
    public function setHarmonizedCode(string $harmonizedCode): self
    {
        $this->harmonizedCode = Some::create($harmonizedCode);

        return $this;
    }

    /**
     * Specify the part number if any. Example: P1.
     */
    public function setPartNumber(string $partNumber): self
    {
        $this->partNumber = Some::create($partNumber);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): Commodity
    {
        return new Commodity(
            $this->description,
            $this->weight,
            $this->quantity,
            $this->customsValue,
            $this->unitPrice,
            $this->numberOfPieces,
            $this->countryOfManufacture,
            $this->quantityUnits,
            $this->name,
            $this->harmonizedCode,
            $this->partNumber,
            $this->additionalProperties,
        );
    }
}
