<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

enum CommitDetail1DaysInTransit: string
{
    case EIGHT_DAYS = 'EIGHT_DAYS';
    case EIGHTEEN_DAYS = 'EIGHTEEN_DAYS';
    case ELEVEN_DAYS = 'ELEVEN_DAYS';
    case FIFTEEN_DAYS = 'FIFTEEN_DAYS';
    case FIVE_DAYS = 'FIVE_DAYS';
    case FOUR_DAYS = 'FOUR_DAYS';
    case FOURTEEN_DAYS = 'FOURTEEN_DAYS';
    case NINE_DAYS = 'NINE_DAYS';
    case NINETEEN_DAYS = 'NINETEEN_DAYS';
    case ONE_DAY = 'ONE_DAY';
    case SEVEN_DAYS = 'SEVEN_DAYS';
    case SEVENTEEN_DAYS = 'SEVENTEEN_DAYS';
    case SIX_DAYS = 'SIX_DAYS';
    case SIXTEEN_DAYS = 'SIXTEEN_DAYS';
    case TEN_DAYS = 'TEN_DAYS';
    case THIRTEEN_DAYS = 'THIRTEEN_DAYS';
    case THREE_DAYS = 'THREE_DAYS';
    case TWELVE_DAYS = 'TWELVE_DAYS';
    case TWENTY_DAYS = 'TWENTY_DAYS';
    case TWO_DAYS = 'TWO_DAYS';
    case SMARTPOST_TRANSIT_DAYS = 'SMARTPOST_TRANSIT_DAYS';
    case UNKNOWN = 'UNKNOWN';
}
