<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Override;
use Prefabcortex\FedexRatesAndTransitTimesApi\Exception\MalformedDataException;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\None;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

use function array_diff_key;
use function array_is_list;
use function array_key_exists;
use function array_map;
use function get_debug_type;
use function is_array;
use function is_bool;
use function is_string;
use function sprintf;

final readonly class CommitDetail1 implements SelfNormalizingModel
{
    /**
     * @param Option<CommitDetail1DaysInTransit|UnknownEnumValue<string>>  $daysInTransit
     * @param Option<CommitDetail1GuaranteedType|UnknownEnumValue<string>> $guaranteedType
     * @param Option<string>                                               $smartPostCommitTime
     * @param Option<DateDetail>                                           $dateDetail
     * @param Option<DelayDetail>                                          $delayDetails
     * @param Option<bool>                                                 $saturdayDelivery
     * @param Option<list<string>>                                         $alternativeCommodityNames
     * @param Option<TransitDays>                                          $transitDays
     * @param Option<string>                                               $label
     * @param Option<string>                                               $commitMessageDetails
     * @param Option<string>                                               $commodityName
     * @param array<int|string, mixed>                                     $additionalProperties
     */
    public function __construct(
        private Option $daysInTransit,
        private Option $guaranteedType,
        private Option $smartPostCommitTime,
        private Option $dateDetail,
        private Option $delayDetails,
        private Option $saturdayDelivery,
        private Option $alternativeCommodityNames,
        private Option $transitDays,
        private Option $label,
        private Option $commitMessageDetails,
        private Option $commodityName,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): CommitDetail1Builder
    {
        return new CommitDetail1Builder(
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            [],
        );
    }

    /**
     * Code indicating the number of transit days.
     *
     * Example: EIGHTEEN_DAYS
     *
     * @return Option<CommitDetail1DaysInTransit|UnknownEnumValue<string>>
     */
    public function getDaysInTransit(): Option
    {
        return $this->daysInTransit;
    }

    /**
     * Indicates if there is a guaranteed delivery option applied to the rate. This is for freight
     * rates only.
     *
     * Valid values
     *
     * GUARANTEED_MORNING - guaranteed delivery on morning of date specified.
     *
     * GUARANTEED_CLOSE_OF_BUSINESS - guaranteed delivery on date specified by close of day
     *
     * Example: GUARANTEED_MORNING
     *
     * @return Option<CommitDetail1GuaranteedType|UnknownEnumValue<string>>
     */
    public function getGuaranteedType(): Option
    {
        return $this->guaranteedType;
    }

    /**
     * CommitTime for SmartPost shipments.
     *
     * @return Option<string>
     */
    public function getSmartPostCommitTime(): Option
    {
        return $this->smartPostCommitTime;
    }

    /**
     * These are date and time details.
     *
     * @return Option<DateDetail>
     */
    public function getDateDetail(): Option
    {
        return $this->dateDetail;
    }

    /**
     * Information about why a shipment delivery is delayed and at what level.
     *
     * @return Option<DelayDetail>
     */
    public function getDelayDetails(): Option
    {
        return $this->delayDetails;
    }

    /**
     * Specifies the saturdayDelivery.
     *
     * @return Option<bool>
     */
    public function getSaturdayDelivery(): Option
    {
        return $this->saturdayDelivery;
    }

    /**
     * Specifies the alternate names of commodities.
     *
     * @return Option<list<string>>
     */
    public function getAlternativeCommodityNames(): Option
    {
        return $this->alternativeCommodityNames;
    }

    /**
     * These are number of days the package/shipment is to be in transit. Applies to Ground and LTL
     * Freight; indicates minimum transit time for SmartPost.
     *
     * @return Option<TransitDays>
     */
    public function getTransitDays(): Option
    {
        return $this->transitDays;
    }

    /**
     * This is an informational message to inform client Deliverydate is unavailable. If
     * commitTimestamp and transitTime are unavailable, then this is populated in the response in
     * the client language.
     *
     * Example: Deliverydate unavailable
     *
     * @return Option<string>
     */
    public function getLabel(): Option
    {
        return $this->label;
    }

    /**
     * Messages concerning the ability to provide an accurate delivery commitment on an
     * International commit quote. These could be messages providing information about why a
     * commitment could not be returned or a successful message.
     *
     * Example: Message
     *
     * @return Option<string>
     */
    public function getCommitMessageDetails(): Option
    {
        return $this->commitMessageDetails;
    }

    /**
     * The Commodity applicable to this commitment.
     *
     * Example: DOCUMENTS
     *
     * @return Option<string>
     */
    public function getCommodityName(): Option
    {
        return $this->commodityName;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $daysInTransit = None::create();
        $guaranteedType = None::create();
        $smartPostCommitTime = None::create();
        $dateDetail = None::create();
        $delayDetails = None::create();
        $saturdayDelivery = None::create();
        $alternativeCommodityNames = None::create();
        $transitDays = None::create();
        $label = None::create();
        $commitMessageDetails = None::create();
        $commodityName = None::create();
        if (array_key_exists('daysInTransit', $data) && $data['daysInTransit'] !== null) {
            $daysInTransitRaw = $data['daysInTransit'];
            if (!is_string($daysInTransitRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "daysInTransit" must be string, got %s.', get_debug_type($daysInTransitRaw)),
                );
            }
            $daysInTransit = Some::create(
                CommitDetail1DaysInTransit::tryFrom($daysInTransitRaw) ?? UnknownEnumValue::of($daysInTransitRaw),
            );
        }
        if (array_key_exists('guaranteedType', $data) && $data['guaranteedType'] !== null) {
            $guaranteedTypeRaw = $data['guaranteedType'];
            if (!is_string($guaranteedTypeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "guaranteedType" must be string, got %s.', get_debug_type($guaranteedTypeRaw)),
                );
            }
            $guaranteedType = Some::create(
                CommitDetail1GuaranteedType::tryFrom($guaranteedTypeRaw) ?? UnknownEnumValue::of($guaranteedTypeRaw),
            );
        }
        if (array_key_exists('smartPostCommitTime', $data) && $data['smartPostCommitTime'] !== null) {
            $smartPostCommitTimeRaw = $data['smartPostCommitTime'];
            if (!is_string($smartPostCommitTimeRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "smartPostCommitTime" must be string, got %s.',
                        get_debug_type($smartPostCommitTimeRaw),
                    ),
                );
            }
            $smartPostCommitTime = Some::create($smartPostCommitTimeRaw);
        }
        if (array_key_exists('dateDetail', $data) && $data['dateDetail'] !== null) {
            $dateDetailRaw = $data['dateDetail'];
            if (!is_array($dateDetailRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "dateDetail" must be object, got %s.', get_debug_type($dateDetailRaw)),
                );
            }
            /** @var array<string, mixed> $dateDetailRawTyped */
            $dateDetailRawTyped = $dateDetailRaw;
            $dateDetail = Some::create(DateDetail::fromArray($dateDetailRawTyped));
        }
        if (array_key_exists('delayDetails', $data) && $data['delayDetails'] !== null) {
            $delayDetailsRaw = $data['delayDetails'];
            if (!is_array($delayDetailsRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "delayDetails" must be object, got %s.', get_debug_type($delayDetailsRaw)),
                );
            }
            /** @var array<string, mixed> $delayDetailsRawTyped */
            $delayDetailsRawTyped = $delayDetailsRaw;
            $delayDetails = Some::create(DelayDetail::fromArray($delayDetailsRawTyped));
        }
        if (array_key_exists('saturdayDelivery', $data) && $data['saturdayDelivery'] !== null) {
            $saturdayDeliveryRaw = $data['saturdayDelivery'];
            if (!is_bool($saturdayDeliveryRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "saturdayDelivery" must be bool, got %s.', get_debug_type($saturdayDeliveryRaw)),
                );
            }
            $saturdayDelivery = Some::create($saturdayDeliveryRaw);
        }
        if (array_key_exists('alternativeCommodityNames', $data) && $data['alternativeCommodityNames'] !== null) {
            $alternativeCommodityNamesRaw = $data['alternativeCommodityNames'];
            if (!(is_array($alternativeCommodityNamesRaw) && array_is_list($alternativeCommodityNamesRaw))) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "alternativeCommodityNames" must be list, got %s.',
                        get_debug_type($alternativeCommodityNamesRaw),
                    ),
                );
            }
            $alternativeCommodityNames = Some::create(array_map(static function (mixed $value): string {
                if (!is_string($value)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be string, got %s.', get_debug_type($value)),
                    );
                }

                return $value;
            }, $alternativeCommodityNamesRaw));
        }
        if (array_key_exists('transitDays', $data) && $data['transitDays'] !== null) {
            $transitDaysRaw = $data['transitDays'];
            if (!is_array($transitDaysRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "transitDays" must be object, got %s.', get_debug_type($transitDaysRaw)),
                );
            }
            /** @var array<string, mixed> $transitDaysRawTyped */
            $transitDaysRawTyped = $transitDaysRaw;
            $transitDays = Some::create(TransitDays::fromArray($transitDaysRawTyped));
        }
        if (array_key_exists('label', $data) && $data['label'] !== null) {
            $labelRaw = $data['label'];
            if (!is_string($labelRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "label" must be string, got %s.', get_debug_type($labelRaw)),
                );
            }
            $label = Some::create($labelRaw);
        }
        if (array_key_exists('commitMessageDetails', $data) && $data['commitMessageDetails'] !== null) {
            $commitMessageDetailsRaw = $data['commitMessageDetails'];
            if (!is_string($commitMessageDetailsRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "commitMessageDetails" must be string, got %s.',
                        get_debug_type($commitMessageDetailsRaw),
                    ),
                );
            }
            $commitMessageDetails = Some::create($commitMessageDetailsRaw);
        }
        if (array_key_exists('commodityName', $data) && $data['commodityName'] !== null) {
            $commodityNameRaw = $data['commodityName'];
            if (!is_string($commodityNameRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "commodityName" must be string, got %s.', get_debug_type($commodityNameRaw)),
                );
            }
            $commodityName = Some::create($commodityNameRaw);
        }
        $additionalProperties = array_diff_key(
            $data,
            [
                'daysInTransit' => true,
                'guaranteedType' => true,
                'smartPostCommitTime' => true,
                'dateDetail' => true,
                'delayDetails' => true,
                'saturdayDelivery' => true,
                'alternativeCommodityNames' => true,
                'transitDays' => true,
                'label' => true,
                'commitMessageDetails' => true,
                'commodityName' => true,
            ],
        );

        return new self(
            $daysInTransit,
            $guaranteedType,
            $smartPostCommitTime,
            $dateDetail,
            $delayDetails,
            $saturdayDelivery,
            $alternativeCommodityNames,
            $transitDays,
            $label,
            $commitMessageDetails,
            $commodityName,
            $additionalProperties,
        );
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $daysInTransitOption = $this->daysInTransit;
        if ($daysInTransitOption->isDefined()) {
            $daysInTransit = $daysInTransitOption->get();
            $dataArray['daysInTransit'] = $daysInTransit->value;
        }
        $guaranteedTypeOption = $this->guaranteedType;
        if ($guaranteedTypeOption->isDefined()) {
            $guaranteedType = $guaranteedTypeOption->get();
            $dataArray['guaranteedType'] = $guaranteedType->value;
        }
        $smartPostCommitTimeOption = $this->smartPostCommitTime;
        if ($smartPostCommitTimeOption->isDefined()) {
            $smartPostCommitTime = $smartPostCommitTimeOption->get();
            $dataArray['smartPostCommitTime'] = $smartPostCommitTime;
        }
        $dateDetailOption = $this->dateDetail;
        if ($dateDetailOption->isDefined()) {
            $dateDetail = $dateDetailOption->get();
            $dataArray['dateDetail'] = $normalizationTarget->model($dateDetail);
        }
        $delayDetailsOption = $this->delayDetails;
        if ($delayDetailsOption->isDefined()) {
            $delayDetails = $delayDetailsOption->get();
            $dataArray['delayDetails'] = $normalizationTarget->model($delayDetails);
        }
        $saturdayDeliveryOption = $this->saturdayDelivery;
        if ($saturdayDeliveryOption->isDefined()) {
            $saturdayDelivery = $saturdayDeliveryOption->get();
            $dataArray['saturdayDelivery'] = $saturdayDelivery;
        }
        $alternativeCommodityNamesOption = $this->alternativeCommodityNames;
        if ($alternativeCommodityNamesOption->isDefined()) {
            $alternativeCommodityNames = $alternativeCommodityNamesOption->get();
            $values = [];
            foreach ($alternativeCommodityNames as $value) {
                $values[] = $value;
            }
            $dataArray['alternativeCommodityNames'] = $values;
        }
        $transitDaysOption = $this->transitDays;
        if ($transitDaysOption->isDefined()) {
            $transitDays = $transitDaysOption->get();
            $dataArray['transitDays'] = $normalizationTarget->model($transitDays);
        }
        $labelOption = $this->label;
        if ($labelOption->isDefined()) {
            $label = $labelOption->get();
            $dataArray['label'] = $label;
        }
        $commitMessageDetailsOption = $this->commitMessageDetails;
        if ($commitMessageDetailsOption->isDefined()) {
            $commitMessageDetails = $commitMessageDetailsOption->get();
            $dataArray['commitMessageDetails'] = $commitMessageDetails;
        }
        $commodityNameOption = $this->commodityName;
        if ($commodityNameOption->isDefined()) {
            $commodityName = $commodityNameOption->get();
            $dataArray['commodityName'] = $commodityName;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): CommitDetail1Builder
    {
        return new CommitDetail1Builder(
            $this->daysInTransit,
            $this->guaranteedType,
            $this->smartPostCommitTime,
            $this->dateDetail,
            $this->delayDetails,
            $this->saturdayDelivery,
            $this->alternativeCommodityNames,
            $this->transitDays,
            $this->label,
            $this->commitMessageDetails,
            $this->commodityName,
            $this->additionalProperties,
        );
    }
}
