<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

/**
 * Builds a {@see CommitDetail1}.
 */
final class CommitDetail1Builder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<CommitDetail1DaysInTransit|UnknownEnumValue<string>>  $daysInTransit
     * @param Option<CommitDetail1GuaranteedType|UnknownEnumValue<string>> $guaranteedType
     * @param Option<string>                                               $smartPostCommitTime
     * @param Option<DateDetail>                                           $dateDetail
     * @param Option<DelayDetail>                                          $delayDetails
     * @param Option<bool>                                                 $saturdayDelivery
     * @param Option<list<string>>                                         $alternativeCommodityNames
     * @param Option<TransitDays>                                          $transitDays
     * @param Option<string>                                               $label
     * @param Option<string>                                               $commitMessageDetails
     * @param Option<string>                                               $commodityName
     * @param array<int|string, mixed>                                     $additionalProperties
     */
    public function __construct(
        private Option $daysInTransit,
        private Option $guaranteedType,
        private Option $smartPostCommitTime,
        private Option $dateDetail,
        private Option $delayDetails,
        private Option $saturdayDelivery,
        private Option $alternativeCommodityNames,
        private Option $transitDays,
        private Option $label,
        private Option $commitMessageDetails,
        private Option $commodityName,
        private array $additionalProperties,
    ) {
    }

    /**
     * Code indicating the number of transit days.
     *
     * Example: EIGHTEEN_DAYS
     */
    public function setDaysInTransit(CommitDetail1DaysInTransit $daysInTransit): self
    {
        $this->daysInTransit = Some::create($daysInTransit);

        return $this;
    }

    /**
     * Indicates if there is a guaranteed delivery option applied to the rate. This is for freight
     * rates only.
     *
     * Valid values
     *
     * GUARANTEED_MORNING - guaranteed delivery on morning of date specified.
     *
     * GUARANTEED_CLOSE_OF_BUSINESS - guaranteed delivery on date specified by close of day
     *
     * Example: GUARANTEED_MORNING
     */
    public function setGuaranteedType(CommitDetail1GuaranteedType $guaranteedType): self
    {
        $this->guaranteedType = Some::create($guaranteedType);

        return $this;
    }

    /**
     * CommitTime for SmartPost shipments.
     */
    public function setSmartPostCommitTime(string $smartPostCommitTime): self
    {
        $this->smartPostCommitTime = Some::create($smartPostCommitTime);

        return $this;
    }

    /**
     * These are date and time details.
     */
    public function setDateDetail(DateDetail $dateDetail): self
    {
        $this->dateDetail = Some::create($dateDetail);

        return $this;
    }

    /**
     * Information about why a shipment delivery is delayed and at what level.
     */
    public function setDelayDetails(DelayDetail $delayDetails): self
    {
        $this->delayDetails = Some::create($delayDetails);

        return $this;
    }

    /**
     * Specifies the saturdayDelivery.
     */
    public function setSaturdayDelivery(bool $saturdayDelivery): self
    {
        $this->saturdayDelivery = Some::create($saturdayDelivery);

        return $this;
    }

    /**
     * Specifies the alternate names of commodities.
     *
     * @param list<string> $alternativeCommodityNames
     */
    public function setAlternativeCommodityNames(array $alternativeCommodityNames): self
    {
        $this->alternativeCommodityNames = Some::create($alternativeCommodityNames);

        return $this;
    }

    /**
     * These are number of days the package/shipment is to be in transit. Applies to Ground and LTL
     * Freight; indicates minimum transit time for SmartPost.
     */
    public function setTransitDays(TransitDays $transitDays): self
    {
        $this->transitDays = Some::create($transitDays);

        return $this;
    }

    /**
     * This is an informational message to inform client Deliverydate is unavailable. If
     * commitTimestamp and transitTime are unavailable, then this is populated in the response in
     * the client language.
     *
     * Example: Deliverydate unavailable
     */
    public function setLabel(string $label): self
    {
        $this->label = Some::create($label);

        return $this;
    }

    /**
     * Messages concerning the ability to provide an accurate delivery commitment on an
     * International commit quote. These could be messages providing information about why a
     * commitment could not be returned or a successful message.
     *
     * Example: Message
     */
    public function setCommitMessageDetails(string $commitMessageDetails): self
    {
        $this->commitMessageDetails = Some::create($commitMessageDetails);

        return $this;
    }

    /**
     * The Commodity applicable to this commitment.
     *
     * Example: DOCUMENTS
     */
    public function setCommodityName(string $commodityName): self
    {
        $this->commodityName = Some::create($commodityName);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): CommitDetail1
    {
        return new CommitDetail1(
            $this->daysInTransit,
            $this->guaranteedType,
            $this->smartPostCommitTime,
            $this->dateDetail,
            $this->delayDetails,
            $this->saturdayDelivery,
            $this->alternativeCommodityNames,
            $this->transitDays,
            $this->label,
            $this->commitMessageDetails,
            $this->commodityName,
            $this->additionalProperties,
        );
    }
}
