<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

enum CommitDetail1GuaranteedType: string
{
    case GUARANTEED_MORNING = 'GUARANTEED_MORNING';
    case GUARANTEED_CLOSE_OF_BUSINESS = 'GUARANTEED_CLOSE_OF_BUSINESS';
}
