<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

/**
 * Builds a {@see CurrencyExchangeRate}.
 */
final class CurrencyExchangeRateBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>           $fromCurrency
     * @param Option<string>           $intoCurrency
     * @param Option<float>            $rate
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private Option $fromCurrency,
        private Option $intoCurrency,
        private Option $rate,
        private array $additionalProperties,
    ) {
    }

    /**
     * The currency code for the original (converted FROM) currency.
     */
    public function setFromCurrency(string $fromCurrency): self
    {
        $this->fromCurrency = Some::create($fromCurrency);

        return $this;
    }

    /**
     * The currency code for the final (converted INTO) currency.
     */
    public function setIntoCurrency(string $intoCurrency): self
    {
        $this->intoCurrency = Some::create($intoCurrency);

        return $this;
    }

    /**
     * Multiplier used to convert fromCurrency units to intoCurrency units.
     */
    public function setRate(float $rate): self
    {
        $this->rate = Some::create($rate);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): CurrencyExchangeRate
    {
        return new CurrencyExchangeRate(
            $this->fromCurrency,
            $this->intoCurrency,
            $this->rate,
            $this->additionalProperties,
        );
    }
}
