<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

enum DangerousGoodsContainerRadioactiveContainerClass: string
{
    case EXCEPTED_PACKAGE = 'EXCEPTED_PACKAGE';
    case INDUSTRIAL_IP1 = 'INDUSTRIAL_IP1';
    case INDUSTRIAL_IP2 = 'INDUSTRIAL_IP2';
    case INDUSTRIAL_IP3 = 'INDUSTRIAL_IP3';
    case TYPE_A = 'TYPE_A';
    case TYPE_B_M = 'TYPE_B_M';
    case TYPE_B_U = 'TYPE_B_U';
    case TYPE_C = 'TYPE_C';
}
