<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Override;
use Prefabcortex\FedexRatesAndTransitTimesApi\Exception\MalformedDataException;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\None;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

use function array_diff_key;
use function array_is_list;
use function array_key_exists;
use function array_map;
use function get_debug_type;
use function is_array;
use function is_int;
use function is_string;
use function sprintf;

final readonly class DangerousGoodsContainer implements SelfNormalizingModel
{
    /**
     * @param Option<string>                                                                    $offeror
     * @param Option<list<HazardousCommodityContent>>                                           $hazardousCommodities
     * @param Option<int>                                                                       $numberOfContainers
     * @param Option<string>                                                                    $containerType
     * @param Option<PhoneNumber>                                                               $emergencyContactNumber
     * @param Option<HazardousCommodityPackagingDetail>                                         $packaging
     * @param Option<DangerousGoodsContainerPackingType|UnknownEnumValue<string>>               $packingType
     * @param Option<DangerousGoodsContainerRadioactiveContainerClass|UnknownEnumValue<string>> $radioactiveContainerClass
     * @param array<int|string, mixed>                                                          $additionalProperties
     */
    public function __construct(
        private Option $offeror,
        private Option $hazardousCommodities,
        private Option $numberOfContainers,
        private Option $containerType,
        private Option $emergencyContactNumber,
        private Option $packaging,
        private Option $packingType,
        private Option $radioactiveContainerClass,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): DangerousGoodsContainerBuilder
    {
        return new DangerousGoodsContainerBuilder(
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            [],
        );
    }

    /**
     * Specify the shipper name(offeror) or contact number. Required on all shipping papers.
     *
     * @return Option<string>
     */
    public function getOfferor(): Option
    {
        return $this->offeror;
    }

    /**
     * Specify the kinds and quantities of all hazardous commodities in the current container.
     *
     * @return Option<list<HazardousCommodityContent>>
     */
    public function getHazardousCommodities(): Option
    {
        return $this->hazardousCommodities;
    }

    /**
     * Indicate the number of containers.
     *
     * @return Option<int>
     */
    public function getNumberOfContainers(): Option
    {
        return $this->numberOfContainers;
    }

    /**
     * Indicate the type of container.
     *
     * @return Option<string>
     */
    public function getContainerType(): Option
    {
        return $this->containerType;
    }

    /**
     * Indicates the telephone number to use for contact in the event of an emergency.
     *
     * @return Option<PhoneNumber>
     */
    public function getEmergencyContactNumber(): Option
    {
        return $this->emergencyContactNumber;
    }

    /**
     * Identifies number and type of packaging units for hazardous commodities.
     *
     * @return Option<HazardousCommodityPackagingDetail>
     */
    public function getPackaging(): Option
    {
        return $this->packaging;
    }

    /**
     * Indicate the packing type used.
     *
     * @return Option<DangerousGoodsContainerPackingType|UnknownEnumValue<string>>
     */
    public function getPackingType(): Option
    {
        return $this->packingType;
    }

    /**
     * Indicate the packaging type of the container used to package the radioactive materials.
     *
     * @return Option<DangerousGoodsContainerRadioactiveContainerClass|UnknownEnumValue<string>>
     */
    public function getRadioactiveContainerClass(): Option
    {
        return $this->radioactiveContainerClass;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $offeror = None::create();
        $hazardousCommodities = None::create();
        $numberOfContainers = None::create();
        $containerType = None::create();
        $emergencyContactNumber = None::create();
        $packaging = None::create();
        $packingType = None::create();
        $radioactiveContainerClass = None::create();
        if (array_key_exists('offeror', $data) && $data['offeror'] !== null) {
            $offerorRaw = $data['offeror'];
            if (!is_string($offerorRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "offeror" must be string, got %s.', get_debug_type($offerorRaw)),
                );
            }
            $offeror = Some::create($offerorRaw);
        }
        if (array_key_exists('hazardousCommodities', $data) && $data['hazardousCommodities'] !== null) {
            $hazardousCommoditiesRaw = $data['hazardousCommodities'];
            if (!(is_array($hazardousCommoditiesRaw) && array_is_list($hazardousCommoditiesRaw))) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "hazardousCommodities" must be list, got %s.',
                        get_debug_type($hazardousCommoditiesRaw),
                    ),
                );
            }
            $hazardousCommodities = Some::create(array_map(static function (mixed $value): HazardousCommodityContent {
                if (!is_array($value)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be object, got %s.', get_debug_type($value)),
                    );
                }
                /** @var array<string, mixed> $valueTyped */
                $valueTyped = $value;

                return HazardousCommodityContent::fromArray($valueTyped);
            }, $hazardousCommoditiesRaw));
        }
        if (array_key_exists('numberOfContainers', $data) && $data['numberOfContainers'] !== null) {
            $numberOfContainersRaw = $data['numberOfContainers'];
            if (!is_int($numberOfContainersRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "numberOfContainers" must be int, got %s.',
                        get_debug_type($numberOfContainersRaw),
                    ),
                );
            }
            $numberOfContainers = Some::create($numberOfContainersRaw);
        }
        if (array_key_exists('containerType', $data) && $data['containerType'] !== null) {
            $containerTypeRaw = $data['containerType'];
            if (!is_string($containerTypeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "containerType" must be string, got %s.', get_debug_type($containerTypeRaw)),
                );
            }
            $containerType = Some::create($containerTypeRaw);
        }
        if (array_key_exists('emergencyContactNumber', $data) && $data['emergencyContactNumber'] !== null) {
            $emergencyContactNumberRaw = $data['emergencyContactNumber'];
            if (!is_array($emergencyContactNumberRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "emergencyContactNumber" must be object, got %s.',
                        get_debug_type($emergencyContactNumberRaw),
                    ),
                );
            }
            /** @var non-empty-array<string, mixed> $emergencyContactNumberRawTyped */
            $emergencyContactNumberRawTyped = $emergencyContactNumberRaw;
            $emergencyContactNumber = Some::create(PhoneNumber::fromArray($emergencyContactNumberRawTyped));
        }
        if (array_key_exists('packaging', $data) && $data['packaging'] !== null) {
            $packagingRaw = $data['packaging'];
            if (!is_array($packagingRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "packaging" must be object, got %s.', get_debug_type($packagingRaw)),
                );
            }
            /** @var array<string, mixed> $packagingRawTyped */
            $packagingRawTyped = $packagingRaw;
            $packaging = Some::create(HazardousCommodityPackagingDetail::fromArray($packagingRawTyped));
        }
        if (array_key_exists('packingType', $data) && $data['packingType'] !== null) {
            $packingTypeRaw = $data['packingType'];
            if (!is_string($packingTypeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "packingType" must be string, got %s.', get_debug_type($packingTypeRaw)),
                );
            }
            $packingType = Some::create(
                DangerousGoodsContainerPackingType::tryFrom($packingTypeRaw) ?? UnknownEnumValue::of($packingTypeRaw),
            );
        }
        if (array_key_exists('radioactiveContainerClass', $data) && $data['radioactiveContainerClass'] !== null) {
            $radioactiveContainerClassRaw = $data['radioactiveContainerClass'];
            if (!is_string($radioactiveContainerClassRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "radioactiveContainerClass" must be string, got %s.',
                        get_debug_type($radioactiveContainerClassRaw),
                    ),
                );
            }
            $radioactiveContainerClass = Some::create(
                DangerousGoodsContainerRadioactiveContainerClass::tryFrom($radioactiveContainerClassRaw)
                    ?? UnknownEnumValue::of($radioactiveContainerClassRaw),
            );
        }
        $additionalProperties = array_diff_key(
            $data,
            [
                'offeror' => true,
                'hazardousCommodities' => true,
                'numberOfContainers' => true,
                'containerType' => true,
                'emergencyContactNumber' => true,
                'packaging' => true,
                'packingType' => true,
                'radioactiveContainerClass' => true,
            ],
        );

        return new self(
            $offeror,
            $hazardousCommodities,
            $numberOfContainers,
            $containerType,
            $emergencyContactNumber,
            $packaging,
            $packingType,
            $radioactiveContainerClass,
            $additionalProperties,
        );
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $offerorOption = $this->offeror;
        if ($offerorOption->isDefined()) {
            $offeror = $offerorOption->get();
            $dataArray['offeror'] = $offeror;
        }
        $hazardousCommoditiesOption = $this->hazardousCommodities;
        if ($hazardousCommoditiesOption->isDefined()) {
            $hazardousCommodities = $hazardousCommoditiesOption->get();
            $values = [];
            foreach ($hazardousCommodities as $value) {
                $values[] = $normalizationTarget->model($value);
            }
            $dataArray['hazardousCommodities'] = $values;
        }
        $numberOfContainersOption = $this->numberOfContainers;
        if ($numberOfContainersOption->isDefined()) {
            $numberOfContainers = $numberOfContainersOption->get();
            $dataArray['numberOfContainers'] = $numberOfContainers;
        }
        $containerTypeOption = $this->containerType;
        if ($containerTypeOption->isDefined()) {
            $containerType = $containerTypeOption->get();
            $dataArray['containerType'] = $containerType;
        }
        $emergencyContactNumberOption = $this->emergencyContactNumber;
        if ($emergencyContactNumberOption->isDefined()) {
            $emergencyContactNumber = $emergencyContactNumberOption->get();
            $dataArray['emergencyContactNumber'] = $normalizationTarget->model($emergencyContactNumber);
        }
        $packagingOption = $this->packaging;
        if ($packagingOption->isDefined()) {
            $packaging = $packagingOption->get();
            $dataArray['packaging'] = $normalizationTarget->model($packaging);
        }
        $packingTypeOption = $this->packingType;
        if ($packingTypeOption->isDefined()) {
            $packingType = $packingTypeOption->get();
            $dataArray['packingType'] = $packingType->value;
        }
        $radioactiveContainerClassOption = $this->radioactiveContainerClass;
        if ($radioactiveContainerClassOption->isDefined()) {
            $radioactiveContainerClass = $radioactiveContainerClassOption->get();
            $dataArray['radioactiveContainerClass'] = $radioactiveContainerClass->value;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): DangerousGoodsContainerBuilder
    {
        return new DangerousGoodsContainerBuilder(
            $this->offeror,
            $this->hazardousCommodities,
            $this->numberOfContainers,
            $this->containerType,
            $this->emergencyContactNumber,
            $this->packaging,
            $this->packingType,
            $this->radioactiveContainerClass,
            $this->additionalProperties,
        );
    }
}
