<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

/**
 * Builds a {@see DeliveryOnInvoiceAcceptanceDetailRecipientAddress}.
 */
final class DeliveryOnInvoiceAcceptanceDetailRecipientAddressBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<list<string>>     $streetLines
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private string $countryCode,
        private Option $streetLines,
        private array $additionalProperties,
    ) {
    }

    /**
     * The two-letter country code.
     *
     * Maximum length is 2.
     *
     * Example: US
     *
     * <a onclick='loadDocReference("countrycodes")'>Click here to see Country Codes</a>
     */
    public function setCountryCode(string $countryCode): self
    {
        $this->countryCode = $countryCode;

        return $this;
    }

    /**
     * This is the combination of number, street name, etc.
     *
     * Note: At least one line is required and streetlines more than 3 will be ignored. Empty lines
     * should not be included. Maximum Length per line is 35.
     *
     * Example: [10 FedEx Parkway, Suite 302, .etc.]
     *
     * @param list<string> $streetLines
     */
    public function setStreetLines(array $streetLines): self
    {
        $this->streetLines = Some::create($streetLines);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): DeliveryOnInvoiceAcceptanceDetailRecipientAddress
    {
        return new DeliveryOnInvoiceAcceptanceDetailRecipientAddress(
            $this->countryCode,
            $this->streetLines,
            $this->additionalProperties,
        );
    }
}
