<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

/**
 * Builds a {@see DeliveryOnInvoiceAcceptanceDetailRecipientContact}.
 */
final class DeliveryOnInvoiceAcceptanceDetailRecipientContactBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>           $faxNumber
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private string $companyName,
        private string $personName,
        private string $phoneNumber,
        private Option $faxNumber,
        private array $additionalProperties,
    ) {
    }

    /**
     * This is a placeholder for company name. Maximum length is 35.
     */
    public function setCompanyName(string $companyName): self
    {
        $this->companyName = $companyName;

        return $this;
    }

    /**
     * This is a placeholder for contact person's name. Maximum Length is 70.
     */
    public function setPersonName(string $personName): self
    {
        $this->personName = $personName;

        return $this;
    }

    /**
     * This is a placeholder for phone number associated with this contact. Maximum length is 15.
     */
    public function setPhoneNumber(string $phoneNumber): self
    {
        $this->phoneNumber = $phoneNumber;

        return $this;
    }

    /**
     * This is a placeholder for Fax number. Maximum length is 15.
     */
    public function setFaxNumber(string $faxNumber): self
    {
        $this->faxNumber = Some::create($faxNumber);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): DeliveryOnInvoiceAcceptanceDetailRecipientContact
    {
        return new DeliveryOnInvoiceAcceptanceDetailRecipientContact(
            $this->companyName,
            $this->personName,
            $this->phoneNumber,
            $this->faxNumber,
            $this->additionalProperties,
        );
    }
}
