<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

/**
 * Builds a {@see DeliveryOnInvoiceAcceptanceDetailRecipient}.
 */
final class DeliveryOnInvoiceAcceptanceDetailRecipientBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<AccountNumber>    $accountNumber
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private DeliveryOnInvoiceAcceptanceDetailRecipientAddress $address,
        private DeliveryOnInvoiceAcceptanceDetailRecipientContact $contact,
        private Option $accountNumber,
        private array $additionalProperties,
    ) {
    }

    public function setAddress(DeliveryOnInvoiceAcceptanceDetailRecipientAddress $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function setContact(DeliveryOnInvoiceAcceptanceDetailRecipientContact $contact): self
    {
        $this->contact = $contact;

        return $this;
    }

    /**
     * This is the Account number details.
     *
     * <i>Note:<ul><li>If the paymentType is Sender, then the account number is optional in
     * shippingChargesPayment.</li></ul>
     */
    public function setAccountNumber(AccountNumber $accountNumber): self
    {
        $this->accountNumber = Some::create($accountNumber);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): DeliveryOnInvoiceAcceptanceDetailRecipient
    {
        return new DeliveryOnInvoiceAcceptanceDetailRecipient(
            $this->address,
            $this->contact,
            $this->accountNumber,
            $this->additionalProperties,
        );
    }
}
