<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

/**
 * Builds a {@see DeliveryOnInvoiceAcceptanceDetail}.
 */
final class DeliveryOnInvoiceAcceptanceDetailBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<DeliveryOnInvoiceAcceptanceDetailRecipient> $recipient
     * @param array<int|string, mixed>                           $additionalProperties
     */
    public function __construct(private Option $recipient, private array $additionalProperties)
    {
    }

    public function setRecipient(DeliveryOnInvoiceAcceptanceDetailRecipient $recipient): self
    {
        $this->recipient = Some::create($recipient);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): DeliveryOnInvoiceAcceptanceDetail
    {
        return new DeliveryOnInvoiceAcceptanceDetail($this->recipient, $this->additionalProperties);
    }
}
