<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Override;
use Prefabcortex\FedexRatesAndTransitTimesApi\Exception\MalformedDataException;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\None;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_int;
use function is_string;
use function sprintf;

final readonly class Dimensions1 implements SelfNormalizingModel
{
    /**
     * @param Option<int>                                       $length
     * @param Option<int>                                       $width
     * @param Option<int>                                       $height
     * @param Option<Dimensions1Units|UnknownEnumValue<string>> $units
     * @param array<int|string, mixed>                          $additionalProperties
     */
    public function __construct(
        private Option $length,
        private Option $width,
        private Option $height,
        private Option $units,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): Dimensions1Builder
    {
        return new Dimensions1Builder(None::create(), None::create(), None::create(), None::create(), []);
    }

    /**
     * Indicate the length of the package. No implied decimal places. Maximum value: 999.
     *
     * Example: 20
     *
     * @return Option<int>
     */
    public function getLength(): Option
    {
        return $this->length;
    }

    /**
     * Indicate the width of the package. No implied decimal places. Maximum value: 999.
     *
     * Example: 10
     *
     * @return Option<int>
     */
    public function getWidth(): Option
    {
        return $this->width;
    }

    /**
     * Indicate the height of the package. No implied decimal places. Maximum value: 999.
     *
     * Example: 10
     *
     * @return Option<int>
     */
    public function getHeight(): Option
    {
        return $this->height;
    }

    /**
     * Indicate the unit of measure for the provided dimensions.
     *
     * Valid Values are:<ul><li>IN - Inches</li><li>CM - Centimeters</li></ul>
     *
     * @return Option<Dimensions1Units|UnknownEnumValue<string>>
     */
    public function getUnits(): Option
    {
        return $this->units;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $length = None::create();
        $width = None::create();
        $height = None::create();
        $units = None::create();
        if (array_key_exists('length', $data) && $data['length'] !== null) {
            $lengthRaw = $data['length'];
            if (!is_int($lengthRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "length" must be int, got %s.', get_debug_type($lengthRaw)),
                );
            }
            $length = Some::create($lengthRaw);
        }
        if (array_key_exists('width', $data) && $data['width'] !== null) {
            $widthRaw = $data['width'];
            if (!is_int($widthRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "width" must be int, got %s.', get_debug_type($widthRaw)),
                );
            }
            $width = Some::create($widthRaw);
        }
        if (array_key_exists('height', $data) && $data['height'] !== null) {
            $heightRaw = $data['height'];
            if (!is_int($heightRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "height" must be int, got %s.', get_debug_type($heightRaw)),
                );
            }
            $height = Some::create($heightRaw);
        }
        if (array_key_exists('units', $data) && $data['units'] !== null) {
            $unitsRaw = $data['units'];
            if (!is_string($unitsRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "units" must be string, got %s.', get_debug_type($unitsRaw)),
                );
            }
            $units = Some::create(Dimensions1Units::tryFrom($unitsRaw) ?? UnknownEnumValue::of($unitsRaw));
        }
        $additionalProperties = array_diff_key(
            $data,
            ['length' => true, 'width' => true, 'height' => true, 'units' => true],
        );

        return new self($length, $width, $height, $units, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $lengthOption = $this->length;
        if ($lengthOption->isDefined()) {
            $length = $lengthOption->get();
            $dataArray['length'] = $length;
        }
        $widthOption = $this->width;
        if ($widthOption->isDefined()) {
            $width = $widthOption->get();
            $dataArray['width'] = $width;
        }
        $heightOption = $this->height;
        if ($heightOption->isDefined()) {
            $height = $heightOption->get();
            $dataArray['height'] = $height;
        }
        $unitsOption = $this->units;
        if ($unitsOption->isDefined()) {
            $units = $unitsOption->get();
            $dataArray['units'] = $units->value;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): Dimensions1Builder
    {
        return new Dimensions1Builder(
            $this->length,
            $this->width,
            $this->height,
            $this->units,
            $this->additionalProperties,
        );
    }
}
