<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Override;
use Prefabcortex\FedexRatesAndTransitTimesApi\Exception\MalformedDataException;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\None;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_array;
use function is_string;
use function sprintf;

final readonly class EmailRecipient implements SelfNormalizingModel
{
    /**
     * @param Option<EmailOptionsRequested>                       $optionsRequested
     * @param Option<EmailRecipientRole|UnknownEnumValue<string>> $role
     * @param Option<Locale>                                      $locale
     * @param array<int|string, mixed>                            $additionalProperties
     */
    public function __construct(
        private string $emailAddress,
        private Option $optionsRequested,
        private Option $role,
        private Option $locale,
        private array $additionalProperties,
    ) {
    }

    public static function builder(string $emailAddress): EmailRecipientBuilder
    {
        return new EmailRecipientBuilder($emailAddress, None::create(), None::create(), None::create(), []);
    }

    /**
     * This is the placeholder for Email address of the end-user to be notified of the return label.
     * Maximum length is 200 characters.
     */
    public function getEmailAddress(): string
    {
        return $this->emailAddress;
    }

    /**
     * Indicates how the email notifications for the pending shipment need to be processed.
     *
     * @return Option<EmailOptionsRequested>
     */
    public function getOptionsRequested(): Option
    {
        return $this->optionsRequested;
    }

    /**
     * Specifies the role of the recipient to the pending shipment.
     *
     * @return Option<EmailRecipientRole|UnknownEnumValue<string>>
     */
    public function getRole(): Option
    {
        return $this->role;
    }

    /**
     * These are Locale details.
     *
     * Note: If the locale is left blank or an invalid locale is entered, an error message is
     * returned in response.
     *
     * @return Option<Locale>
     */
    public function getLocale(): Option
    {
        return $this->locale;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $emailAddress = null;
        $optionsRequested = None::create();
        $role = None::create();
        $locale = None::create();
        if (array_key_exists('emailAddress', $data)) {
            $emailAddressRaw = $data['emailAddress'];
            if (!is_string($emailAddressRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "emailAddress" must be string, got %s.', get_debug_type($emailAddressRaw)),
                );
            }
            $emailAddress = $emailAddressRaw;
        }
        if (array_key_exists('optionsRequested', $data) && $data['optionsRequested'] !== null) {
            $optionsRequestedRaw = $data['optionsRequested'];
            if (!is_array($optionsRequestedRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "optionsRequested" must be object, got %s.',
                        get_debug_type($optionsRequestedRaw),
                    ),
                );
            }
            /** @var array<string, mixed> $optionsRequestedRawTyped */
            $optionsRequestedRawTyped = $optionsRequestedRaw;
            $optionsRequested = Some::create(EmailOptionsRequested::fromArray($optionsRequestedRawTyped));
        }
        if (array_key_exists('role', $data) && $data['role'] !== null) {
            $roleRaw = $data['role'];
            if (!is_string($roleRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "role" must be string, got %s.', get_debug_type($roleRaw)),
                );
            }
            $role = Some::create(EmailRecipientRole::tryFrom($roleRaw) ?? UnknownEnumValue::of($roleRaw));
        }
        if (array_key_exists('locale', $data) && $data['locale'] !== null) {
            $localeRaw = $data['locale'];
            if (!is_array($localeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "locale" must be object, got %s.', get_debug_type($localeRaw)),
                );
            }
            /** @var array<string, mixed> $localeRawTyped */
            $localeRawTyped = $localeRaw;
            $locale = Some::create(Locale::fromArray($localeRawTyped));
        }
        $additionalProperties = array_diff_key(
            $data,
            ['emailAddress' => true, 'optionsRequested' => true, 'role' => true, 'locale' => true],
        );
        if ($emailAddress === null) {
            throw new MalformedDataException('Required property "emailAddress" is missing from the document.');
        }

        return new self($emailAddress, $optionsRequested, $role, $locale, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $dataArray['emailAddress'] = $this->emailAddress;
        $optionsRequestedOption = $this->optionsRequested;
        if ($optionsRequestedOption->isDefined()) {
            $optionsRequested = $optionsRequestedOption->get();
            $dataArray['optionsRequested'] = $normalizationTarget->model($optionsRequested);
        }
        $roleOption = $this->role;
        if ($roleOption->isDefined()) {
            $role = $roleOption->get();
            $dataArray['role'] = $role->value;
        }
        $localeOption = $this->locale;
        if ($localeOption->isDefined()) {
            $locale = $localeOption->get();
            $dataArray['locale'] = $normalizationTarget->model($locale);
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): EmailRecipientBuilder
    {
        return new EmailRecipientBuilder(
            $this->emailAddress,
            $this->optionsRequested,
            $this->role,
            $this->locale,
            $this->additionalProperties,
        );
    }
}
