<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Override;
use Prefabcortex\FedexRatesAndTransitTimesApi\Exception\MalformedDataException;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\None;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

use function array_diff_key;
use function array_is_list;
use function array_key_exists;
use function array_map;
use function get_debug_type;
use function is_array;
use function is_string;
use function sprintf;

final readonly class EmailNotificationRecipient implements SelfNormalizingModel
{
    /**
     * @param Option<list<EmailNotificationRecipientNotificationEventTypeItem|UnknownEnumValue<string>>> $notificationEventType
     * @param Option<SmsDetail>                                                                          $smsDetail
     * @param Option<EmailNotificationRecipientNotificationFormatType|UnknownEnumValue<string>>          $notificationFormatType
     * @param Option<EmailNotificationRecipientEmailNotificationRecipientType|UnknownEnumValue<string>>  $emailNotificationRecipientType
     * @param Option<EmailNotificationRecipientNotificationType|UnknownEnumValue<string>>                $notificationType
     * @param Option<string>                                                                             $locale
     * @param array<int|string, mixed>                                                                   $additionalProperties
     */
    public function __construct(
        private string $emailAddress,
        private Option $notificationEventType,
        private Option $smsDetail,
        private Option $notificationFormatType,
        private Option $emailNotificationRecipientType,
        private Option $notificationType,
        private Option $locale,
        private array $additionalProperties,
    ) {
    }

    public static function builder(string $emailAddress): EmailNotificationRecipientBuilder
    {
        return new EmailNotificationRecipientBuilder(
            $emailAddress,
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            [],
        );
    }

    /**
     * Identifies the email address associated with this contact.
     */
    public function getEmailAddress(): string
    {
        return $this->emailAddress;
    }

    /**
     * Specifies notification event type.
     *
     * @return Option<list<EmailNotificationRecipientNotificationEventTypeItem|UnknownEnumValue<string>>>
     */
    public function getNotificationEventType(): Option
    {
        return $this->notificationEventType;
    }

    /**
     * Specifies the SMS notification details.
     *
     * Conditionally required for SMS notifications.
     *
     * @return Option<SmsDetail>
     */
    public function getSmsDetail(): Option
    {
        return $this->smsDetail;
    }

    /**
     * Specifies Notification Format Type.
     *
     * @return Option<EmailNotificationRecipientNotificationFormatType|UnknownEnumValue<string>>
     */
    public function getNotificationFormatType(): Option
    {
        return $this->notificationFormatType;
    }

    /**
     * Required Email Notification Recipient Type.
     *
     * @return Option<EmailNotificationRecipientEmailNotificationRecipientType|UnknownEnumValue<string>>
     */
    public function getEmailNotificationRecipientType(): Option
    {
        return $this->emailNotificationRecipientType;
    }

    /**
     * Specifies the type of the notification received.
     *
     * @return Option<EmailNotificationRecipientNotificationType|UnknownEnumValue<string>>
     */
    public function getNotificationType(): Option
    {
        return $this->notificationType;
    }

    /**
     * Specify the locale details.
     *
     * Example: 'en_US'
     *
     * <a onclick='loadDocReference("locales")'>Click here to see the list of available locales
     *
     * </a>
     *
     * Note: If the locale is left blank or an invalid locale is entered, an error message is
     * returned in response.
     *
     * @return Option<string>
     */
    public function getLocale(): Option
    {
        return $this->locale;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $emailAddress = null;
        $notificationEventType = None::create();
        $smsDetail = None::create();
        $notificationFormatType = None::create();
        $emailNotificationRecipientType = None::create();
        $notificationType = None::create();
        $locale = None::create();
        if (array_key_exists('emailAddress', $data)) {
            $emailAddressRaw = $data['emailAddress'];
            if (!is_string($emailAddressRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "emailAddress" must be string, got %s.', get_debug_type($emailAddressRaw)),
                );
            }
            $emailAddress = $emailAddressRaw;
        }
        if (array_key_exists('notificationEventType', $data) && $data['notificationEventType'] !== null) {
            $notificationEventTypeRaw = $data['notificationEventType'];
            if (!(is_array($notificationEventTypeRaw) && array_is_list($notificationEventTypeRaw))) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "notificationEventType" must be list, got %s.',
                        get_debug_type($notificationEventTypeRaw),
                    ),
                );
            }
            $notificationEventType = Some::create(
                array_map(
                    static function (
                        mixed $value,
                    ): EmailNotificationRecipientNotificationEventTypeItem|UnknownEnumValue {
                        if (!is_string($value)) {
                            throw new MalformedDataException(
                                sprintf('Array item must be string, got %s.', get_debug_type($value)),
                            );
                        }

                        return EmailNotificationRecipientNotificationEventTypeItem::tryFrom($value)
                            ?? UnknownEnumValue::of($value);
                    },
                    $notificationEventTypeRaw,
                ),
            );
        }
        if (array_key_exists('smsDetail', $data) && $data['smsDetail'] !== null) {
            $smsDetailRaw = $data['smsDetail'];
            if (!is_array($smsDetailRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "smsDetail" must be object, got %s.', get_debug_type($smsDetailRaw)),
                );
            }
            /** @var non-empty-array<string, mixed> $smsDetailRawTyped */
            $smsDetailRawTyped = $smsDetailRaw;
            $smsDetail = Some::create(SmsDetail::fromArray($smsDetailRawTyped));
        }
        if (array_key_exists('notificationFormatType', $data) && $data['notificationFormatType'] !== null) {
            $notificationFormatTypeRaw = $data['notificationFormatType'];
            if (!is_string($notificationFormatTypeRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "notificationFormatType" must be string, got %s.',
                        get_debug_type($notificationFormatTypeRaw),
                    ),
                );
            }
            $notificationFormatType = Some::create(
                EmailNotificationRecipientNotificationFormatType::tryFrom($notificationFormatTypeRaw)
                    ?? UnknownEnumValue::of($notificationFormatTypeRaw),
            );
        }
        if (
            array_key_exists('emailNotificationRecipientType', $data)
            && $data['emailNotificationRecipientType'] !== null
        ) {
            $emailNotificationRecipientTypeRaw = $data['emailNotificationRecipientType'];
            if (!is_string($emailNotificationRecipientTypeRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "emailNotificationRecipientType" must be string, got %s.',
                        get_debug_type($emailNotificationRecipientTypeRaw),
                    ),
                );
            }
            $emailNotificationRecipientType = Some::create(
                EmailNotificationRecipientEmailNotificationRecipientType::tryFrom($emailNotificationRecipientTypeRaw)
                    ?? UnknownEnumValue::of($emailNotificationRecipientTypeRaw),
            );
        }
        if (array_key_exists('notificationType', $data) && $data['notificationType'] !== null) {
            $notificationTypeRaw = $data['notificationType'];
            if (!is_string($notificationTypeRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "notificationType" must be string, got %s.',
                        get_debug_type($notificationTypeRaw),
                    ),
                );
            }
            $notificationType = Some::create(
                EmailNotificationRecipientNotificationType::tryFrom($notificationTypeRaw)
                    ?? UnknownEnumValue::of($notificationTypeRaw),
            );
        }
        if (array_key_exists('locale', $data) && $data['locale'] !== null) {
            $localeRaw = $data['locale'];
            if (!is_string($localeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "locale" must be string, got %s.', get_debug_type($localeRaw)),
                );
            }
            $locale = Some::create($localeRaw);
        }
        $additionalProperties = array_diff_key(
            $data,
            [
                'emailAddress' => true,
                'notificationEventType' => true,
                'smsDetail' => true,
                'notificationFormatType' => true,
                'emailNotificationRecipientType' => true,
                'notificationType' => true,
                'locale' => true,
            ],
        );
        if ($emailAddress === null) {
            throw new MalformedDataException('Required property "emailAddress" is missing from the document.');
        }

        return new self(
            $emailAddress,
            $notificationEventType,
            $smsDetail,
            $notificationFormatType,
            $emailNotificationRecipientType,
            $notificationType,
            $locale,
            $additionalProperties,
        );
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $dataArray['emailAddress'] = $this->emailAddress;
        $notificationEventTypeOption = $this->notificationEventType;
        if ($notificationEventTypeOption->isDefined()) {
            $notificationEventType = $notificationEventTypeOption->get();
            $values = [];
            foreach ($notificationEventType as $value) {
                $values[] = $value->value;
            }
            $dataArray['notificationEventType'] = $values;
        }
        $smsDetailOption = $this->smsDetail;
        if ($smsDetailOption->isDefined()) {
            $smsDetail = $smsDetailOption->get();
            $dataArray['smsDetail'] = $normalizationTarget->model($smsDetail);
        }
        $notificationFormatTypeOption = $this->notificationFormatType;
        if ($notificationFormatTypeOption->isDefined()) {
            $notificationFormatType = $notificationFormatTypeOption->get();
            $dataArray['notificationFormatType'] = $notificationFormatType->value;
        }
        $emailNotificationRecipientTypeOption = $this->emailNotificationRecipientType;
        if ($emailNotificationRecipientTypeOption->isDefined()) {
            $emailNotificationRecipientType = $emailNotificationRecipientTypeOption->get();
            $dataArray['emailNotificationRecipientType'] = $emailNotificationRecipientType->value;
        }
        $notificationTypeOption = $this->notificationType;
        if ($notificationTypeOption->isDefined()) {
            $notificationType = $notificationTypeOption->get();
            $dataArray['notificationType'] = $notificationType->value;
        }
        $localeOption = $this->locale;
        if ($localeOption->isDefined()) {
            $locale = $localeOption->get();
            $dataArray['locale'] = $locale;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): EmailNotificationRecipientBuilder
    {
        return new EmailNotificationRecipientBuilder(
            $this->emailAddress,
            $this->notificationEventType,
            $this->smsDetail,
            $this->notificationFormatType,
            $this->emailNotificationRecipientType,
            $this->notificationType,
            $this->locale,
            $this->additionalProperties,
        );
    }
}
