<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

enum EMailNotificationDetailPrintedReferencePrintedReferenceType: string
{
    case BILL_OF_LADING = 'BILL_OF_LADING';
    case CONSIGNEE_ID_NUMBER = 'CONSIGNEE_ID_NUMBER';
    case INTERLINE_PRO_NUMBER = 'INTERLINE_PRO_NUMBER';
    case PO_NUMBER = 'PO_NUMBER';
    case SHIPPER_ID_NUMBER = 'SHIPPER_ID_NUMBER';
    case SHIPPER_ID1_NUMBER = 'SHIPPER_ID1_NUMBER';
    case SHIPPER_ID2_NUMBER = 'SHIPPER_ID2_NUMBER';
}
