<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

/**
 * Builds a {@see EmailRecipient}.
 */
final class EmailRecipientBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<EmailOptionsRequested>                       $optionsRequested
     * @param Option<EmailRecipientRole|UnknownEnumValue<string>> $role
     * @param Option<Locale>                                      $locale
     * @param array<int|string, mixed>                            $additionalProperties
     */
    public function __construct(
        private string $emailAddress,
        private Option $optionsRequested,
        private Option $role,
        private Option $locale,
        private array $additionalProperties,
    ) {
    }

    /**
     * This is the placeholder for Email address of the end-user to be notified of the return label.
     * Maximum length is 200 characters.
     */
    public function setEmailAddress(string $emailAddress): self
    {
        $this->emailAddress = $emailAddress;

        return $this;
    }

    /**
     * Indicates how the email notifications for the pending shipment need to be processed.
     */
    public function setOptionsRequested(EmailOptionsRequested $optionsRequested): self
    {
        $this->optionsRequested = Some::create($optionsRequested);

        return $this;
    }

    /**
     * Specifies the role of the recipient to the pending shipment.
     */
    public function setRole(EmailRecipientRole $role): self
    {
        $this->role = Some::create($role);

        return $this;
    }

    /**
     * These are Locale details.
     *
     * Note: If the locale is left blank or an invalid locale is entered, an error message is
     * returned in response.
     */
    public function setLocale(Locale $locale): self
    {
        $this->locale = Some::create($locale);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): EmailRecipient
    {
        return new EmailRecipient(
            $this->emailAddress,
            $this->optionsRequested,
            $this->role,
            $this->locale,
            $this->additionalProperties,
        );
    }
}
