<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

/**
 * Builds a {@see HazardousCommodityInnerReceptacleDetail}.
 */
final class HazardousCommodityInnerReceptacleDetailBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<HazardousCommodityQuantityDetail> $quantity
     * @param array<int|string, mixed>                 $additionalProperties
     */
    public function __construct(private Option $quantity, private array $additionalProperties)
    {
    }

    /**
     * Specifies Hazardous Commodity Quantity Detail.
     */
    public function setQuantity(HazardousCommodityQuantityDetail $quantity): self
    {
        $this->quantity = Some::create($quantity);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): HazardousCommodityInnerReceptacleDetail
    {
        return new HazardousCommodityInnerReceptacleDetail($this->quantity, $this->additionalProperties);
    }
}
