<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

/**
 * Builds a {@see HazardousCommodityPackingDetail}.
 */
final class HazardousCommodityPackingDetailBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>           $packingInstructions
     * @param Option<bool>             $cargoAircraftOnly
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private Option $packingInstructions,
        private Option $cargoAircraftOnly,
        private array $additionalProperties,
    ) {
    }

    /**
     * Indicates the coded specification for how commodity is to be packed.
     */
    public function setPackingInstructions(string $packingInstructions): self
    {
        $this->packingInstructions = Some::create($packingInstructions);

        return $this;
    }

    /**
     * Indicates the shipment is packaged/documented for movement ONLY on cargo aircraft.
     */
    public function setCargoAircraftOnly(bool $cargoAircraftOnly): self
    {
        $this->cargoAircraftOnly = Some::create($cargoAircraftOnly);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): HazardousCommodityPackingDetail
    {
        return new HazardousCommodityPackingDetail(
            $this->packingInstructions,
            $this->cargoAircraftOnly,
            $this->additionalProperties,
        );
    }
}
