<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

/**
 * Builds a {@see HazardousCommodityOptionDetail}.
 */
final class HazardousCommodityOptionDetailBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<HazardousCommodityOptionDetailLabelTextOption|UnknownEnumValue<string>> $labelTextOption
     * @param Option<string>                                                                 $customerSuppliedLabelText
     * @param array<int|string, mixed>                                                       $additionalProperties
     */
    public function __construct(
        private Option $labelTextOption,
        private Option $customerSuppliedLabelText,
        private array $additionalProperties,
    ) {
    }

    /**
     * Specifies how the customer wishes the label text to be handled for this commodity in this
     * package.
     */
    public function setLabelTextOption(HazardousCommodityOptionDetailLabelTextOption $labelTextOption): self
    {
        $this->labelTextOption = Some::create($labelTextOption);

        return $this;
    }

    /**
     * Text used in labeling the commodity under control of the labelTextOption field.
     */
    public function setCustomerSuppliedLabelText(string $customerSuppliedLabelText): self
    {
        $this->customerSuppliedLabelText = Some::create($customerSuppliedLabelText);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): HazardousCommodityOptionDetail
    {
        return new HazardousCommodityOptionDetail(
            $this->labelTextOption,
            $this->customerSuppliedLabelText,
            $this->additionalProperties,
        );
    }
}
