<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

/**
 * Builds a {@see HomeDeliveryPremiumDetail}.
 */
final class HomeDeliveryPremiumDetailBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>                                                                    $shipTimestamp
     * @param Option<HomeDeliveryPremiumDetailHomedeliveryPremiumType|UnknownEnumValue<string>> $homedeliveryPremiumType
     * @param array<int|string, mixed>                                                          $additionalProperties
     */
    public function __construct(
        private Option $shipTimestamp,
        private Option $homedeliveryPremiumType,
        private array $additionalProperties,
    ) {
    }

    /**
     * This is shipment date. Both the date and time portions of the string are expected to be used.
     * The date should not be a past date or a date more than 10 days in the future. The time is the
     * local time of the shipment based on the shipper's time zone.
     *
     * Formats: YYYY-MM-DD, YYYY-MM-DD HH:MM:SS
     *
     * Example: 2024-06-14 19:23:51
     */
    public function setShipTimestamp(string $shipTimestamp): self
    {
        $this->shipTimestamp = Some::create($shipTimestamp);

        return $this;
    }

    /**
     * This is Home Delivery Premium Type. It allows to specify additional premimum service options
     * for the home delivery shipment. Can specify Evening delivery or a Date certain, or can
     * specify appointment for the delivery.
     */
    public function setHomedeliveryPremiumType(
        HomeDeliveryPremiumDetailHomedeliveryPremiumType $homedeliveryPremiumType,
    ): self {
        $this->homedeliveryPremiumType = Some::create($homedeliveryPremiumType);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): HomeDeliveryPremiumDetail
    {
        return new HomeDeliveryPremiumDetail(
            $this->shipTimestamp,
            $this->homedeliveryPremiumType,
            $this->additionalProperties,
        );
    }
}
