<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

/**
 * Builds a {@see InternationalTrafficInArmsRegulationsDetail}.
 */
final class InternationalTrafficInArmsRegulationsDetailBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>           $licenseOrExemptionNumber
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(private Option $licenseOrExemptionNumber, private array $additionalProperties)
    {
    }

    /**
     * The export or license number for the ITAR shipment.
     *
     * Example: 9871234
     */
    public function setLicenseOrExemptionNumber(string $licenseOrExemptionNumber): self
    {
        $this->licenseOrExemptionNumber = Some::create($licenseOrExemptionNumber);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): InternationalTrafficInArmsRegulationsDetail
    {
        return new InternationalTrafficInArmsRegulationsDetail(
            $this->licenseOrExemptionNumber,
            $this->additionalProperties,
        );
    }
}
