<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Override;
use Prefabcortex\FedexRatesAndTransitTimesApi\Exception\MalformedDataException;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\None;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_string;
use function sprintf;

final readonly class InternationalControlledExportDetail implements SelfNormalizingModel
{
    /**
     * @param Option<InternationalControlledExportDetailType|UnknownEnumValue<string>> $type
     * @param array<int|string, mixed>                                                 $additionalProperties
     */
    public function __construct(private Option $type, private array $additionalProperties)
    {
    }

    public static function builder(): InternationalControlledExportDetailBuilder
    {
        return new InternationalControlledExportDetailBuilder(None::create(), []);
    }

    /**
     * Indicate International Controlled Export Type.
     *
     * Example: WAREHOUSE_WITHDRAWAL
     *
     * @return Option<InternationalControlledExportDetailType|UnknownEnumValue<string>>
     */
    public function getType(): Option
    {
        return $this->type;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $type = None::create();
        if (array_key_exists('type', $data) && $data['type'] !== null) {
            $typeRaw = $data['type'];
            if (!is_string($typeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "type" must be string, got %s.', get_debug_type($typeRaw)),
                );
            }
            $type = Some::create(
                InternationalControlledExportDetailType::tryFrom($typeRaw) ?? UnknownEnumValue::of($typeRaw),
            );
        }
        $additionalProperties = array_diff_key($data, ['type' => true]);

        return new self($type, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $typeOption = $this->type;
        if ($typeOption->isDefined()) {
            $type = $typeOption->get();
            $dataArray['type'] = $type->value;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): InternationalControlledExportDetailBuilder
    {
        return new InternationalControlledExportDetailBuilder($this->type, $this->additionalProperties);
    }
}
