<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Override;
use Prefabcortex\FedexRatesAndTransitTimesApi\Exception\MalformedDataException;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\None;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

use function array_diff_key;
use function array_is_list;
use function array_key_exists;
use function array_map;
use function get_debug_type;
use function is_array;
use function is_bool;
use function is_int;
use function is_string;
use function sprintf;

final readonly class OperationalDetail implements SelfNormalizingModel
{
    /**
     * @param Option<list<string>>     $originLocationIds
     * @param Option<list<string>>     $commitDays
     * @param Option<string>           $serviceCode
     * @param Option<string>           $airportId
     * @param Option<string>           $scac
     * @param Option<list<string>>     $originServiceAreas
     * @param Option<string>           $deliveryDay
     * @param Option<list<int>>        $originLocationNumbers
     * @param Option<string>           $destinationPostalCode
     * @param Option<string>           $commitDate
     * @param Option<string>           $astraDescription
     * @param Option<string>           $deliveryDate
     * @param Option<list<string>>     $deliveryEligibilities
     * @param Option<bool>             $ineligibleForMoneyBackGuarantee
     * @param Option<string>           $maximumTransitTime
     * @param Option<string>           $astraPlannedServiceLevel
     * @param Option<list<string>>     $destinationLocationIds
     * @param Option<list<string>>     $destinationLocationStateOrProvinceCodes
     * @param Option<string>           $transitTime
     * @param Option<string>           $packagingCode
     * @param Option<list<int>>        $destinationLocationNumbers
     * @param Option<string>           $publishedDeliveryTime
     * @param Option<list<string>>     $countryCodes
     * @param Option<list<string>>     $stateOrProvinceCodes
     * @param Option<string>           $ursaPrefixCode
     * @param Option<string>           $ursaSuffixCode
     * @param Option<list<string>>     $destinationServiceAreas
     * @param Option<list<string>>     $originPostalCodes
     * @param Option<string>           $customTransitTime
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private Option $originLocationIds,
        private Option $commitDays,
        private Option $serviceCode,
        private Option $airportId,
        private Option $scac,
        private Option $originServiceAreas,
        private Option $deliveryDay,
        private Option $originLocationNumbers,
        private Option $destinationPostalCode,
        private Option $commitDate,
        private Option $astraDescription,
        private Option $deliveryDate,
        private Option $deliveryEligibilities,
        private Option $ineligibleForMoneyBackGuarantee,
        private Option $maximumTransitTime,
        private Option $astraPlannedServiceLevel,
        private Option $destinationLocationIds,
        private Option $destinationLocationStateOrProvinceCodes,
        private Option $transitTime,
        private Option $packagingCode,
        private Option $destinationLocationNumbers,
        private Option $publishedDeliveryTime,
        private Option $countryCodes,
        private Option $stateOrProvinceCodes,
        private Option $ursaPrefixCode,
        private Option $ursaSuffixCode,
        private Option $destinationServiceAreas,
        private Option $originPostalCodes,
        private Option $customTransitTime,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): OperationalDetailBuilder
    {
        return new OperationalDetailBuilder(
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            [],
        );
    }

    /**
     * Indicate the location ID of the origin of shipment.
     *
     * Example: YBZA
     *
     * @return Option<list<string>>
     */
    public function getOriginLocationIds(): Option
    {
        return $this->originLocationIds;
    }

    /**
     * Indicate the delivery commitment day.
     *
     * Example: MON
     *
     * @return Option<list<string>>
     */
    public function getCommitDays(): Option
    {
        return $this->commitDays;
    }

    /**
     * Indicate the service code.
     *
     * Example: 06
     *
     * @return Option<string>
     */
    public function getServiceCode(): Option
    {
        return $this->serviceCode;
    }

    /**
     * Specify the Airport Id.
     *
     * Example: MEM
     *
     * @return Option<string>
     */
    public function getAirportId(): Option
    {
        return $this->airportId;
    }

    /**
     * Indicate the Standard Carrier Alpha Code (SCAC) is a privately controlled US code used to
     * identify vessel operating common carriers (VOCC). It is typically two to four letters long.
     *
     * @return Option<string>
     */
    public function getScac(): Option
    {
        return $this->scac;
    }

    /**
     * Specify origin service area.
     *
     * Example: AM
     *
     * @return Option<list<string>>
     */
    public function getOriginServiceAreas(): Option
    {
        return $this->originServiceAreas;
    }

    /**
     * Specify the delivery commitment day.
     *
     * Example: SAT
     *
     * @return Option<string>
     */
    public function getDeliveryDay(): Option
    {
        return $this->deliveryDay;
    }

    /**
     * Specify the origin location ID.
     *
     * Example: 6121
     *
     * @return Option<list<int>>
     */
    public function getOriginLocationNumbers(): Option
    {
        return $this->originLocationNumbers;
    }

    /**
     * Indicate the destination postal code.
     *
     * Example: 38017
     *
     * @return Option<string>
     */
    public function getDestinationPostalCode(): Option
    {
        return $this->destinationPostalCode;
    }

    /**
     * Indicate the shipment Commit Date.
     *
     * Example: 2019-07-22T08:30:00
     *
     * @return Option<string>
     */
    public function getCommitDate(): Option
    {
        return $this->commitDate;
    }

    /**
     * Indicate the ASTRA description for the label.
     *
     * Example: XXXL1ST
     *
     * @return Option<string>
     */
    public function getAstraDescription(): Option
    {
        return $this->astraDescription;
    }

    /**
     * Indicate the delivery date.
     *
     * Example: 2019-07-22T08:30:00
     *
     * @return Option<string>
     */
    public function getDeliveryDate(): Option
    {
        return $this->deliveryDate;
    }

    /**
     * Indicate the delivery eligibilities.
     *
     * @return Option<list<string>>
     */
    public function getDeliveryEligibilities(): Option
    {
        return $this->deliveryEligibilities;
    }

    /**
     * indicate if ineligible For Money Back Guarantee.
     *
     * @return Option<bool>
     */
    public function getIneligibleForMoneyBackGuarantee(): Option
    {
        return $this->ineligibleForMoneyBackGuarantee;
    }

    /**
     * Specify Maximum transit time.
     *
     * Example: THREE_DAYS
     *
     * @return Option<string>
     */
    public function getMaximumTransitTime(): Option
    {
        return $this->maximumTransitTime;
    }

    /**
     * Indicate Astra Planned Service Level.
     *
     * Example: astraPlannedServicelevel
     *
     * @return Option<string>
     */
    public function getAstraPlannedServiceLevel(): Option
    {
        return $this->astraPlannedServiceLevel;
    }

    /**
     * Indicate Destination Location Ids.
     *
     * Example: HKAA
     *
     * @return Option<list<string>>
     */
    public function getDestinationLocationIds(): Option
    {
        return $this->destinationLocationIds;
    }

    /**
     * Indicate destination location State Or Province code.
     *
     * Example: TN
     *
     * <a onclick='loadDocReference("canadaprovincecodes")'>Click here to see State Or Province
     * Code</a>
     *
     * @return Option<list<string>>
     */
    public function getDestinationLocationStateOrProvinceCodes(): Option
    {
        return $this->destinationLocationStateOrProvinceCodes;
    }

    /**
     * Indicate the Transit Time in days.
     *
     * Example: THREE_DAYS
     *
     * @return Option<string>
     */
    public function getTransitTime(): Option
    {
        return $this->transitTime;
    }

    /**
     * Indicate the Packaging Code.
     *
     * Example: M1M1M1
     *
     * @return Option<string>
     */
    public function getPackagingCode(): Option
    {
        return $this->packagingCode;
    }

    /**
     * Indicate the Destination Location Numbers.
     *
     * Example: 386
     *
     * @return Option<list<int>>
     */
    public function getDestinationLocationNumbers(): Option
    {
        return $this->destinationLocationNumbers;
    }

    /**
     * Indicate the Published Delivery Time.
     *
     * Example: THREE_DAYS
     *
     * @return Option<string>
     */
    public function getPublishedDeliveryTime(): Option
    {
        return $this->publishedDeliveryTime;
    }

    /**
     * Indicate the Country Code.
     *
     * Example: [ US, IN]
     *
     * <a onclick='loadDocReference("countrycodes")'>Click here to see Country Codes</a>
     *
     * @return Option<list<string>>
     */
    public function getCountryCodes(): Option
    {
        return $this->countryCodes;
    }

    /**
     * Specifies state Or Province Code. State code is required for US, CA, PR and not required for
     * other countries. Conditional. Max length is 2.
     *
     * Example: TN
     *
     * @return Option<list<string>>
     */
    public function getStateOrProvinceCodes(): Option
    {
        return $this->stateOrProvinceCodes;
    }

    /**
     * This is FedEx URSA Prefix Code.
     *
     * Example: PrefixCode
     *
     * @return Option<string>
     */
    public function getUrsaPrefixCode(): Option
    {
        return $this->ursaPrefixCode;
    }

    /**
     * This is URSA Suffix Code.
     *
     * Example: SuffixCode
     *
     * @return Option<string>
     */
    public function getUrsaSuffixCode(): Option
    {
        return $this->ursaSuffixCode;
    }

    /**
     * This is Destination Service Areas.
     *
     * Example: A2
     *
     * @return Option<list<string>>
     */
    public function getDestinationServiceAreas(): Option
    {
        return $this->destinationServiceAreas;
    }

    /**
     * This is Origin Postal Codes.
     *
     * Example: M1M1M1
     *
     * @return Option<list<string>>
     */
    public function getOriginPostalCodes(): Option
    {
        return $this->originPostalCodes;
    }

    /**
     * This is Custom Transit Time in days.
     *
     * Example: THREE_DAYS
     *
     * @return Option<string>
     */
    public function getCustomTransitTime(): Option
    {
        return $this->customTransitTime;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $originLocationIds = None::create();
        $commitDays = None::create();
        $serviceCode = None::create();
        $airportId = None::create();
        $scac = None::create();
        $originServiceAreas = None::create();
        $deliveryDay = None::create();
        $originLocationNumbers = None::create();
        $destinationPostalCode = None::create();
        $commitDate = None::create();
        $astraDescription = None::create();
        $deliveryDate = None::create();
        $deliveryEligibilities = None::create();
        $ineligibleForMoneyBackGuarantee = None::create();
        $maximumTransitTime = None::create();
        $astraPlannedServiceLevel = None::create();
        $destinationLocationIds = None::create();
        $destinationLocationStateOrProvinceCodes = None::create();
        $transitTime = None::create();
        $packagingCode = None::create();
        $destinationLocationNumbers = None::create();
        $publishedDeliveryTime = None::create();
        $countryCodes = None::create();
        $stateOrProvinceCodes = None::create();
        $ursaPrefixCode = None::create();
        $ursaSuffixCode = None::create();
        $destinationServiceAreas = None::create();
        $originPostalCodes = None::create();
        $customTransitTime = None::create();
        if (array_key_exists('originLocationIds', $data) && $data['originLocationIds'] !== null) {
            $originLocationIdsRaw = $data['originLocationIds'];
            if (!(is_array($originLocationIdsRaw) && array_is_list($originLocationIdsRaw))) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "originLocationIds" must be list, got %s.',
                        get_debug_type($originLocationIdsRaw),
                    ),
                );
            }
            $originLocationIds = Some::create(array_map(static function (mixed $value): string {
                if (!is_string($value)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be string, got %s.', get_debug_type($value)),
                    );
                }

                return $value;
            }, $originLocationIdsRaw));
        }
        if (array_key_exists('commitDays', $data) && $data['commitDays'] !== null) {
            $commitDaysRaw = $data['commitDays'];
            if (!(is_array($commitDaysRaw) && array_is_list($commitDaysRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "commitDays" must be list, got %s.', get_debug_type($commitDaysRaw)),
                );
            }
            $commitDays = Some::create(array_map(static function (mixed $value_1): string {
                if (!is_string($value_1)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be string, got %s.', get_debug_type($value_1)),
                    );
                }

                return $value_1;
            }, $commitDaysRaw));
        }
        if (array_key_exists('serviceCode', $data) && $data['serviceCode'] !== null) {
            $serviceCodeRaw = $data['serviceCode'];
            if (!is_string($serviceCodeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "serviceCode" must be string, got %s.', get_debug_type($serviceCodeRaw)),
                );
            }
            $serviceCode = Some::create($serviceCodeRaw);
        }
        if (array_key_exists('airportId', $data) && $data['airportId'] !== null) {
            $airportIdRaw = $data['airportId'];
            if (!is_string($airportIdRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "airportId" must be string, got %s.', get_debug_type($airportIdRaw)),
                );
            }
            $airportId = Some::create($airportIdRaw);
        }
        if (array_key_exists('scac', $data) && $data['scac'] !== null) {
            $scacRaw = $data['scac'];
            if (!is_string($scacRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "scac" must be string, got %s.', get_debug_type($scacRaw)),
                );
            }
            $scac = Some::create($scacRaw);
        }
        if (array_key_exists('originServiceAreas', $data) && $data['originServiceAreas'] !== null) {
            $originServiceAreasRaw = $data['originServiceAreas'];
            if (!(is_array($originServiceAreasRaw) && array_is_list($originServiceAreasRaw))) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "originServiceAreas" must be list, got %s.',
                        get_debug_type($originServiceAreasRaw),
                    ),
                );
            }
            $originServiceAreas = Some::create(array_map(static function (mixed $value_2): string {
                if (!is_string($value_2)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be string, got %s.', get_debug_type($value_2)),
                    );
                }

                return $value_2;
            }, $originServiceAreasRaw));
        }
        if (array_key_exists('deliveryDay', $data) && $data['deliveryDay'] !== null) {
            $deliveryDayRaw = $data['deliveryDay'];
            if (!is_string($deliveryDayRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "deliveryDay" must be string, got %s.', get_debug_type($deliveryDayRaw)),
                );
            }
            $deliveryDay = Some::create($deliveryDayRaw);
        }
        if (array_key_exists('originLocationNumbers', $data) && $data['originLocationNumbers'] !== null) {
            $originLocationNumbersRaw = $data['originLocationNumbers'];
            if (!(is_array($originLocationNumbersRaw) && array_is_list($originLocationNumbersRaw))) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "originLocationNumbers" must be list, got %s.',
                        get_debug_type($originLocationNumbersRaw),
                    ),
                );
            }
            $originLocationNumbers = Some::create(array_map(static function (mixed $value_3): int {
                if (!is_int($value_3)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be int, got %s.', get_debug_type($value_3)),
                    );
                }

                return $value_3;
            }, $originLocationNumbersRaw));
        }
        if (array_key_exists('destinationPostalCode', $data) && $data['destinationPostalCode'] !== null) {
            $destinationPostalCodeRaw = $data['destinationPostalCode'];
            if (!is_string($destinationPostalCodeRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "destinationPostalCode" must be string, got %s.',
                        get_debug_type($destinationPostalCodeRaw),
                    ),
                );
            }
            $destinationPostalCode = Some::create($destinationPostalCodeRaw);
        }
        if (array_key_exists('commitDate', $data) && $data['commitDate'] !== null) {
            $commitDateRaw = $data['commitDate'];
            if (!is_string($commitDateRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "commitDate" must be string, got %s.', get_debug_type($commitDateRaw)),
                );
            }
            $commitDate = Some::create($commitDateRaw);
        }
        if (array_key_exists('astraDescription', $data) && $data['astraDescription'] !== null) {
            $astraDescriptionRaw = $data['astraDescription'];
            if (!is_string($astraDescriptionRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "astraDescription" must be string, got %s.',
                        get_debug_type($astraDescriptionRaw),
                    ),
                );
            }
            $astraDescription = Some::create($astraDescriptionRaw);
        }
        if (array_key_exists('deliveryDate', $data) && $data['deliveryDate'] !== null) {
            $deliveryDateRaw = $data['deliveryDate'];
            if (!is_string($deliveryDateRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "deliveryDate" must be string, got %s.', get_debug_type($deliveryDateRaw)),
                );
            }
            $deliveryDate = Some::create($deliveryDateRaw);
        }
        if (array_key_exists('deliveryEligibilities', $data) && $data['deliveryEligibilities'] !== null) {
            $deliveryEligibilitiesRaw = $data['deliveryEligibilities'];
            if (!(is_array($deliveryEligibilitiesRaw) && array_is_list($deliveryEligibilitiesRaw))) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "deliveryEligibilities" must be list, got %s.',
                        get_debug_type($deliveryEligibilitiesRaw),
                    ),
                );
            }
            $deliveryEligibilities = Some::create(array_map(static function (mixed $value_4): string {
                if (!is_string($value_4)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be string, got %s.', get_debug_type($value_4)),
                    );
                }

                return $value_4;
            }, $deliveryEligibilitiesRaw));
        }
        if (
            array_key_exists('ineligibleForMoneyBackGuarantee', $data)
            && $data['ineligibleForMoneyBackGuarantee'] !== null
        ) {
            $ineligibleForMoneyBackGuaranteeRaw = $data['ineligibleForMoneyBackGuarantee'];
            if (!is_bool($ineligibleForMoneyBackGuaranteeRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "ineligibleForMoneyBackGuarantee" must be bool, got %s.',
                        get_debug_type($ineligibleForMoneyBackGuaranteeRaw),
                    ),
                );
            }
            $ineligibleForMoneyBackGuarantee = Some::create($ineligibleForMoneyBackGuaranteeRaw);
        }
        if (array_key_exists('MaximumTransitTime', $data) && $data['MaximumTransitTime'] !== null) {
            $maximumTransitTimeRaw = $data['MaximumTransitTime'];
            if (!is_string($maximumTransitTimeRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "MaximumTransitTime" must be string, got %s.',
                        get_debug_type($maximumTransitTimeRaw),
                    ),
                );
            }
            $maximumTransitTime = Some::create($maximumTransitTimeRaw);
        }
        if (array_key_exists('astraPlannedServiceLevel', $data) && $data['astraPlannedServiceLevel'] !== null) {
            $astraPlannedServiceLevelRaw = $data['astraPlannedServiceLevel'];
            if (!is_string($astraPlannedServiceLevelRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "astraPlannedServiceLevel" must be string, got %s.',
                        get_debug_type($astraPlannedServiceLevelRaw),
                    ),
                );
            }
            $astraPlannedServiceLevel = Some::create($astraPlannedServiceLevelRaw);
        }
        if (array_key_exists('destinationLocationIds', $data) && $data['destinationLocationIds'] !== null) {
            $destinationLocationIdsRaw = $data['destinationLocationIds'];
            if (!(is_array($destinationLocationIdsRaw) && array_is_list($destinationLocationIdsRaw))) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "destinationLocationIds" must be list, got %s.',
                        get_debug_type($destinationLocationIdsRaw),
                    ),
                );
            }
            $destinationLocationIds = Some::create(array_map(static function (mixed $value_5): string {
                if (!is_string($value_5)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be string, got %s.', get_debug_type($value_5)),
                    );
                }

                return $value_5;
            }, $destinationLocationIdsRaw));
        }
        if (
            array_key_exists('destinationLocationStateOrProvinceCodes', $data)
            && $data['destinationLocationStateOrProvinceCodes'] !== null
        ) {
            $destinationLocationStateOrProvinceCodesRaw = $data['destinationLocationStateOrProvinceCodes'];
            if (!(is_array($destinationLocationStateOrProvinceCodesRaw) && array_is_list($destinationLocationStateOrProvinceCodesRaw))) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "destinationLocationStateOrProvinceCodes" must be list, got %s.',
                        get_debug_type($destinationLocationStateOrProvinceCodesRaw),
                    ),
                );
            }
            $destinationLocationStateOrProvinceCodes = Some::create(array_map(static function (mixed $value_6): string {
                if (!is_string($value_6)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be string, got %s.', get_debug_type($value_6)),
                    );
                }

                return $value_6;
            }, $destinationLocationStateOrProvinceCodesRaw));
        }
        if (array_key_exists('transitTime', $data) && $data['transitTime'] !== null) {
            $transitTimeRaw = $data['transitTime'];
            if (!is_string($transitTimeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "transitTime" must be string, got %s.', get_debug_type($transitTimeRaw)),
                );
            }
            $transitTime = Some::create($transitTimeRaw);
        }
        if (array_key_exists('packagingCode', $data) && $data['packagingCode'] !== null) {
            $packagingCodeRaw = $data['packagingCode'];
            if (!is_string($packagingCodeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "packagingCode" must be string, got %s.', get_debug_type($packagingCodeRaw)),
                );
            }
            $packagingCode = Some::create($packagingCodeRaw);
        }
        if (array_key_exists('destinationLocationNumbers', $data) && $data['destinationLocationNumbers'] !== null) {
            $destinationLocationNumbersRaw = $data['destinationLocationNumbers'];
            if (!(is_array($destinationLocationNumbersRaw) && array_is_list($destinationLocationNumbersRaw))) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "destinationLocationNumbers" must be list, got %s.',
                        get_debug_type($destinationLocationNumbersRaw),
                    ),
                );
            }
            $destinationLocationNumbers = Some::create(array_map(static function (mixed $value_7): int {
                if (!is_int($value_7)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be int, got %s.', get_debug_type($value_7)),
                    );
                }

                return $value_7;
            }, $destinationLocationNumbersRaw));
        }
        if (array_key_exists('publishedDeliveryTime', $data) && $data['publishedDeliveryTime'] !== null) {
            $publishedDeliveryTimeRaw = $data['publishedDeliveryTime'];
            if (!is_string($publishedDeliveryTimeRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "publishedDeliveryTime" must be string, got %s.',
                        get_debug_type($publishedDeliveryTimeRaw),
                    ),
                );
            }
            $publishedDeliveryTime = Some::create($publishedDeliveryTimeRaw);
        }
        if (array_key_exists('countryCodes', $data) && $data['countryCodes'] !== null) {
            $countryCodesRaw = $data['countryCodes'];
            if (!(is_array($countryCodesRaw) && array_is_list($countryCodesRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "countryCodes" must be list, got %s.', get_debug_type($countryCodesRaw)),
                );
            }
            $countryCodes = Some::create(array_map(static function (mixed $value_8): string {
                if (!is_string($value_8)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be string, got %s.', get_debug_type($value_8)),
                    );
                }

                return $value_8;
            }, $countryCodesRaw));
        }
        if (array_key_exists('stateOrProvinceCodes', $data) && $data['stateOrProvinceCodes'] !== null) {
            $stateOrProvinceCodesRaw = $data['stateOrProvinceCodes'];
            if (!(is_array($stateOrProvinceCodesRaw) && array_is_list($stateOrProvinceCodesRaw))) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "stateOrProvinceCodes" must be list, got %s.',
                        get_debug_type($stateOrProvinceCodesRaw),
                    ),
                );
            }
            $stateOrProvinceCodes = Some::create(array_map(static function (mixed $value_9): string {
                if (!is_string($value_9)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be string, got %s.', get_debug_type($value_9)),
                    );
                }

                return $value_9;
            }, $stateOrProvinceCodesRaw));
        }
        if (array_key_exists('ursaPrefixCode', $data) && $data['ursaPrefixCode'] !== null) {
            $ursaPrefixCodeRaw = $data['ursaPrefixCode'];
            if (!is_string($ursaPrefixCodeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "ursaPrefixCode" must be string, got %s.', get_debug_type($ursaPrefixCodeRaw)),
                );
            }
            $ursaPrefixCode = Some::create($ursaPrefixCodeRaw);
        }
        if (array_key_exists('ursaSuffixCode', $data) && $data['ursaSuffixCode'] !== null) {
            $ursaSuffixCodeRaw = $data['ursaSuffixCode'];
            if (!is_string($ursaSuffixCodeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "ursaSuffixCode" must be string, got %s.', get_debug_type($ursaSuffixCodeRaw)),
                );
            }
            $ursaSuffixCode = Some::create($ursaSuffixCodeRaw);
        }
        if (array_key_exists('destinationServiceAreas', $data) && $data['destinationServiceAreas'] !== null) {
            $destinationServiceAreasRaw = $data['destinationServiceAreas'];
            if (!(is_array($destinationServiceAreasRaw) && array_is_list($destinationServiceAreasRaw))) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "destinationServiceAreas" must be list, got %s.',
                        get_debug_type($destinationServiceAreasRaw),
                    ),
                );
            }
            $destinationServiceAreas = Some::create(array_map(static function (mixed $value_10): string {
                if (!is_string($value_10)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be string, got %s.', get_debug_type($value_10)),
                    );
                }

                return $value_10;
            }, $destinationServiceAreasRaw));
        }
        if (array_key_exists('originPostalCodes', $data) && $data['originPostalCodes'] !== null) {
            $originPostalCodesRaw = $data['originPostalCodes'];
            if (!(is_array($originPostalCodesRaw) && array_is_list($originPostalCodesRaw))) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "originPostalCodes" must be list, got %s.',
                        get_debug_type($originPostalCodesRaw),
                    ),
                );
            }
            $originPostalCodes = Some::create(array_map(static function (mixed $value_11): string {
                if (!is_string($value_11)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be string, got %s.', get_debug_type($value_11)),
                    );
                }

                return $value_11;
            }, $originPostalCodesRaw));
        }
        if (array_key_exists('customTransitTime', $data) && $data['customTransitTime'] !== null) {
            $customTransitTimeRaw = $data['customTransitTime'];
            if (!is_string($customTransitTimeRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "customTransitTime" must be string, got %s.',
                        get_debug_type($customTransitTimeRaw),
                    ),
                );
            }
            $customTransitTime = Some::create($customTransitTimeRaw);
        }
        $additionalProperties = array_diff_key(
            $data,
            [
                'originLocationIds' => true,
                'commitDays' => true,
                'serviceCode' => true,
                'airportId' => true,
                'scac' => true,
                'originServiceAreas' => true,
                'deliveryDay' => true,
                'originLocationNumbers' => true,
                'destinationPostalCode' => true,
                'commitDate' => true,
                'astraDescription' => true,
                'deliveryDate' => true,
                'deliveryEligibilities' => true,
                'ineligibleForMoneyBackGuarantee' => true,
                'MaximumTransitTime' => true,
                'astraPlannedServiceLevel' => true,
                'destinationLocationIds' => true,
                'destinationLocationStateOrProvinceCodes' => true,
                'transitTime' => true,
                'packagingCode' => true,
                'destinationLocationNumbers' => true,
                'publishedDeliveryTime' => true,
                'countryCodes' => true,
                'stateOrProvinceCodes' => true,
                'ursaPrefixCode' => true,
                'ursaSuffixCode' => true,
                'destinationServiceAreas' => true,
                'originPostalCodes' => true,
                'customTransitTime' => true,
            ],
        );

        return new self(
            $originLocationIds,
            $commitDays,
            $serviceCode,
            $airportId,
            $scac,
            $originServiceAreas,
            $deliveryDay,
            $originLocationNumbers,
            $destinationPostalCode,
            $commitDate,
            $astraDescription,
            $deliveryDate,
            $deliveryEligibilities,
            $ineligibleForMoneyBackGuarantee,
            $maximumTransitTime,
            $astraPlannedServiceLevel,
            $destinationLocationIds,
            $destinationLocationStateOrProvinceCodes,
            $transitTime,
            $packagingCode,
            $destinationLocationNumbers,
            $publishedDeliveryTime,
            $countryCodes,
            $stateOrProvinceCodes,
            $ursaPrefixCode,
            $ursaSuffixCode,
            $destinationServiceAreas,
            $originPostalCodes,
            $customTransitTime,
            $additionalProperties,
        );
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $originLocationIdsOption = $this->originLocationIds;
        if ($originLocationIdsOption->isDefined()) {
            $originLocationIds = $originLocationIdsOption->get();
            $values = [];
            foreach ($originLocationIds as $value) {
                $values[] = $value;
            }
            $dataArray['originLocationIds'] = $values;
        }
        $commitDaysOption = $this->commitDays;
        if ($commitDaysOption->isDefined()) {
            $commitDays = $commitDaysOption->get();
            $values_1 = [];
            foreach ($commitDays as $value_1) {
                $values_1[] = $value_1;
            }
            $dataArray['commitDays'] = $values_1;
        }
        $serviceCodeOption = $this->serviceCode;
        if ($serviceCodeOption->isDefined()) {
            $serviceCode = $serviceCodeOption->get();
            $dataArray['serviceCode'] = $serviceCode;
        }
        $airportIdOption = $this->airportId;
        if ($airportIdOption->isDefined()) {
            $airportId = $airportIdOption->get();
            $dataArray['airportId'] = $airportId;
        }
        $scacOption = $this->scac;
        if ($scacOption->isDefined()) {
            $scac = $scacOption->get();
            $dataArray['scac'] = $scac;
        }
        $originServiceAreasOption = $this->originServiceAreas;
        if ($originServiceAreasOption->isDefined()) {
            $originServiceAreas = $originServiceAreasOption->get();
            $values_2 = [];
            foreach ($originServiceAreas as $value_2) {
                $values_2[] = $value_2;
            }
            $dataArray['originServiceAreas'] = $values_2;
        }
        $deliveryDayOption = $this->deliveryDay;
        if ($deliveryDayOption->isDefined()) {
            $deliveryDay = $deliveryDayOption->get();
            $dataArray['deliveryDay'] = $deliveryDay;
        }
        $originLocationNumbersOption = $this->originLocationNumbers;
        if ($originLocationNumbersOption->isDefined()) {
            $originLocationNumbers = $originLocationNumbersOption->get();
            $values_3 = [];
            foreach ($originLocationNumbers as $value_3) {
                $values_3[] = $value_3;
            }
            $dataArray['originLocationNumbers'] = $values_3;
        }
        $destinationPostalCodeOption = $this->destinationPostalCode;
        if ($destinationPostalCodeOption->isDefined()) {
            $destinationPostalCode = $destinationPostalCodeOption->get();
            $dataArray['destinationPostalCode'] = $destinationPostalCode;
        }
        $commitDateOption = $this->commitDate;
        if ($commitDateOption->isDefined()) {
            $commitDate = $commitDateOption->get();
            $dataArray['commitDate'] = $commitDate;
        }
        $astraDescriptionOption = $this->astraDescription;
        if ($astraDescriptionOption->isDefined()) {
            $astraDescription = $astraDescriptionOption->get();
            $dataArray['astraDescription'] = $astraDescription;
        }
        $deliveryDateOption = $this->deliveryDate;
        if ($deliveryDateOption->isDefined()) {
            $deliveryDate = $deliveryDateOption->get();
            $dataArray['deliveryDate'] = $deliveryDate;
        }
        $deliveryEligibilitiesOption = $this->deliveryEligibilities;
        if ($deliveryEligibilitiesOption->isDefined()) {
            $deliveryEligibilities = $deliveryEligibilitiesOption->get();
            $values_4 = [];
            foreach ($deliveryEligibilities as $value_4) {
                $values_4[] = $value_4;
            }
            $dataArray['deliveryEligibilities'] = $values_4;
        }
        $ineligibleForMoneyBackGuaranteeOption = $this->ineligibleForMoneyBackGuarantee;
        if ($ineligibleForMoneyBackGuaranteeOption->isDefined()) {
            $ineligibleForMoneyBackGuarantee = $ineligibleForMoneyBackGuaranteeOption->get();
            $dataArray['ineligibleForMoneyBackGuarantee'] = $ineligibleForMoneyBackGuarantee;
        }
        $maximumTransitTimeOption = $this->maximumTransitTime;
        if ($maximumTransitTimeOption->isDefined()) {
            $maximumTransitTime = $maximumTransitTimeOption->get();
            $dataArray['MaximumTransitTime'] = $maximumTransitTime;
        }
        $astraPlannedServiceLevelOption = $this->astraPlannedServiceLevel;
        if ($astraPlannedServiceLevelOption->isDefined()) {
            $astraPlannedServiceLevel = $astraPlannedServiceLevelOption->get();
            $dataArray['astraPlannedServiceLevel'] = $astraPlannedServiceLevel;
        }
        $destinationLocationIdsOption = $this->destinationLocationIds;
        if ($destinationLocationIdsOption->isDefined()) {
            $destinationLocationIds = $destinationLocationIdsOption->get();
            $values_5 = [];
            foreach ($destinationLocationIds as $value_5) {
                $values_5[] = $value_5;
            }
            $dataArray['destinationLocationIds'] = $values_5;
        }
        $destinationLocationStateOrProvinceCodesOption = $this->destinationLocationStateOrProvinceCodes;
        if ($destinationLocationStateOrProvinceCodesOption->isDefined()) {
            $destinationLocationStateOrProvinceCodes = $destinationLocationStateOrProvinceCodesOption->get();
            $values_6 = [];
            foreach ($destinationLocationStateOrProvinceCodes as $value_6) {
                $values_6[] = $value_6;
            }
            $dataArray['destinationLocationStateOrProvinceCodes'] = $values_6;
        }
        $transitTimeOption = $this->transitTime;
        if ($transitTimeOption->isDefined()) {
            $transitTime = $transitTimeOption->get();
            $dataArray['transitTime'] = $transitTime;
        }
        $packagingCodeOption = $this->packagingCode;
        if ($packagingCodeOption->isDefined()) {
            $packagingCode = $packagingCodeOption->get();
            $dataArray['packagingCode'] = $packagingCode;
        }
        $destinationLocationNumbersOption = $this->destinationLocationNumbers;
        if ($destinationLocationNumbersOption->isDefined()) {
            $destinationLocationNumbers = $destinationLocationNumbersOption->get();
            $values_7 = [];
            foreach ($destinationLocationNumbers as $value_7) {
                $values_7[] = $value_7;
            }
            $dataArray['destinationLocationNumbers'] = $values_7;
        }
        $publishedDeliveryTimeOption = $this->publishedDeliveryTime;
        if ($publishedDeliveryTimeOption->isDefined()) {
            $publishedDeliveryTime = $publishedDeliveryTimeOption->get();
            $dataArray['publishedDeliveryTime'] = $publishedDeliveryTime;
        }
        $countryCodesOption = $this->countryCodes;
        if ($countryCodesOption->isDefined()) {
            $countryCodes = $countryCodesOption->get();
            $values_8 = [];
            foreach ($countryCodes as $value_8) {
                $values_8[] = $value_8;
            }
            $dataArray['countryCodes'] = $values_8;
        }
        $stateOrProvinceCodesOption = $this->stateOrProvinceCodes;
        if ($stateOrProvinceCodesOption->isDefined()) {
            $stateOrProvinceCodes = $stateOrProvinceCodesOption->get();
            $values_9 = [];
            foreach ($stateOrProvinceCodes as $value_9) {
                $values_9[] = $value_9;
            }
            $dataArray['stateOrProvinceCodes'] = $values_9;
        }
        $ursaPrefixCodeOption = $this->ursaPrefixCode;
        if ($ursaPrefixCodeOption->isDefined()) {
            $ursaPrefixCode = $ursaPrefixCodeOption->get();
            $dataArray['ursaPrefixCode'] = $ursaPrefixCode;
        }
        $ursaSuffixCodeOption = $this->ursaSuffixCode;
        if ($ursaSuffixCodeOption->isDefined()) {
            $ursaSuffixCode = $ursaSuffixCodeOption->get();
            $dataArray['ursaSuffixCode'] = $ursaSuffixCode;
        }
        $destinationServiceAreasOption = $this->destinationServiceAreas;
        if ($destinationServiceAreasOption->isDefined()) {
            $destinationServiceAreas = $destinationServiceAreasOption->get();
            $values_10 = [];
            foreach ($destinationServiceAreas as $value_10) {
                $values_10[] = $value_10;
            }
            $dataArray['destinationServiceAreas'] = $values_10;
        }
        $originPostalCodesOption = $this->originPostalCodes;
        if ($originPostalCodesOption->isDefined()) {
            $originPostalCodes = $originPostalCodesOption->get();
            $values_11 = [];
            foreach ($originPostalCodes as $value_11) {
                $values_11[] = $value_11;
            }
            $dataArray['originPostalCodes'] = $values_11;
        }
        $customTransitTimeOption = $this->customTransitTime;
        if ($customTransitTimeOption->isDefined()) {
            $customTransitTime = $customTransitTimeOption->get();
            $dataArray['customTransitTime'] = $customTransitTime;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): OperationalDetailBuilder
    {
        return new OperationalDetailBuilder(
            $this->originLocationIds,
            $this->commitDays,
            $this->serviceCode,
            $this->airportId,
            $this->scac,
            $this->originServiceAreas,
            $this->deliveryDay,
            $this->originLocationNumbers,
            $this->destinationPostalCode,
            $this->commitDate,
            $this->astraDescription,
            $this->deliveryDate,
            $this->deliveryEligibilities,
            $this->ineligibleForMoneyBackGuarantee,
            $this->maximumTransitTime,
            $this->astraPlannedServiceLevel,
            $this->destinationLocationIds,
            $this->destinationLocationStateOrProvinceCodes,
            $this->transitTime,
            $this->packagingCode,
            $this->destinationLocationNumbers,
            $this->publishedDeliveryTime,
            $this->countryCodes,
            $this->stateOrProvinceCodes,
            $this->ursaPrefixCode,
            $this->ursaSuffixCode,
            $this->destinationServiceAreas,
            $this->originPostalCodes,
            $this->customTransitTime,
            $this->additionalProperties,
        );
    }
}
