<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

/**
 * Builds a {@see OperationalDetail}.
 */
final class OperationalDetailBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<list<string>>     $originLocationIds
     * @param Option<list<string>>     $commitDays
     * @param Option<string>           $serviceCode
     * @param Option<string>           $airportId
     * @param Option<string>           $scac
     * @param Option<list<string>>     $originServiceAreas
     * @param Option<string>           $deliveryDay
     * @param Option<list<int>>        $originLocationNumbers
     * @param Option<string>           $destinationPostalCode
     * @param Option<string>           $commitDate
     * @param Option<string>           $astraDescription
     * @param Option<string>           $deliveryDate
     * @param Option<list<string>>     $deliveryEligibilities
     * @param Option<bool>             $ineligibleForMoneyBackGuarantee
     * @param Option<string>           $maximumTransitTime
     * @param Option<string>           $astraPlannedServiceLevel
     * @param Option<list<string>>     $destinationLocationIds
     * @param Option<list<string>>     $destinationLocationStateOrProvinceCodes
     * @param Option<string>           $transitTime
     * @param Option<string>           $packagingCode
     * @param Option<list<int>>        $destinationLocationNumbers
     * @param Option<string>           $publishedDeliveryTime
     * @param Option<list<string>>     $countryCodes
     * @param Option<list<string>>     $stateOrProvinceCodes
     * @param Option<string>           $ursaPrefixCode
     * @param Option<string>           $ursaSuffixCode
     * @param Option<list<string>>     $destinationServiceAreas
     * @param Option<list<string>>     $originPostalCodes
     * @param Option<string>           $customTransitTime
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private Option $originLocationIds,
        private Option $commitDays,
        private Option $serviceCode,
        private Option $airportId,
        private Option $scac,
        private Option $originServiceAreas,
        private Option $deliveryDay,
        private Option $originLocationNumbers,
        private Option $destinationPostalCode,
        private Option $commitDate,
        private Option $astraDescription,
        private Option $deliveryDate,
        private Option $deliveryEligibilities,
        private Option $ineligibleForMoneyBackGuarantee,
        private Option $maximumTransitTime,
        private Option $astraPlannedServiceLevel,
        private Option $destinationLocationIds,
        private Option $destinationLocationStateOrProvinceCodes,
        private Option $transitTime,
        private Option $packagingCode,
        private Option $destinationLocationNumbers,
        private Option $publishedDeliveryTime,
        private Option $countryCodes,
        private Option $stateOrProvinceCodes,
        private Option $ursaPrefixCode,
        private Option $ursaSuffixCode,
        private Option $destinationServiceAreas,
        private Option $originPostalCodes,
        private Option $customTransitTime,
        private array $additionalProperties,
    ) {
    }

    /**
     * Indicate the location ID of the origin of shipment.
     *
     * Example: YBZA
     *
     * @param list<string> $originLocationIds
     */
    public function setOriginLocationIds(array $originLocationIds): self
    {
        $this->originLocationIds = Some::create($originLocationIds);

        return $this;
    }

    /**
     * Indicate the delivery commitment day.
     *
     * Example: MON
     *
     * @param list<string> $commitDays
     */
    public function setCommitDays(array $commitDays): self
    {
        $this->commitDays = Some::create($commitDays);

        return $this;
    }

    /**
     * Indicate the service code.
     *
     * Example: 06
     */
    public function setServiceCode(string $serviceCode): self
    {
        $this->serviceCode = Some::create($serviceCode);

        return $this;
    }

    /**
     * Specify the Airport Id.
     *
     * Example: MEM
     */
    public function setAirportId(string $airportId): self
    {
        $this->airportId = Some::create($airportId);

        return $this;
    }

    /**
     * Indicate the Standard Carrier Alpha Code (SCAC) is a privately controlled US code used to
     * identify vessel operating common carriers (VOCC). It is typically two to four letters long.
     */
    public function setScac(string $scac): self
    {
        $this->scac = Some::create($scac);

        return $this;
    }

    /**
     * Specify origin service area.
     *
     * Example: AM
     *
     * @param list<string> $originServiceAreas
     */
    public function setOriginServiceAreas(array $originServiceAreas): self
    {
        $this->originServiceAreas = Some::create($originServiceAreas);

        return $this;
    }

    /**
     * Specify the delivery commitment day.
     *
     * Example: SAT
     */
    public function setDeliveryDay(string $deliveryDay): self
    {
        $this->deliveryDay = Some::create($deliveryDay);

        return $this;
    }

    /**
     * Specify the origin location ID.
     *
     * Example: 6121
     *
     * @param list<int> $originLocationNumbers
     */
    public function setOriginLocationNumbers(array $originLocationNumbers): self
    {
        $this->originLocationNumbers = Some::create($originLocationNumbers);

        return $this;
    }

    /**
     * Indicate the destination postal code.
     *
     * Example: 38017
     */
    public function setDestinationPostalCode(string $destinationPostalCode): self
    {
        $this->destinationPostalCode = Some::create($destinationPostalCode);

        return $this;
    }

    /**
     * Indicate the shipment Commit Date.
     *
     * Example: 2019-07-22T08:30:00
     */
    public function setCommitDate(string $commitDate): self
    {
        $this->commitDate = Some::create($commitDate);

        return $this;
    }

    /**
     * Indicate the ASTRA description for the label.
     *
     * Example: XXXL1ST
     */
    public function setAstraDescription(string $astraDescription): self
    {
        $this->astraDescription = Some::create($astraDescription);

        return $this;
    }

    /**
     * Indicate the delivery date.
     *
     * Example: 2019-07-22T08:30:00
     */
    public function setDeliveryDate(string $deliveryDate): self
    {
        $this->deliveryDate = Some::create($deliveryDate);

        return $this;
    }

    /**
     * Indicate the delivery eligibilities.
     *
     * @param list<string> $deliveryEligibilities
     */
    public function setDeliveryEligibilities(array $deliveryEligibilities): self
    {
        $this->deliveryEligibilities = Some::create($deliveryEligibilities);

        return $this;
    }

    /**
     * indicate if ineligible For Money Back Guarantee.
     */
    public function setIneligibleForMoneyBackGuarantee(bool $ineligibleForMoneyBackGuarantee): self
    {
        $this->ineligibleForMoneyBackGuarantee = Some::create($ineligibleForMoneyBackGuarantee);

        return $this;
    }

    /**
     * Specify Maximum transit time.
     *
     * Example: THREE_DAYS
     */
    public function setMaximumTransitTime(string $maximumTransitTime): self
    {
        $this->maximumTransitTime = Some::create($maximumTransitTime);

        return $this;
    }

    /**
     * Indicate Astra Planned Service Level.
     *
     * Example: astraPlannedServicelevel
     */
    public function setAstraPlannedServiceLevel(string $astraPlannedServiceLevel): self
    {
        $this->astraPlannedServiceLevel = Some::create($astraPlannedServiceLevel);

        return $this;
    }

    /**
     * Indicate Destination Location Ids.
     *
     * Example: HKAA
     *
     * @param list<string> $destinationLocationIds
     */
    public function setDestinationLocationIds(array $destinationLocationIds): self
    {
        $this->destinationLocationIds = Some::create($destinationLocationIds);

        return $this;
    }

    /**
     * Indicate destination location State Or Province code.
     *
     * Example: TN
     *
     * <a onclick='loadDocReference("canadaprovincecodes")'>Click here to see State Or Province
     * Code</a>
     *
     * @param list<string> $destinationLocationStateOrProvinceCodes
     */
    public function setDestinationLocationStateOrProvinceCodes(array $destinationLocationStateOrProvinceCodes): self
    {
        $this->destinationLocationStateOrProvinceCodes = Some::create($destinationLocationStateOrProvinceCodes);

        return $this;
    }

    /**
     * Indicate the Transit Time in days.
     *
     * Example: THREE_DAYS
     */
    public function setTransitTime(string $transitTime): self
    {
        $this->transitTime = Some::create($transitTime);

        return $this;
    }

    /**
     * Indicate the Packaging Code.
     *
     * Example: M1M1M1
     */
    public function setPackagingCode(string $packagingCode): self
    {
        $this->packagingCode = Some::create($packagingCode);

        return $this;
    }

    /**
     * Indicate the Destination Location Numbers.
     *
     * Example: 386
     *
     * @param list<int> $destinationLocationNumbers
     */
    public function setDestinationLocationNumbers(array $destinationLocationNumbers): self
    {
        $this->destinationLocationNumbers = Some::create($destinationLocationNumbers);

        return $this;
    }

    /**
     * Indicate the Published Delivery Time.
     *
     * Example: THREE_DAYS
     */
    public function setPublishedDeliveryTime(string $publishedDeliveryTime): self
    {
        $this->publishedDeliveryTime = Some::create($publishedDeliveryTime);

        return $this;
    }

    /**
     * Indicate the Country Code.
     *
     * Example: [ US, IN]
     *
     * <a onclick='loadDocReference("countrycodes")'>Click here to see Country Codes</a>
     *
     * @param list<string> $countryCodes
     */
    public function setCountryCodes(array $countryCodes): self
    {
        $this->countryCodes = Some::create($countryCodes);

        return $this;
    }

    /**
     * Specifies state Or Province Code. State code is required for US, CA, PR and not required for
     * other countries. Conditional. Max length is 2.
     *
     * Example: TN
     *
     * @param list<string> $stateOrProvinceCodes
     */
    public function setStateOrProvinceCodes(array $stateOrProvinceCodes): self
    {
        $this->stateOrProvinceCodes = Some::create($stateOrProvinceCodes);

        return $this;
    }

    /**
     * This is FedEx URSA Prefix Code.
     *
     * Example: PrefixCode
     */
    public function setUrsaPrefixCode(string $ursaPrefixCode): self
    {
        $this->ursaPrefixCode = Some::create($ursaPrefixCode);

        return $this;
    }

    /**
     * This is URSA Suffix Code.
     *
     * Example: SuffixCode
     */
    public function setUrsaSuffixCode(string $ursaSuffixCode): self
    {
        $this->ursaSuffixCode = Some::create($ursaSuffixCode);

        return $this;
    }

    /**
     * This is Destination Service Areas.
     *
     * Example: A2
     *
     * @param list<string> $destinationServiceAreas
     */
    public function setDestinationServiceAreas(array $destinationServiceAreas): self
    {
        $this->destinationServiceAreas = Some::create($destinationServiceAreas);

        return $this;
    }

    /**
     * This is Origin Postal Codes.
     *
     * Example: M1M1M1
     *
     * @param list<string> $originPostalCodes
     */
    public function setOriginPostalCodes(array $originPostalCodes): self
    {
        $this->originPostalCodes = Some::create($originPostalCodes);

        return $this;
    }

    /**
     * This is Custom Transit Time in days.
     *
     * Example: THREE_DAYS
     */
    public function setCustomTransitTime(string $customTransitTime): self
    {
        $this->customTransitTime = Some::create($customTransitTime);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): OperationalDetail
    {
        return new OperationalDetail(
            $this->originLocationIds,
            $this->commitDays,
            $this->serviceCode,
            $this->airportId,
            $this->scac,
            $this->originServiceAreas,
            $this->deliveryDay,
            $this->originLocationNumbers,
            $this->destinationPostalCode,
            $this->commitDate,
            $this->astraDescription,
            $this->deliveryDate,
            $this->deliveryEligibilities,
            $this->ineligibleForMoneyBackGuarantee,
            $this->maximumTransitTime,
            $this->astraPlannedServiceLevel,
            $this->destinationLocationIds,
            $this->destinationLocationStateOrProvinceCodes,
            $this->transitTime,
            $this->packagingCode,
            $this->destinationLocationNumbers,
            $this->publishedDeliveryTime,
            $this->countryCodes,
            $this->stateOrProvinceCodes,
            $this->ursaPrefixCode,
            $this->ursaSuffixCode,
            $this->destinationServiceAreas,
            $this->originPostalCodes,
            $this->customTransitTime,
            $this->additionalProperties,
        );
    }
}
