<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

enum PackageCODDetailCodCollectionType: string
{
    case ANY = 'ANY';
    case CASH = 'CASH';
    case COMPANY_CHECK = 'COMPANY_CHECK';
    case GUARANTEED_FUNDS = 'GUARANTEED_FUNDS';
    case PERSONAL_CHECK = 'PERSONAL_CHECK';
}
