<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

/**
 * Builds a {@see Party2}.
 */
final class Party2Builder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<Address2>         $address
     * @param Option<Contact2>         $contact
     * @param Option<AccountNumber>    $accountNumber
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private Option $address,
        private Option $contact,
        private Option $accountNumber,
        private array $additionalProperties,
    ) {
    }

    /**
     * This is detailed information on physical location. May be used as an actual physical address
     * (place to which one could go), or as a container of address parts which should be handled as
     * a unit (such as a city-state-ZIP combination within the U.S.).
     */
    public function setAddress(Address2 $address): self
    {
        $this->address = Some::create($address);

        return $this;
    }

    /**
     * Indicate the contact details.
     */
    public function setContact(Contact2 $contact): self
    {
        $this->contact = Some::create($contact);

        return $this;
    }

    /**
     * This is the Account number details.
     *
     * <i>Note:<ul><li>If the paymentType is Sender, then the account number is optional in
     * shippingChargesPayment.</li></ul>
     */
    public function setAccountNumber(AccountNumber $accountNumber): self
    {
        $this->accountNumber = Some::create($accountNumber);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): Party2
    {
        return new Party2($this->address, $this->contact, $this->accountNumber, $this->additionalProperties);
    }
}
