<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Override;
use Prefabcortex\FedexRatesAndTransitTimesApi\Exception\MalformedDataException;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\None;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_array;
use function sprintf;

final readonly class Party2 implements SelfNormalizingModel
{
    /**
     * @param Option<Address2>         $address
     * @param Option<Contact2>         $contact
     * @param Option<AccountNumber>    $accountNumber
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private Option $address,
        private Option $contact,
        private Option $accountNumber,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): Party2Builder
    {
        return new Party2Builder(None::create(), None::create(), None::create(), []);
    }

    /**
     * This is detailed information on physical location. May be used as an actual physical address
     * (place to which one could go), or as a container of address parts which should be handled as
     * a unit (such as a city-state-ZIP combination within the U.S.).
     *
     * @return Option<Address2>
     */
    public function getAddress(): Option
    {
        return $this->address;
    }

    /**
     * Indicate the contact details.
     *
     * @return Option<Contact2>
     */
    public function getContact(): Option
    {
        return $this->contact;
    }

    /**
     * This is the Account number details.
     *
     * <i>Note:<ul><li>If the paymentType is Sender, then the account number is optional in
     * shippingChargesPayment.</li></ul>
     *
     * @return Option<AccountNumber>
     */
    public function getAccountNumber(): Option
    {
        return $this->accountNumber;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $address = None::create();
        $contact = None::create();
        $accountNumber = None::create();
        if (array_key_exists('address', $data) && $data['address'] !== null) {
            $addressRaw = $data['address'];
            if (!is_array($addressRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "address" must be object, got %s.', get_debug_type($addressRaw)),
                );
            }
            /** @var array<string, mixed> $addressRawTyped */
            $addressRawTyped = $addressRaw;
            $address = Some::create(Address2::fromArray($addressRawTyped));
        }
        if (array_key_exists('contact', $data) && $data['contact'] !== null) {
            $contactRaw = $data['contact'];
            if (!is_array($contactRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "contact" must be object, got %s.', get_debug_type($contactRaw)),
                );
            }
            /** @var array<string, mixed> $contactRawTyped */
            $contactRawTyped = $contactRaw;
            $contact = Some::create(Contact2::fromArray($contactRawTyped));
        }
        if (array_key_exists('accountNumber', $data) && $data['accountNumber'] !== null) {
            $accountNumberRaw = $data['accountNumber'];
            if (!is_array($accountNumberRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "accountNumber" must be object, got %s.', get_debug_type($accountNumberRaw)),
                );
            }
            /** @var array<string, mixed> $accountNumberRawTyped */
            $accountNumberRawTyped = $accountNumberRaw;
            $accountNumber = Some::create(AccountNumber::fromArray($accountNumberRawTyped));
        }
        $additionalProperties = array_diff_key($data, ['address' => true, 'contact' => true, 'accountNumber' => true]);

        return new self($address, $contact, $accountNumber, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $addressOption = $this->address;
        if ($addressOption->isDefined()) {
            $address = $addressOption->get();
            $dataArray['address'] = $normalizationTarget->model($address);
        }
        $contactOption = $this->contact;
        if ($contactOption->isDefined()) {
            $contact = $contactOption->get();
            $dataArray['contact'] = $normalizationTarget->model($contact);
        }
        $accountNumberOption = $this->accountNumber;
        if ($accountNumberOption->isDefined()) {
            $accountNumber = $accountNumberOption->get();
            $dataArray['accountNumber'] = $normalizationTarget->model($accountNumber);
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): Party2Builder
    {
        return new Party2Builder($this->address, $this->contact, $this->accountNumber, $this->additionalProperties);
    }
}
