<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Override;
use Prefabcortex\FedexRatesAndTransitTimesApi\Exception\MalformedDataException;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\None;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_array;
use function sprintf;

final readonly class Payor implements SelfNormalizingModel
{
    /**
     * @param Option<PayorResponsibleParty> $responsibleParty
     * @param array<int|string, mixed>      $additionalProperties
     */
    public function __construct(private Option $responsibleParty, private array $additionalProperties)
    {
    }

    public static function builder(): PayorBuilder
    {
        return new PayorBuilder(None::create(), []);
    }

    /**
     * These are payer details such as address, account and contacts.
     *
     * @return Option<PayorResponsibleParty>
     */
    public function getResponsibleParty(): Option
    {
        return $this->responsibleParty;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $responsibleParty = None::create();
        if (array_key_exists('responsibleParty', $data) && $data['responsibleParty'] !== null) {
            $responsiblePartyRaw = $data['responsibleParty'];
            if (!is_array($responsiblePartyRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "responsibleParty" must be object, got %s.',
                        get_debug_type($responsiblePartyRaw),
                    ),
                );
            }
            /** @var non-empty-array<string, mixed> $responsiblePartyRawTyped */
            $responsiblePartyRawTyped = $responsiblePartyRaw;
            $responsibleParty = Some::create(PayorResponsibleParty::fromArray($responsiblePartyRawTyped));
        }
        $additionalProperties = array_diff_key($data, ['responsibleParty' => true]);

        return new self($responsibleParty, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $responsiblePartyOption = $this->responsibleParty;
        if ($responsiblePartyOption->isDefined()) {
            $responsibleParty = $responsiblePartyOption->get();
            $dataArray['responsibleParty'] = $normalizationTarget->model($responsibleParty);
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): PayorBuilder
    {
        return new PayorBuilder($this->responsibleParty, $this->additionalProperties);
    }
}
