<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use DateTimeInterface;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

/**
 * Builds a {@see PickupDetail}.
 */
final class PickupDetailBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<DateTimeInterface>                                $readyDateTime
     * @param Option<DateTimeInterface>                                $latestPickupDateTime
     * @param Option<string>                                           $courierInstructions
     * @param Option<PickupRequestType|UnknownEnumValue<string>>       $requestType
     * @param Option<PickupRequestSourceType|UnknownEnumValue<string>> $requestSource
     * @param array<int|string, mixed>                                 $additionalProperties
     */
    public function __construct(
        private Option $readyDateTime,
        private Option $latestPickupDateTime,
        private Option $courierInstructions,
        private Option $requestType,
        private Option $requestSource,
        private array $additionalProperties,
    ) {
    }

    /**
     * Pickup ready date in YYYY-MM-DD format. Required when requestType is 'FUTURE_DAY'.
     */
    public function setReadyDateTime(DateTimeInterface $readyDateTime): self
    {
        $this->readyDateTime = Some::create($readyDateTime);

        return $this;
    }

    /**
     * Latest pickup date in YYYY-MM-DD format. Required when requestType is 'FUTURE_DAY'.
     */
    public function setLatestPickupDateTime(DateTimeInterface $latestPickupDateTime): self
    {
        $this->latestPickupDateTime = Some::create($latestPickupDateTime);

        return $this;
    }

    /**
     * Special instructions for the courier.
     */
    public function setCourierInstructions(string $courierInstructions): self
    {
        $this->courierInstructions = Some::create($courierInstructions);

        return $this;
    }

    /**
     * Type of pickup request.
     */
    public function setRequestType(PickupRequestType $requestType): self
    {
        $this->requestType = Some::create($requestType);

        return $this;
    }

    /**
     * Source of the pickup request.
     */
    public function setRequestSource(PickupRequestSourceType $requestSource): self
    {
        $this->requestSource = Some::create($requestSource);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): PickupDetail
    {
        return new PickupDetail(
            $this->readyDateTime,
            $this->latestPickupDateTime,
            $this->courierInstructions,
            $this->requestType,
            $this->requestSource,
            $this->additionalProperties,
        );
    }
}
