<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

/**
 * Builds a {@see RatedShipmentDetail}.
 */
final class RatedShipmentDetailBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<RatedShipmentDetailRateType|UnknownEnumValue<string>>           $rateType
     * @param Option<Money>                                                          $totalNetTransportationAndPickupCharge
     * @param Option<Money>                                                          $totalNetFedExTransportationAndPickupCharge
     * @param Option<RatedShipmentDetailPickupRateDetail>                            $pickupRateDetail
     * @param Option<RatedShipmentDetailRatedWeightMethod|UnknownEnumValue<string>>  $ratedWeightMethod
     * @param Option<float>                                                          $totalDutiesTaxesAndFees
     * @param Option<float>                                                          $totalDiscounts
     * @param Option<float>                                                          $totalDutiesAndTaxes
     * @param Option<VariableHandlingCharges>                                        $variableHandlingCharges
     * @param Option<list<EdtCharge>>                                                $edtCharges
     * @param Option<float>                                                          $totalAncillaryFeesAndTaxes
     * @param Option<list<RatedPackageDetail>>                                       $ratedPackages
     * @param Option<float>                                                          $totalNetFedExCharge
     * @param Option<string>                                                         $quoteNumber
     * @param Option<list<ShipmentLegRateDetail1>>                                   $shipmentLegRateDetails
     * @param Option<RatedShipmentDetailFreightChargeBasis|UnknownEnumValue<string>> $freightChargeBasis
     * @param Option<VariableHandlingCharges>                                        $totalVariableHandlingCharges
     * @param Option<float>                                                          $totalVatCharge
     * @param Option<list<AncillaryFeesAndTaxes>>                                    $ancillaryFeesAndTaxes
     * @param Option<list<EdtCharge>>                                                $preferredEdtCharges
     * @param Option<float>                                                          $totalNetCharge
     * @param Option<float>                                                          $totalBaseCharge
     * @param Option<float>                                                          $totalNetChargeWithDutiesAndTaxes
     * @param Option<ShipmentRateDetail>                                             $shipmentRateDetail
     * @param array<int|string, mixed>                                               $additionalProperties
     */
    public function __construct(
        private Option $rateType,
        private Option $totalNetTransportationAndPickupCharge,
        private Option $totalNetFedExTransportationAndPickupCharge,
        private Option $pickupRateDetail,
        private Option $ratedWeightMethod,
        private Option $totalDutiesTaxesAndFees,
        private Option $totalDiscounts,
        private Option $totalDutiesAndTaxes,
        private Option $variableHandlingCharges,
        private Option $edtCharges,
        private Option $totalAncillaryFeesAndTaxes,
        private Option $ratedPackages,
        private Option $totalNetFedExCharge,
        private Option $quoteNumber,
        private Option $shipmentLegRateDetails,
        private Option $freightChargeBasis,
        private Option $totalVariableHandlingCharges,
        private Option $totalVatCharge,
        private Option $ancillaryFeesAndTaxes,
        private Option $preferredEdtCharges,
        private Option $totalNetCharge,
        private Option $totalBaseCharge,
        private Option $totalNetChargeWithDutiesAndTaxes,
        private Option $shipmentRateDetail,
        private array $additionalProperties,
    ) {
    }

    /**
     * Type used for this specific set of rate data.
     *
     * Example: ACCOUNT
     */
    public function setRateType(RatedShipmentDetailRateType $rateType): self
    {
        $this->rateType = Some::create($rateType);

        return $this;
    }

    /**
     * Sum of totalNetCharge from pickupRateDetail and shipmentRateDetail. This charge will be
     * populated regardless of pickup.
     */
    public function setTotalNetTransportationAndPickupCharge(Money $totalNetTransportationAndPickupCharge): self
    {
        $this->totalNetTransportationAndPickupCharge = Some::create($totalNetTransportationAndPickupCharge);

        return $this;
    }

    /**
     * Sum of totalNetFedExCharge from pickupRateDetail and shipmentRateDetail. This charge will be
     * populated regardless of a pickup.
     */
    public function setTotalNetFedExTransportationAndPickupCharge(
        Money $totalNetFedExTransportationAndPickupCharge,
    ): self {
        $this->totalNetFedExTransportationAndPickupCharge = Some::create($totalNetFedExTransportationAndPickupCharge);

        return $this;
    }

    /**
     * Charges associated with a scheduled shipment pickup.
     */
    public function setPickupRateDetail(RatedShipmentDetailPickupRateDetail $pickupRateDetail): self
    {
        $this->pickupRateDetail = Some::create($pickupRateDetail);

        return $this;
    }

    /**
     * Indicates which weight was used for the rate.
     *
     * Example: 'ACTUAL'
     */
    public function setRatedWeightMethod(RatedShipmentDetailRatedWeightMethod $ratedWeightMethod): self
    {
        $this->ratedWeightMethod = Some::create($ratedWeightMethod);

        return $this;
    }

    /**
     * The total amount of the duties and taxes plus the total ancillary fees and taxes.
     *
     * Example: 445.54
     */
    public function setTotalDutiesTaxesAndFees(float $totalDutiesTaxesAndFees): self
    {
        $this->totalDutiesTaxesAndFees = Some::create($totalDutiesTaxesAndFees);

        return $this;
    }

    /**
     * This is the total discount.
     *
     * Example: 445.54
     *
     * <a href='/api/en-us/reference-guide.html#discounts' target='_blank'>Click here to see FedEx
     * Discounts</a>
     */
    public function setTotalDiscounts(float $totalDiscounts): self
    {
        $this->totalDiscounts = Some::create($totalDiscounts);

        return $this;
    }

    /**
     * The sum of shipment/package Duties and taxes.
     *
     * Example: 445.54
     */
    public function setTotalDutiesAndTaxes(float $totalDutiesAndTaxes): self
    {
        $this->totalDutiesAndTaxes = Some::create($totalDutiesAndTaxes);

        return $this;
    }

    /**
     * The variable handling charge amount calculated based on the requested variable handling
     * charge detail.
     */
    public function setVariableHandlingCharges(VariableHandlingCharges $variableHandlingCharges): self
    {
        $this->variableHandlingCharges = Some::create($variableHandlingCharges);

        return $this;
    }

    /**
     * These are the estimation and duty charges.
     *
     * @param list<EdtCharge> $edtCharges
     */
    public function setEdtCharges(array $edtCharges): self
    {
        $this->edtCharges = Some::create($edtCharges);

        return $this;
    }

    /**
     * Indicates the shipment-level fees and taxes that are not based on transportation charges or
     * commodity-level estimated duties and taxes.
     */
    public function setTotalAncillaryFeesAndTaxes(float $totalAncillaryFeesAndTaxes): self
    {
        $this->totalAncillaryFeesAndTaxes = Some::create($totalAncillaryFeesAndTaxes);

        return $this;
    }

    /**
     * These are the package-level data for this rate type.
     *
     * @param list<RatedPackageDetail> $ratedPackages
     */
    public function setRatedPackages(array $ratedPackages): self
    {
        $this->ratedPackages = Some::create($ratedPackages);

        return $this;
    }

    /**
     * This shipment's totalNetFedExChargeList, which is totalNetFreight plus totalSurcharges (not
     * including totalTaxes).
     */
    public function setTotalNetFedExCharge(float $totalNetFedExCharge): self
    {
        $this->totalNetFedExCharge = Some::create($totalNetFedExCharge);

        return $this;
    }

    /**
     * Indicates the unique identifier for a specific rate quotation.
     *
     * Example: XX1123XX
     */
    public function setQuoteNumber(string $quoteNumber): self
    {
        $this->quoteNumber = Some::create($quoteNumber);

        return $this;
    }

    /**
     * This is data for a single leg of a shipment's total/summary rates, as calculated per a
     * specific rate type.
     *
     * @param list<ShipmentLegRateDetail1> $shipmentLegRateDetails
     */
    public function setShipmentLegRateDetails(array $shipmentLegRateDetails): self
    {
        $this->shipmentLegRateDetails = Some::create($shipmentLegRateDetails);

        return $this;
    }

    /**
     * This identifies the manner in which the chargeRate was applied, for Freight.
     *
     * Valid values are: <ul><li>CWT - Charge rate applies per weight.</li><li>FLAT - Charge rate is
     * a flat-rate amount.</li><li>MINIMUM</li></ul>
     */
    public function setFreightChargeBasis(RatedShipmentDetailFreightChargeBasis $freightChargeBasis): self
    {
        $this->freightChargeBasis = Some::create($freightChargeBasis);

        return $this;
    }

    /**
     * The variable handling charge amount calculated based on the requested variable handling
     * charge detail.
     */
    public function setTotalVariableHandlingCharges(VariableHandlingCharges $totalVariableHandlingCharges): self
    {
        $this->totalVariableHandlingCharges = Some::create($totalVariableHandlingCharges);

        return $this;
    }

    /**
     * This is total value added tax charges (VAT).
     */
    public function setTotalVatCharge(float $totalVatCharge): self
    {
        $this->totalVatCharge = Some::create($totalVatCharge);

        return $this;
    }

    /**
     * This is the total amount of the shipment-level fees and taxes that are not based on
     * transportation charges of commodity-level estimated duties and taxes.
     *
     * @param list<AncillaryFeesAndTaxes> $ancillaryFeesAndTaxes
     */
    public function setAncillaryFeesAndTaxes(array $ancillaryFeesAndTaxes): self
    {
        $this->ancillaryFeesAndTaxes = Some::create($ancillaryFeesAndTaxes);

        return $this;
    }

    /**
     * Specifies the Edt charges.
     *
     * @param list<EdtCharge> $preferredEdtCharges
     */
    public function setPreferredEdtCharges(array $preferredEdtCharges): self
    {
        $this->preferredEdtCharges = Some::create($preferredEdtCharges);

        return $this;
    }

    /**
     * This is net charges for the shipment.
     */
    public function setTotalNetCharge(float $totalNetCharge): self
    {
        $this->totalNetCharge = Some::create($totalNetCharge);

        return $this;
    }

    /**
     * This is total base charges for the shipment.
     */
    public function setTotalBaseCharge(float $totalBaseCharge): self
    {
        $this->totalBaseCharge = Some::create($totalBaseCharge);

        return $this;
    }

    /**
     * This is total net Charges with Duties And Taxes for the shipment.
     */
    public function setTotalNetChargeWithDutiesAndTaxes(float $totalNetChargeWithDutiesAndTaxes): self
    {
        $this->totalNetChargeWithDutiesAndTaxes = Some::create($totalNetChargeWithDutiesAndTaxes);

        return $this;
    }

    /**
     * This is shipment level rate data.
     */
    public function setShipmentRateDetail(ShipmentRateDetail $shipmentRateDetail): self
    {
        $this->shipmentRateDetail = Some::create($shipmentRateDetail);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): RatedShipmentDetail
    {
        return new RatedShipmentDetail(
            $this->rateType,
            $this->totalNetTransportationAndPickupCharge,
            $this->totalNetFedExTransportationAndPickupCharge,
            $this->pickupRateDetail,
            $this->ratedWeightMethod,
            $this->totalDutiesTaxesAndFees,
            $this->totalDiscounts,
            $this->totalDutiesAndTaxes,
            $this->variableHandlingCharges,
            $this->edtCharges,
            $this->totalAncillaryFeesAndTaxes,
            $this->ratedPackages,
            $this->totalNetFedExCharge,
            $this->quoteNumber,
            $this->shipmentLegRateDetails,
            $this->freightChargeBasis,
            $this->totalVariableHandlingCharges,
            $this->totalVatCharge,
            $this->ancillaryFeesAndTaxes,
            $this->preferredEdtCharges,
            $this->totalNetCharge,
            $this->totalBaseCharge,
            $this->totalNetChargeWithDutiesAndTaxes,
            $this->shipmentRateDetail,
            $this->additionalProperties,
        );
    }
}
