<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

/**
 * Builds a {@see RateParty}.
 */
final class RatePartyBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(private RateAddress $address, private array $additionalProperties)
    {
    }

    /**
     * Descriptive data for a physical location. May be used as an actual physical address (place to
     * which one could go), or as a container of address parts which should be handled as a unit
     * (such as a city-state-ZIP combination within the US). Country code is required. Postal code
     * is required for postal aware countries.
     */
    public function setAddress(RateAddress $address): self
    {
        $this->address = $address;

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): RateParty
    {
        return new RateParty($this->address, $this->additionalProperties);
    }
}
