<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

enum RatedShipmentDetailRatedWeightMethod: string
{
    case ACTUAL = 'ACTUAL';
    case AVERAGE_PACKAGE_WEIGHT_MINIMUM = 'AVERAGE_PACKAGE_WEIGHT_MINIMUM';
    case DEFAULT_WEIGHT_APPLIED = 'DEFAULT_WEIGHT_APPLIED';
    case BALLOON = 'BALLOON';
    case DIM = 'DIM';
    case FREIGHT_MINIMUM = 'FREIGHT_MINIMUM';
    case MIXED = 'MIXED';
    case OVERSIZE = 'OVERSIZE';
    case OVERSIZE_1 = 'OVERSIZE_1';
    case OVERSIZE_2 = 'OVERSIZE_2';
    case OVERSIZE_3 = 'OVERSIZE_3';
    case PACKAGING_MINIMUM = 'PACKAGING_MINIMUM';
    case WEIGHT_BREAK = 'WEIGHT_BREAK';
}
