<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Override;
use Prefabcortex\FedexRatesAndTransitTimesApi\Exception\MalformedDataException;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\None;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_float;
use function is_int;
use function is_string;
use function sprintf;

final readonly class RateDiscount implements SelfNormalizingModel
{
    /**
     * @param Option<float>            $amount
     * @param Option<string>           $name
     * @param Option<string>           $description
     * @param Option<string>           $type
     * @param Option<float>            $percent
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private Option $amount,
        private Option $name,
        private Option $description,
        private Option $type,
        private Option $percent,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): RateDiscountBuilder
    {
        return new RateDiscountBuilder(
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            [],
        );
    }

    /**
     * Indicates the details of the charges are to be added to the COD collect amount.
     *
     * Example: 95
     *
     * @return Option<float>
     */
    public function getAmount(): Option
    {
        return $this->amount;
    }

    /**
     * Specifies the name of all of the discounts that apply to the package.
     *
     * <a onclick='loadDocReference("discounts")'>Click here to see Discounts</a>
     *
     * @return Option<string>
     */
    public function getName(): Option
    {
        return $this->name;
    }

    /**
     * Specifies the discounts on this package.
     *
     * @return Option<string>
     */
    public function getDescription(): Option
    {
        return $this->description;
    }

    /**
     * Specifies the type of discount.
     *
     * @return Option<string>
     */
    public function getType(): Option
    {
        return $this->type;
    }

    /**
     * Specifies the percentage of discount.
     *
     * @return Option<float>
     */
    public function getPercent(): Option
    {
        return $this->percent;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $amount = None::create();
        $name = None::create();
        $description = None::create();
        $type = None::create();
        $percent = None::create();
        if (array_key_exists('amount', $data) && is_int($data['amount'])) {
            $data['amount'] = (float) $data['amount'];
        }
        if (array_key_exists('percent', $data) && is_int($data['percent'])) {
            $data['percent'] = (float) $data['percent'];
        }
        if (array_key_exists('amount', $data) && $data['amount'] !== null) {
            $amountRaw = $data['amount'];
            if (!(is_float($amountRaw) || is_int($amountRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "amount" must be number, got %s.', get_debug_type($amountRaw)),
                );
            }
            $amount = Some::create((float) $amountRaw);
        }
        if (array_key_exists('name', $data) && $data['name'] !== null) {
            $nameRaw = $data['name'];
            if (!is_string($nameRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "name" must be string, got %s.', get_debug_type($nameRaw)),
                );
            }
            $name = Some::create($nameRaw);
        }
        if (array_key_exists('description', $data) && $data['description'] !== null) {
            $descriptionRaw = $data['description'];
            if (!is_string($descriptionRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "description" must be string, got %s.', get_debug_type($descriptionRaw)),
                );
            }
            $description = Some::create($descriptionRaw);
        }
        if (array_key_exists('type', $data) && $data['type'] !== null) {
            $typeRaw = $data['type'];
            if (!is_string($typeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "type" must be string, got %s.', get_debug_type($typeRaw)),
                );
            }
            $type = Some::create($typeRaw);
        }
        if (array_key_exists('percent', $data) && $data['percent'] !== null) {
            $percentRaw = $data['percent'];
            if (!(is_float($percentRaw) || is_int($percentRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "percent" must be number, got %s.', get_debug_type($percentRaw)),
                );
            }
            $percent = Some::create((float) $percentRaw);
        }
        $additionalProperties = array_diff_key(
            $data,
            ['amount' => true, 'name' => true, 'description' => true, 'type' => true, 'percent' => true],
        );

        return new self($amount, $name, $description, $type, $percent, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $amountOption = $this->amount;
        if ($amountOption->isDefined()) {
            $amount = $amountOption->get();
            $dataArray['amount'] = $amount;
        }
        $nameOption = $this->name;
        if ($nameOption->isDefined()) {
            $name = $nameOption->get();
            $dataArray['name'] = $name;
        }
        $descriptionOption = $this->description;
        if ($descriptionOption->isDefined()) {
            $description = $descriptionOption->get();
            $dataArray['description'] = $description;
        }
        $typeOption = $this->type;
        if ($typeOption->isDefined()) {
            $type = $typeOption->get();
            $dataArray['type'] = $type;
        }
        $percentOption = $this->percent;
        if ($percentOption->isDefined()) {
            $percent = $percentOption->get();
            $dataArray['percent'] = $percent;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): RateDiscountBuilder
    {
        return new RateDiscountBuilder(
            $this->amount,
            $this->name,
            $this->description,
            $this->type,
            $this->percent,
            $this->additionalProperties,
        );
    }
}
