<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

/**
 * Builds a {@see RateAddress}.
 */
final class RateAddressBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>           $city
     * @param Option<string>           $stateOrProvinceCode
     * @param Option<bool>             $residential
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private string $postalCode,
        private string $countryCode,
        private Option $city,
        private Option $stateOrProvinceCode,
        private Option $residential,
        private array $additionalProperties,
    ) {
    }

    public function setPostalCode(string $postalCode): self
    {
        $this->postalCode = $postalCode;

        return $this;
    }

    public function setCountryCode(string $countryCode): self
    {
        $this->countryCode = $countryCode;

        return $this;
    }

    /**
     * This is a placeholder for City Name.
     *
     * Example: Beverly Hills
     */
    public function setCity(string $city): self
    {
        $this->city = Some::create($city);

        return $this;
    }

    /**
     * This is a placeholder for State or Province code. State code is required for US, CA, PR and
     * not required for other countries. Conditional. Max length is 2 .
     *
     * Example: CA
     *
     * <a onclick='loadDocReference("canadaprovincecodes")'>Click here to see State Or Province
     * Code</a>
     */
    public function setStateOrProvinceCode(string $stateOrProvinceCode): self
    {
        $this->stateOrProvinceCode = Some::create($stateOrProvinceCode);

        return $this;
    }

    /**
     * Indicate whether this address is residential (as opposed to commercial).
     */
    public function setResidential(bool $residential): self
    {
        $this->residential = Some::create($residential);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): RateAddress
    {
        return new RateAddress(
            $this->postalCode,
            $this->countryCode,
            $this->city,
            $this->stateOrProvinceCode,
            $this->residential,
            $this->additionalProperties,
        );
    }
}
