<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

/**
 * Builds a {@see RateDiscount1}.
 */
final class RateDiscount1Builder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<float>            $amount
     * @param Option<string>           $name
     * @param Option<string>           $description
     * @param Option<string>           $type
     * @param Option<float>            $percent
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private Option $amount,
        private Option $name,
        private Option $description,
        private Option $type,
        private Option $percent,
        private array $additionalProperties,
    ) {
    }

    /**
     * Indicates the amount for the rate discount.
     *
     * Example: 87.5
     */
    public function setAmount(float $amount): self
    {
        $this->amount = Some::create($amount);

        return $this;
    }

    /**
     * Indicate the name of the discount.<a
     * href="/developer-portal/en-us/reference-guide.html#discounts" target="_blank">Click here to
     * see Discounts</a>.
     *
     * Example: name
     */
    public function setName(string $name): self
    {
        $this->name = Some::create($name);

        return $this;
    }

    /**
     * Indicates the description for the rate discount.
     *
     * Example: Description
     */
    public function setDescription(string $description): self
    {
        $this->description = Some::create($description);

        return $this;
    }

    /**
     * Indicates the type.
     *
     * Example: type
     */
    public function setType(string $type): self
    {
        $this->type = Some::create($type);

        return $this;
    }

    /**
     * Indicates the percentage of the rate discount.
     *
     * Example: 10.5
     */
    public function setPercent(float $percent): self
    {
        $this->percent = Some::create($percent);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): RateDiscount1
    {
        return new RateDiscount1(
            $this->amount,
            $this->name,
            $this->description,
            $this->type,
            $this->percent,
            $this->additionalProperties,
        );
    }
}
