<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

/**
 * Builds a {@see RequestedShipmentSmartPostInfoDetail}.
 */
final class RequestedShipmentSmartPostInfoDetailBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<SmartPostInfoDetailAncillaryEndorsement|UnknownEnumValue<string>> $ancillaryEndorsement
     * @param Option<string>                                                           $hubId
     * @param Option<SmartPostInfoDetailIndicia|UnknownEnumValue<string>>              $indicia
     * @param Option<SmartPostInfoDetailSpecialServices|UnknownEnumValue<string>>      $specialServices
     * @param array<int|string, mixed>                                                 $additionalProperties
     */
    public function __construct(
        private Option $ancillaryEndorsement,
        private Option $hubId,
        private Option $indicia,
        private Option $specialServices,
        private array $additionalProperties,
    ) {
    }

    /**
     * Indicate the type of ancillary endorsement. Is required for Presorted Standard but not for
     * returns or parcel select. Note not all are usable for all ancillary endorsements.
     *
     * For more information, refer to the <a href =
     * 'https://www.fedex.com/en-us/shipping/fedex-smartpost/rates-zones.html' target='_blank'>FedEx
     * SmartPost®</a>.
     */
    public function setAncillaryEndorsement(SmartPostInfoDetailAncillaryEndorsement $ancillaryEndorsement): self
    {
        $this->ancillaryEndorsement = Some::create($ancillaryEndorsement);

        return $this;
    }

    /**
     * Specify the four-digit numeric Hub ID value used during rate quote for smartport shipments.
     *
     * <a onclick='loadDocReference("smartposthubids")'>Click here to see Hub Ids</a>
     */
    public function setHubId(string $hubId): self
    {
        $this->hubId = Some::create($hubId);

        return $this;
    }

    /**
     * Specify the indicia type.
     *
     * Available options include:<ul><li>MEDIA_MAIL</li><li>PARCEL_SELECT (1 LB through 70
     * LB)</li><li>PRESORTED_BOUND_PRINTED_MATTER</li><li>PRESORTED_STANDARD (less than 1
     * LB)</li><li>PARCEL_RETURN</li></ul>
     */
    public function setIndicia(SmartPostInfoDetailIndicia $indicia): self
    {
        $this->indicia = Some::create($indicia);

        return $this;
    }

    /**
     * Specify the special handling associated with Smartpost Shipment.
     *
     * <a onclick='loadDocReference("shipmentlevelspecialservicetypes")'>Click here to see Shipment
     * Level Special Service Types</a>
     */
    public function setSpecialServices(SmartPostInfoDetailSpecialServices $specialServices): self
    {
        $this->specialServices = Some::create($specialServices);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): RequestedShipmentSmartPostInfoDetail
    {
        return new RequestedShipmentSmartPostInfoDetail(
            $this->ancillaryEndorsement,
            $this->hubId,
            $this->indicia,
            $this->specialServices,
            $this->additionalProperties,
        );
    }
}
