<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Override;
use Prefabcortex\FedexRatesAndTransitTimesApi\Exception\MalformedDataException;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\None;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

use function array_diff_key;
use function array_is_list;
use function array_key_exists;
use function array_map;
use function get_debug_type;
use function is_array;
use function is_string;
use function sprintf;

final readonly class RequestedShipmentCustomsClearanceDetail implements SelfNormalizingModel
{
    /**
     * @param list<Commodity>                                                       $commodities
     * @param Option<list<BrokerDetail>>                                            $brokers
     * @param Option<CommercialInvoice>                                             $commercialInvoice
     * @param Option<CustomsClearanceDetailFreightOnValue|UnknownEnumValue<string>> $freightOnValue
     * @param Option<Payment>                                                       $dutiesPayment
     * @param array<int|string, mixed>                                              $additionalProperties
     */
    public function __construct(
        private array $commodities,
        private Option $brokers,
        private Option $commercialInvoice,
        private Option $freightOnValue,
        private Option $dutiesPayment,
        private array $additionalProperties,
    ) {
    }

    /** @param list<Commodity> $commodities */
    public static function builder(array $commodities): RequestedShipmentCustomsClearanceDetailBuilder
    {
        return new RequestedShipmentCustomsClearanceDetailBuilder(
            $commodities,
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            [],
        );
    }

    /**
     * Conditional.
     *
     * Required if BROKER_SELECT_OPTION is specified as a shipment special service type. A country
     * code must be specified in addition to one of the following address items: postal code, city,
     * or location id.
     *
     * @return Option<list<BrokerDetail>>
     */
    public function getBrokers(): Option
    {
        return $this->brokers;
    }

    /**
     * The Commercial Invoice element is required for electronic upload of CI data. It will serve to
     * create/transmit an electronic Commercial Invoice through the FedEx system.
     *
     * Customers are responsible for printing their own Commercial Invoice.
     *
     * If you would like FedEx to generate a Commercial Invoice and transmit it to Customs for
     * clearance purposes, you need to specify that in the 'ETDDetail/RequesteDocumentCopies'
     * element.
     *
     * Support consists of a Maximum of 99 commodity line items.
     *
     * @return Option<CommercialInvoice>
     */
    public function getCommercialInvoice(): Option
    {
        return $this->commercialInvoice;
    }

    /**
     * Indicates Freight on value for customs.
     *
     * @return Option<CustomsClearanceDetailFreightOnValue|UnknownEnumValue<string>>
     */
    public function getFreightOnValue(): Option
    {
        return $this->freightOnValue;
    }

    /**
     * These are details about shipment payment. Value payor is optional when paymentType provided
     * as SENDER.
     *
     * @return Option<Payment>
     */
    public function getDutiesPayment(): Option
    {
        return $this->dutiesPayment;
    }

    /**
     * Indicates the details about the dutiable packages. Maximum upto 999 commodities per shipment.
     *
     * @return list<Commodity>
     */
    public function getCommodities(): array
    {
        return $this->commodities;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $brokers = None::create();
        $commercialInvoice = None::create();
        $freightOnValue = None::create();
        $dutiesPayment = None::create();
        $commodities = null;
        if (array_key_exists('brokers', $data) && $data['brokers'] !== null) {
            $brokersRaw = $data['brokers'];
            if (!(is_array($brokersRaw) && array_is_list($brokersRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "brokers" must be list, got %s.', get_debug_type($brokersRaw)),
                );
            }
            $brokers = Some::create(array_map(static function (mixed $value): BrokerDetail {
                if (!is_array($value)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be object, got %s.', get_debug_type($value)),
                    );
                }
                /** @var non-empty-array<string, mixed> $valueTyped */
                $valueTyped = $value;

                return BrokerDetail::fromArray($valueTyped);
            }, $brokersRaw));
        }
        if (array_key_exists('commercialInvoice', $data) && $data['commercialInvoice'] !== null) {
            $commercialInvoiceRaw = $data['commercialInvoice'];
            if (!is_array($commercialInvoiceRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "commercialInvoice" must be object, got %s.',
                        get_debug_type($commercialInvoiceRaw),
                    ),
                );
            }
            /** @var array<string, mixed> $commercialInvoiceRawTyped */
            $commercialInvoiceRawTyped = $commercialInvoiceRaw;
            $commercialInvoice = Some::create(CommercialInvoice::fromArray($commercialInvoiceRawTyped));
        }
        if (array_key_exists('freightOnValue', $data) && $data['freightOnValue'] !== null) {
            $freightOnValueRaw = $data['freightOnValue'];
            if (!is_string($freightOnValueRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "freightOnValue" must be string, got %s.', get_debug_type($freightOnValueRaw)),
                );
            }
            $freightOnValue = Some::create(
                CustomsClearanceDetailFreightOnValue::tryFrom($freightOnValueRaw)
                    ?? UnknownEnumValue::of($freightOnValueRaw),
            );
        }
        if (array_key_exists('dutiesPayment', $data) && $data['dutiesPayment'] !== null) {
            $dutiesPaymentRaw = $data['dutiesPayment'];
            if (!is_array($dutiesPaymentRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "dutiesPayment" must be object, got %s.', get_debug_type($dutiesPaymentRaw)),
                );
            }
            /** @var array<string, mixed> $dutiesPaymentRawTyped */
            $dutiesPaymentRawTyped = $dutiesPaymentRaw;
            $dutiesPayment = Some::create(Payment::fromArray($dutiesPaymentRawTyped));
        }
        if (array_key_exists('commodities', $data)) {
            $commoditiesRaw = $data['commodities'];
            if (!(is_array($commoditiesRaw) && array_is_list($commoditiesRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "commodities" must be list, got %s.', get_debug_type($commoditiesRaw)),
                );
            }
            $commodities = array_map(static function (mixed $value_1): Commodity {
                if (!is_array($value_1)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be object, got %s.', get_debug_type($value_1)),
                    );
                }
                /** @var array<string, mixed> $value_1Typed */
                $value_1Typed = $value_1;

                return Commodity::fromArray($value_1Typed);
            }, $commoditiesRaw);
        }
        $additionalProperties = array_diff_key(
            $data,
            [
                'brokers' => true,
                'commercialInvoice' => true,
                'freightOnValue' => true,
                'dutiesPayment' => true,
                'commodities' => true,
            ],
        );
        if ($commodities === null) {
            throw new MalformedDataException('Required property "commodities" is missing from the document.');
        }

        return new self(
            $commodities,
            $brokers,
            $commercialInvoice,
            $freightOnValue,
            $dutiesPayment,
            $additionalProperties,
        );
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $brokersOption = $this->brokers;
        if ($brokersOption->isDefined()) {
            $brokers = $brokersOption->get();
            $values = [];
            foreach ($brokers as $value) {
                $values[] = $normalizationTarget->model($value);
            }
            $dataArray['brokers'] = $values;
        }
        $commercialInvoiceOption = $this->commercialInvoice;
        if ($commercialInvoiceOption->isDefined()) {
            $commercialInvoice = $commercialInvoiceOption->get();
            $dataArray['commercialInvoice'] = $normalizationTarget->model($commercialInvoice);
        }
        $freightOnValueOption = $this->freightOnValue;
        if ($freightOnValueOption->isDefined()) {
            $freightOnValue = $freightOnValueOption->get();
            $dataArray['freightOnValue'] = $freightOnValue->value;
        }
        $dutiesPaymentOption = $this->dutiesPayment;
        if ($dutiesPaymentOption->isDefined()) {
            $dutiesPayment = $dutiesPaymentOption->get();
            $dataArray['dutiesPayment'] = $normalizationTarget->model($dutiesPayment);
        }
        $values_1 = [];
        foreach ($this->commodities as $value_1) {
            $values_1[] = $normalizationTarget->model($value_1);
        }
        $dataArray['commodities'] = $values_1;
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): RequestedShipmentCustomsClearanceDetailBuilder
    {
        return new RequestedShipmentCustomsClearanceDetailBuilder(
            $this->commodities,
            $this->brokers,
            $this->commercialInvoice,
            $this->freightOnValue,
            $this->dutiesPayment,
            $this->additionalProperties,
        );
    }
}
