<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Override;
use Prefabcortex\FedexRatesAndTransitTimesApi\Exception\MalformedDataException;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\None;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_array;
use function is_int;
use function is_string;
use function sprintf;

final readonly class RequestedPackageLineItem implements SelfNormalizingModel
{
    /**
     * @param Option<string>                            $subPackagingType
     * @param Option<int>                               $groupPackageCount
     * @param Option<Money>                             $declaredValue
     * @param Option<RequestePackageLineItemDimensions> $dimensions
     * @param Option<VariableHandlingChargeDetail>      $variableHandlingChargeDetail
     * @param Option<PackageSpecialServicesRequested>   $packageSpecialServices
     * @param array<int|string, mixed>                  $additionalProperties
     */
    public function __construct(
        private Weight2 $weight,
        private Option $subPackagingType,
        private Option $groupPackageCount,
        private Option $declaredValue,
        private Option $dimensions,
        private Option $variableHandlingChargeDetail,
        private Option $packageSpecialServices,
        private array $additionalProperties,
    ) {
    }

    public static function builder(Weight2 $weight): RequestedPackageLineItemBuilder
    {
        return new RequestedPackageLineItemBuilder(
            $weight,
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            [],
        );
    }

    /**
     * This is a physical packaging type used for the package.
     *
     * <a onclick='loadDocReference("subpackagetypes")'>Click here to see sub-packaging types</a>
     *
     * For more information on physical packaging or packaging regulatory requirements, visit
     * fedex.com or contact your FedEx representative.
     *
     * @return Option<string>
     */
    public function getSubPackagingType(): Option
    {
        return $this->subPackagingType;
    }

    /**
     * Indicate the grouped package count. These are number of identical package(s) each with one or
     * more commodities.
     *
     * Example: 2
     *
     * @return Option<int>
     */
    public function getGroupPackageCount(): Option
    {
        return $this->groupPackageCount;
    }

    /**
     * This is the Declared Value - represents FedEx Maximum liability in connection with a shipment
     * of that Package, including but not limited to, any loss, damage, delay, misdelivery, any
     * failure to provide information, or misdelivery of information relating to the Shipment.
     *
     * @return Option<Money>
     */
    public function getDeclaredValue(): Option
    {
        return $this->declaredValue;
    }

    /**
     * Indicate the total weight of the requested package line items.
     */
    public function getWeight(): Weight2
    {
        return $this->weight;
    }

    /**
     * Specify the dimensions of this package and the unit type used for the measurements. Valid
     * measurements are whole numbers greater than zero.
     *
     * @return Option<RequestePackageLineItemDimensions>
     */
    public function getDimensions(): Option
    {
        return $this->dimensions;
    }

    /**
     * Indicate the details on how to calculate variable handling charges at the package level. If
     * indicated, element rateLevelType is required.
     *
     * @return Option<VariableHandlingChargeDetail>
     */
    public function getVariableHandlingChargeDetail(): Option
    {
        return $this->variableHandlingChargeDetail;
    }

    /**
     * These special services are available at the package level for some or all service types.
     * Indicated if rate data is being requested for the special services.
     *
     * @return Option<PackageSpecialServicesRequested>
     */
    public function getPackageSpecialServices(): Option
    {
        return $this->packageSpecialServices;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $subPackagingType = None::create();
        $groupPackageCount = None::create();
        $declaredValue = None::create();
        $weight = null;
        $dimensions = None::create();
        $variableHandlingChargeDetail = None::create();
        $packageSpecialServices = None::create();
        if (array_key_exists('subPackagingType', $data) && $data['subPackagingType'] !== null) {
            $subPackagingTypeRaw = $data['subPackagingType'];
            if (!is_string($subPackagingTypeRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "subPackagingType" must be string, got %s.',
                        get_debug_type($subPackagingTypeRaw),
                    ),
                );
            }
            $subPackagingType = Some::create($subPackagingTypeRaw);
        }
        if (array_key_exists('groupPackageCount', $data) && $data['groupPackageCount'] !== null) {
            $groupPackageCountRaw = $data['groupPackageCount'];
            if (!is_int($groupPackageCountRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "groupPackageCount" must be int, got %s.', get_debug_type($groupPackageCountRaw)),
                );
            }
            $groupPackageCount = Some::create($groupPackageCountRaw);
        }
        if (array_key_exists('declaredValue', $data) && $data['declaredValue'] !== null) {
            $declaredValueRaw = $data['declaredValue'];
            if (!is_array($declaredValueRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "declaredValue" must be object, got %s.', get_debug_type($declaredValueRaw)),
                );
            }
            /** @var array<string, mixed> $declaredValueRawTyped */
            $declaredValueRawTyped = $declaredValueRaw;
            $declaredValue = Some::create(Money::fromArray($declaredValueRawTyped));
        }
        if (array_key_exists('weight', $data)) {
            $weightRaw = $data['weight'];
            if (!is_array($weightRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "weight" must be object, got %s.', get_debug_type($weightRaw)),
                );
            }
            /** @var non-empty-array<string, mixed> $weightRawTyped */
            $weightRawTyped = $weightRaw;
            $weight = Weight2::fromArray($weightRawTyped);
        }
        if (array_key_exists('dimensions', $data) && $data['dimensions'] !== null) {
            $dimensionsRaw = $data['dimensions'];
            if (!is_array($dimensionsRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "dimensions" must be object, got %s.', get_debug_type($dimensionsRaw)),
                );
            }
            /** @var non-empty-array<string, mixed> $dimensionsRawTyped */
            $dimensionsRawTyped = $dimensionsRaw;
            $dimensions = Some::create(RequestePackageLineItemDimensions::fromArray($dimensionsRawTyped));
        }
        if (array_key_exists('variableHandlingChargeDetail', $data) && $data['variableHandlingChargeDetail'] !== null) {
            $variableHandlingChargeDetailRaw = $data['variableHandlingChargeDetail'];
            if (!is_array($variableHandlingChargeDetailRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "variableHandlingChargeDetail" must be object, got %s.',
                        get_debug_type($variableHandlingChargeDetailRaw),
                    ),
                );
            }
            /** @var non-empty-array<string, mixed> $variableHandlingChargeDetailRawTyped */
            $variableHandlingChargeDetailRawTyped = $variableHandlingChargeDetailRaw;
            $variableHandlingChargeDetail = Some::create(
                VariableHandlingChargeDetail::fromArray($variableHandlingChargeDetailRawTyped),
            );
        }
        if (array_key_exists('packageSpecialServices', $data) && $data['packageSpecialServices'] !== null) {
            $packageSpecialServicesRaw = $data['packageSpecialServices'];
            if (!is_array($packageSpecialServicesRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "packageSpecialServices" must be object, got %s.',
                        get_debug_type($packageSpecialServicesRaw),
                    ),
                );
            }
            /** @var array<string, mixed> $packageSpecialServicesRawTyped */
            $packageSpecialServicesRawTyped = $packageSpecialServicesRaw;
            $packageSpecialServices = Some::create(
                PackageSpecialServicesRequested::fromArray($packageSpecialServicesRawTyped),
            );
        }
        $additionalProperties = array_diff_key(
            $data,
            [
                'subPackagingType' => true,
                'groupPackageCount' => true,
                'declaredValue' => true,
                'weight' => true,
                'dimensions' => true,
                'variableHandlingChargeDetail' => true,
                'packageSpecialServices' => true,
            ],
        );
        if ($weight === null) {
            throw new MalformedDataException('Required property "weight" is missing from the document.');
        }

        return new self(
            $weight,
            $subPackagingType,
            $groupPackageCount,
            $declaredValue,
            $dimensions,
            $variableHandlingChargeDetail,
            $packageSpecialServices,
            $additionalProperties,
        );
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $subPackagingTypeOption = $this->subPackagingType;
        if ($subPackagingTypeOption->isDefined()) {
            $subPackagingType = $subPackagingTypeOption->get();
            $dataArray['subPackagingType'] = $subPackagingType;
        }
        $groupPackageCountOption = $this->groupPackageCount;
        if ($groupPackageCountOption->isDefined()) {
            $groupPackageCount = $groupPackageCountOption->get();
            $dataArray['groupPackageCount'] = $groupPackageCount;
        }
        $declaredValueOption = $this->declaredValue;
        if ($declaredValueOption->isDefined()) {
            $declaredValue = $declaredValueOption->get();
            $dataArray['declaredValue'] = $normalizationTarget->model($declaredValue);
        }
        $dataArray['weight'] = $normalizationTarget->model($this->weight);
        $dimensionsOption = $this->dimensions;
        if ($dimensionsOption->isDefined()) {
            $dimensions = $dimensionsOption->get();
            $dataArray['dimensions'] = $normalizationTarget->model($dimensions);
        }
        $variableHandlingChargeDetailOption = $this->variableHandlingChargeDetail;
        if ($variableHandlingChargeDetailOption->isDefined()) {
            $variableHandlingChargeDetail = $variableHandlingChargeDetailOption->get();
            $dataArray['variableHandlingChargeDetail'] = $normalizationTarget->model($variableHandlingChargeDetail);
        }
        $packageSpecialServicesOption = $this->packageSpecialServices;
        if ($packageSpecialServicesOption->isDefined()) {
            $packageSpecialServices = $packageSpecialServicesOption->get();
            $dataArray['packageSpecialServices'] = $normalizationTarget->model($packageSpecialServices);
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): RequestedPackageLineItemBuilder
    {
        return new RequestedPackageLineItemBuilder(
            $this->weight,
            $this->subPackagingType,
            $this->groupPackageCount,
            $this->declaredValue,
            $this->dimensions,
            $this->variableHandlingChargeDetail,
            $this->packageSpecialServices,
            $this->additionalProperties,
        );
    }
}
