<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

enum RequestedShipmentRateRequestTypeItem: string
{
    case LIST = 'LIST';
    case INCENTIVE = 'INCENTIVE';
    case ACCOUNT = 'ACCOUNT';
    case PREFERRED = 'PREFERRED';
}
