<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

/**
 * Builds a {@see ServiceDescription}.
 */
final class ServiceDescriptionBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>            $serviceType
     * @param Option<string>            $code
     * @param Option<list<ProductName>> $names
     * @param Option<string>            $astraDescription
     * @param Option<string>            $description
     * @param Option<string>            $serviceId
     * @param Option<string>            $serviceCategory
     * @param array<int|string, mixed>  $additionalProperties
     */
    public function __construct(
        private Option $serviceType,
        private Option $code,
        private Option $names,
        private Option $astraDescription,
        private Option $description,
        private Option $serviceId,
        private Option $serviceCategory,
        private array $additionalProperties,
    ) {
    }

    /**
     * This is the service type.
     *
     * Example: INTERNATIONAL_FIRST
     *
     * <a onclick='loadDocReference("servicetypes")'>Click here to see Service Types</a>
     */
    public function setServiceType(string $serviceType): self
    {
        $this->serviceType = Some::create($serviceType);

        return $this;
    }

    /**
     * Specifies the service code.
     *
     * Example: 92
     */
    public function setCode(string $code): self
    {
        $this->code = Some::create($code);

        return $this;
    }

    /**
     * Specifies the service name.
     *
     * @param list<ProductName> $names
     */
    public function setNames(array $names): self
    {
        $this->names = Some::create($names);

        return $this;
    }

    /**
     * Specifies astra description.
     *
     * Example: INTL1ST
     */
    public function setAstraDescription(string $astraDescription): self
    {
        $this->astraDescription = Some::create($astraDescription);

        return $this;
    }

    /**
     * Specifies description of the service.
     *
     * Example: FedEx Ground
     */
    public function setDescription(string $description): self
    {
        $this->description = Some::create($description);

        return $this;
    }

    /**
     * Specifies the service Id.
     *
     * Example: EP1000000135
     */
    public function setServiceId(string $serviceId): self
    {
        $this->serviceId = Some::create($serviceId);

        return $this;
    }

    /**
     * Specifies service category.
     *
     * Example: parcel
     */
    public function setServiceCategory(string $serviceCategory): self
    {
        $this->serviceCategory = Some::create($serviceCategory);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): ServiceDescription
    {
        return new ServiceDescription(
            $this->serviceType,
            $this->code,
            $this->names,
            $this->astraDescription,
            $this->description,
            $this->serviceId,
            $this->serviceCategory,
            $this->additionalProperties,
        );
    }
}
