<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Override;
use Prefabcortex\FedexRatesAndTransitTimesApi\Exception\MalformedDataException;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\None;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

use function array_diff_key;
use function array_is_list;
use function array_key_exists;
use function array_map;
use function get_debug_type;
use function is_array;
use function is_string;
use function sprintf;

final readonly class ServiceDescription implements SelfNormalizingModel
{
    /**
     * @param Option<string>            $serviceType
     * @param Option<string>            $code
     * @param Option<list<ProductName>> $names
     * @param Option<string>            $astraDescription
     * @param Option<string>            $description
     * @param Option<string>            $serviceId
     * @param Option<string>            $serviceCategory
     * @param array<int|string, mixed>  $additionalProperties
     */
    public function __construct(
        private Option $serviceType,
        private Option $code,
        private Option $names,
        private Option $astraDescription,
        private Option $description,
        private Option $serviceId,
        private Option $serviceCategory,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): ServiceDescriptionBuilder
    {
        return new ServiceDescriptionBuilder(
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            [],
        );
    }

    /**
     * This is the service type.
     *
     * Example: INTERNATIONAL_FIRST
     *
     * <a onclick='loadDocReference("servicetypes")'>Click here to see Service Types</a>
     *
     * @return Option<string>
     */
    public function getServiceType(): Option
    {
        return $this->serviceType;
    }

    /**
     * Specifies the service code.
     *
     * Example: 92
     *
     * @return Option<string>
     */
    public function getCode(): Option
    {
        return $this->code;
    }

    /**
     * Specifies the service name.
     *
     * @return Option<list<ProductName>>
     */
    public function getNames(): Option
    {
        return $this->names;
    }

    /**
     * Specifies astra description.
     *
     * Example: INTL1ST
     *
     * @return Option<string>
     */
    public function getAstraDescription(): Option
    {
        return $this->astraDescription;
    }

    /**
     * Specifies description of the service.
     *
     * Example: FedEx Ground
     *
     * @return Option<string>
     */
    public function getDescription(): Option
    {
        return $this->description;
    }

    /**
     * Specifies the service Id.
     *
     * Example: EP1000000135
     *
     * @return Option<string>
     */
    public function getServiceId(): Option
    {
        return $this->serviceId;
    }

    /**
     * Specifies service category.
     *
     * Example: parcel
     *
     * @return Option<string>
     */
    public function getServiceCategory(): Option
    {
        return $this->serviceCategory;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $serviceType = None::create();
        $code = None::create();
        $names = None::create();
        $astraDescription = None::create();
        $description = None::create();
        $serviceId = None::create();
        $serviceCategory = None::create();
        if (array_key_exists('serviceType', $data) && $data['serviceType'] !== null) {
            $serviceTypeRaw = $data['serviceType'];
            if (!is_string($serviceTypeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "serviceType" must be string, got %s.', get_debug_type($serviceTypeRaw)),
                );
            }
            $serviceType = Some::create($serviceTypeRaw);
        }
        if (array_key_exists('code', $data) && $data['code'] !== null) {
            $codeRaw = $data['code'];
            if (!is_string($codeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "code" must be string, got %s.', get_debug_type($codeRaw)),
                );
            }
            $code = Some::create($codeRaw);
        }
        if (array_key_exists('names', $data) && $data['names'] !== null) {
            $namesRaw = $data['names'];
            if (!(is_array($namesRaw) && array_is_list($namesRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "names" must be list, got %s.', get_debug_type($namesRaw)),
                );
            }
            $names = Some::create(array_map(static function (mixed $value): ProductName {
                if (!is_array($value)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be object, got %s.', get_debug_type($value)),
                    );
                }
                /** @var array<string, mixed> $valueTyped */
                $valueTyped = $value;

                return ProductName::fromArray($valueTyped);
            }, $namesRaw));
        }
        if (array_key_exists('astraDescription', $data) && $data['astraDescription'] !== null) {
            $astraDescriptionRaw = $data['astraDescription'];
            if (!is_string($astraDescriptionRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "astraDescription" must be string, got %s.',
                        get_debug_type($astraDescriptionRaw),
                    ),
                );
            }
            $astraDescription = Some::create($astraDescriptionRaw);
        }
        if (array_key_exists('description', $data) && $data['description'] !== null) {
            $descriptionRaw = $data['description'];
            if (!is_string($descriptionRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "description" must be string, got %s.', get_debug_type($descriptionRaw)),
                );
            }
            $description = Some::create($descriptionRaw);
        }
        if (array_key_exists('serviceId', $data) && $data['serviceId'] !== null) {
            $serviceIdRaw = $data['serviceId'];
            if (!is_string($serviceIdRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "serviceId" must be string, got %s.', get_debug_type($serviceIdRaw)),
                );
            }
            $serviceId = Some::create($serviceIdRaw);
        }
        if (array_key_exists('serviceCategory', $data) && $data['serviceCategory'] !== null) {
            $serviceCategoryRaw = $data['serviceCategory'];
            if (!is_string($serviceCategoryRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "serviceCategory" must be string, got %s.', get_debug_type($serviceCategoryRaw)),
                );
            }
            $serviceCategory = Some::create($serviceCategoryRaw);
        }
        $additionalProperties = array_diff_key(
            $data,
            [
                'serviceType' => true,
                'code' => true,
                'names' => true,
                'astraDescription' => true,
                'description' => true,
                'serviceId' => true,
                'serviceCategory' => true,
            ],
        );

        return new self(
            $serviceType,
            $code,
            $names,
            $astraDescription,
            $description,
            $serviceId,
            $serviceCategory,
            $additionalProperties,
        );
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $serviceTypeOption = $this->serviceType;
        if ($serviceTypeOption->isDefined()) {
            $serviceType = $serviceTypeOption->get();
            $dataArray['serviceType'] = $serviceType;
        }
        $codeOption = $this->code;
        if ($codeOption->isDefined()) {
            $code = $codeOption->get();
            $dataArray['code'] = $code;
        }
        $namesOption = $this->names;
        if ($namesOption->isDefined()) {
            $names = $namesOption->get();
            $values = [];
            foreach ($names as $value) {
                $values[] = $normalizationTarget->model($value);
            }
            $dataArray['names'] = $values;
        }
        $astraDescriptionOption = $this->astraDescription;
        if ($astraDescriptionOption->isDefined()) {
            $astraDescription = $astraDescriptionOption->get();
            $dataArray['astraDescription'] = $astraDescription;
        }
        $descriptionOption = $this->description;
        if ($descriptionOption->isDefined()) {
            $description = $descriptionOption->get();
            $dataArray['description'] = $description;
        }
        $serviceIdOption = $this->serviceId;
        if ($serviceIdOption->isDefined()) {
            $serviceId = $serviceIdOption->get();
            $dataArray['serviceId'] = $serviceId;
        }
        $serviceCategoryOption = $this->serviceCategory;
        if ($serviceCategoryOption->isDefined()) {
            $serviceCategory = $serviceCategoryOption->get();
            $dataArray['serviceCategory'] = $serviceCategory;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): ServiceDescriptionBuilder
    {
        return new ServiceDescriptionBuilder(
            $this->serviceType,
            $this->code,
            $this->names,
            $this->astraDescription,
            $this->description,
            $this->serviceId,
            $this->serviceCategory,
            $this->additionalProperties,
        );
    }
}
