<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Override;
use Prefabcortex\FedexRatesAndTransitTimesApi\Exception\MalformedDataException;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\None;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_string;
use function sprintf;

final readonly class ServiceTypeDetailVO implements SelfNormalizingModel
{
    /**
     * @param Option<ServiceTypeDetailVOCarrierCode|UnknownEnumValue<string>> $carrierCode
     * @param Option<string>                                                  $description
     * @param Option<string>                                                  $serviceName
     * @param Option<string>                                                  $serviceCategory
     * @param array<int|string, mixed>                                        $additionalProperties
     */
    public function __construct(
        private Option $carrierCode,
        private Option $description,
        private Option $serviceName,
        private Option $serviceCategory,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): ServiceTypeDetailVOBuilder
    {
        return new ServiceTypeDetailVOBuilder(None::create(), None::create(), None::create(), None::create(), []);
    }

    /**
     * Identifies which carrier is being described.
     *
     * @return Option<ServiceTypeDetailVOCarrierCode|UnknownEnumValue<string>>
     */
    public function getCarrierCode(): Option
    {
        return $this->carrierCode;
    }

    /**
     * Description.
     *
     * @return Option<string>
     */
    public function getDescription(): Option
    {
        return $this->description;
    }

    /**
     * Service Name.
     *
     * @return Option<string>
     */
    public function getServiceName(): Option
    {
        return $this->serviceName;
    }

    /**
     * Service Category.
     *
     * @return Option<string>
     */
    public function getServiceCategory(): Option
    {
        return $this->serviceCategory;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $carrierCode = None::create();
        $description = None::create();
        $serviceName = None::create();
        $serviceCategory = None::create();
        if (array_key_exists('carrierCode', $data) && $data['carrierCode'] !== null) {
            $carrierCodeRaw = $data['carrierCode'];
            if (!is_string($carrierCodeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "carrierCode" must be string, got %s.', get_debug_type($carrierCodeRaw)),
                );
            }
            $carrierCode = Some::create(
                ServiceTypeDetailVOCarrierCode::tryFrom($carrierCodeRaw) ?? UnknownEnumValue::of($carrierCodeRaw),
            );
        }
        if (array_key_exists('description', $data) && $data['description'] !== null) {
            $descriptionRaw = $data['description'];
            if (!is_string($descriptionRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "description" must be string, got %s.', get_debug_type($descriptionRaw)),
                );
            }
            $description = Some::create($descriptionRaw);
        }
        if (array_key_exists('serviceName', $data) && $data['serviceName'] !== null) {
            $serviceNameRaw = $data['serviceName'];
            if (!is_string($serviceNameRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "serviceName" must be string, got %s.', get_debug_type($serviceNameRaw)),
                );
            }
            $serviceName = Some::create($serviceNameRaw);
        }
        if (array_key_exists('serviceCategory', $data) && $data['serviceCategory'] !== null) {
            $serviceCategoryRaw = $data['serviceCategory'];
            if (!is_string($serviceCategoryRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "serviceCategory" must be string, got %s.', get_debug_type($serviceCategoryRaw)),
                );
            }
            $serviceCategory = Some::create($serviceCategoryRaw);
        }
        $additionalProperties = array_diff_key(
            $data,
            ['carrierCode' => true, 'description' => true, 'serviceName' => true, 'serviceCategory' => true],
        );

        return new self($carrierCode, $description, $serviceName, $serviceCategory, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $carrierCodeOption = $this->carrierCode;
        if ($carrierCodeOption->isDefined()) {
            $carrierCode = $carrierCodeOption->get();
            $dataArray['carrierCode'] = $carrierCode->value;
        }
        $descriptionOption = $this->description;
        if ($descriptionOption->isDefined()) {
            $description = $descriptionOption->get();
            $dataArray['description'] = $description;
        }
        $serviceNameOption = $this->serviceName;
        if ($serviceNameOption->isDefined()) {
            $serviceName = $serviceNameOption->get();
            $dataArray['serviceName'] = $serviceName;
        }
        $serviceCategoryOption = $this->serviceCategory;
        if ($serviceCategoryOption->isDefined()) {
            $serviceCategory = $serviceCategoryOption->get();
            $dataArray['serviceCategory'] = $serviceCategory;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): ServiceTypeDetailVOBuilder
    {
        return new ServiceTypeDetailVOBuilder(
            $this->carrierCode,
            $this->description,
            $this->serviceName,
            $this->serviceCategory,
            $this->additionalProperties,
        );
    }
}
