<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

/**
 * Builds a {@see ShipmentSpecialServicesRequestedReturnShipmentDetail}.
 */
final class ShipmentSpecialServicesRequestedReturnShipmentDetailBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<ShipmentSpecialServicesRequestedReturnShipmentDetailReturnType|UnknownEnumValue<string>> $returnType
     * @param array<int|string, mixed>                                                                        $additionalProperties
     */
    public function __construct(private Option $returnType, private array $additionalProperties)
    {
    }

    /**
     * The type of return shipment being requested.
     */
    public function setReturnType(ShipmentSpecialServicesRequestedReturnShipmentDetailReturnType $returnType): self
    {
        $this->returnType = Some::create($returnType);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): ShipmentSpecialServicesRequestedReturnShipmentDetail
    {
        return new ShipmentSpecialServicesRequestedReturnShipmentDetail($this->returnType, $this->additionalProperties);
    }
}
