<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Override;
use Prefabcortex\FedexRatesAndTransitTimesApi\Exception\MalformedDataException;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\None;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_string;
use function sprintf;

final readonly class ShipmentSpecialServicesRequestedReturnShipmentDetail implements SelfNormalizingModel
{
    /**
     * @param Option<ShipmentSpecialServicesRequestedReturnShipmentDetailReturnType|UnknownEnumValue<string>> $returnType
     * @param array<int|string, mixed>                                                                        $additionalProperties
     */
    public function __construct(private Option $returnType, private array $additionalProperties)
    {
    }

    public static function builder(): ShipmentSpecialServicesRequestedReturnShipmentDetailBuilder
    {
        return new ShipmentSpecialServicesRequestedReturnShipmentDetailBuilder(None::create(), []);
    }

    /**
     * The type of return shipment being requested.
     *
     * @return Option<ShipmentSpecialServicesRequestedReturnShipmentDetailReturnType|UnknownEnumValue<string>>
     */
    public function getReturnType(): Option
    {
        return $this->returnType;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $returnType = None::create();
        if (array_key_exists('returnType', $data) && $data['returnType'] !== null) {
            $returnTypeRaw = $data['returnType'];
            if (!is_string($returnTypeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "returnType" must be string, got %s.', get_debug_type($returnTypeRaw)),
                );
            }
            $returnType = Some::create(
                ShipmentSpecialServicesRequestedReturnShipmentDetailReturnType::tryFrom($returnTypeRaw)
                    ?? UnknownEnumValue::of($returnTypeRaw),
            );
        }
        $additionalProperties = array_diff_key($data, ['returnType' => true]);

        return new self($returnType, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $returnTypeOption = $this->returnType;
        if ($returnTypeOption->isDefined()) {
            $returnType = $returnTypeOption->get();
            $dataArray['returnType'] = $returnType->value;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): ShipmentSpecialServicesRequestedReturnShipmentDetailBuilder
    {
        return new ShipmentSpecialServicesRequestedReturnShipmentDetailBuilder(
            $this->returnType,
            $this->additionalProperties,
        );
    }
}
