<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

/**
 * Builds a {@see ShipmentRateDetail}.
 */
final class ShipmentRateDetailBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<CurrencyExchangeRate>                                   $currencyExchangeRate
     * @param Option<string>                                                 $currency
     * @param Option<string>                                                 $rateZone
     * @param Option<ShipmentRateDetailRatingBasis|UnknownEnumValue<string>> $ratingBasis
     * @param Option<string>                                                 $pricingCode
     * @param Option<float>                                                  $totalFreightDiscount
     * @param Option<list<string>>                                           $specialRatingApplied
     * @param Option<float>                                                  $totalSurcharges
     * @param Option<list<RateDiscount>>                                     $freightDiscount
     * @param Option<float>                                                  $fuelSurchargePercent
     * @param Option<Weight1>                                                $totalBillingWeight
     * @param Option<Weight1>                                                $totalDimWeight
     * @param Option<int>                                                    $dimDivisor
     * @param Option<list<Surcharge>>                                        $surCharges
     * @param Option<list<Tax>>                                              $taxes
     * @param array<int|string, mixed>                                       $additionalProperties
     */
    public function __construct(
        private Option $currencyExchangeRate,
        private Option $currency,
        private Option $rateZone,
        private Option $ratingBasis,
        private Option $pricingCode,
        private Option $totalFreightDiscount,
        private Option $specialRatingApplied,
        private Option $totalSurcharges,
        private Option $freightDiscount,
        private Option $fuelSurchargePercent,
        private Option $totalBillingWeight,
        private Option $totalDimWeight,
        private Option $dimDivisor,
        private Option $surCharges,
        private Option $taxes,
        private array $additionalProperties,
    ) {
    }

    /**
     * Specifies the currency exchange performed on financial amounts for this rate.
     */
    public function setCurrencyExchangeRate(CurrencyExchangeRate $currencyExchangeRate): self
    {
        $this->currencyExchangeRate = Some::create($currencyExchangeRate);

        return $this;
    }

    /**
     * Indicates the currency associated with the amount.
     */
    public function setCurrency(string $currency): self
    {
        $this->currency = Some::create($currency);

        return $this;
    }

    /**
     * Indicates the rate zone used.
     */
    public function setRateZone(string $rateZone): self
    {
        $this->rateZone = Some::create($rateZone);

        return $this;
    }

    /**
     * Allows clients to determine whether to add charges at the package level when Per Piece Rating
     * details are returned.
     *
     * <ul><li>SHIPMENT_WEIGHT_BASED - Indicates shipment weight is used to calculate the rate.</li>
     *
     * <li>FLAT_RATE_PER_PAK - Indicates shipment is rated based on number of packs, weight would be
     * considered for overweight surcharge but not for calculating shipment rate.</li>
     *
     * <li>PACK_WEIGHT_BASED - Indicates individual package weight would be rated and aggregated to
     * get shipment rate weight.</li></ul> Example : SHIPMENT_WEIGHT_BASED.
     */
    public function setRatingBasis(ShipmentRateDetailRatingBasis $ratingBasis): self
    {
        $this->ratingBasis = Some::create($ratingBasis);

        return $this;
    }

    /**
     * Indicates the type of pricing code.
     */
    public function setPricingCode(string $pricingCode): self
    {
        $this->pricingCode = Some::create($pricingCode);

        return $this;
    }

    /**
     * Indicates the total discounts used in the rate calculation. Example: 856.32.
     */
    public function setTotalFreightDiscount(float $totalFreightDiscount): self
    {
        $this->totalFreightDiscount = Some::create($totalFreightDiscount);

        return $this;
    }

    /**
     * Indicates which special rating cases applied to this shipment.
     *
     * @param list<string> $specialRatingApplied
     */
    public function setSpecialRatingApplied(array $specialRatingApplied): self
    {
        $this->specialRatingApplied = Some::create($specialRatingApplied);

        return $this;
    }

    /**
     * This is sum of all surcharges on the package. Example: 586.25.
     */
    public function setTotalSurcharges(float $totalSurcharges): self
    {
        $this->totalSurcharges = Some::create($totalSurcharges);

        return $this;
    }

    /**
     * This is total discount used in the rate calculation.
     *
     * <a onclick='loadDocReference("discounts")'>Click here to see Discounts</a>
     *
     * @param list<RateDiscount> $freightDiscount
     */
    public function setFreightDiscount(array $freightDiscount): self
    {
        $this->freightDiscount = Some::create($freightDiscount);

        return $this;
    }

    /**
     * This is fuel surcharge percentage.
     */
    public function setFuelSurchargePercent(float $fuelSurchargePercent): self
    {
        $this->fuelSurchargePercent = Some::create($fuelSurchargePercent);

        return $this;
    }

    /**
     * This is total of billing weight for the shipment.
     */
    public function setTotalBillingWeight(Weight1 $totalBillingWeight): self
    {
        $this->totalBillingWeight = Some::create($totalBillingWeight);

        return $this;
    }

    /**
     * This is total of dimensional weight for the shipment.
     */
    public function setTotalDimWeight(Weight1 $totalDimWeight): self
    {
        $this->totalDimWeight = Some::create($totalDimWeight);

        return $this;
    }

    /**
     * Identifies the type of divisor that was applied.
     *
     * Example: 10
     */
    public function setDimDivisor(int $dimDivisor): self
    {
        $this->dimDivisor = Some::create($dimDivisor);

        return $this;
    }

    /**
     * Indicates the surcharges applied to this shipment.
     *
     * @param list<Surcharge> $surCharges
     */
    public function setSurCharges(array $surCharges): self
    {
        $this->surCharges = Some::create($surCharges);

        return $this;
    }

    /**
     * List of taxes.
     *
     * @param list<Tax> $taxes
     */
    public function setTaxes(array $taxes): self
    {
        $this->taxes = Some::create($taxes);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): ShipmentRateDetail
    {
        return new ShipmentRateDetail(
            $this->currencyExchangeRate,
            $this->currency,
            $this->rateZone,
            $this->ratingBasis,
            $this->pricingCode,
            $this->totalFreightDiscount,
            $this->specialRatingApplied,
            $this->totalSurcharges,
            $this->freightDiscount,
            $this->fuelSurchargePercent,
            $this->totalBillingWeight,
            $this->totalDimWeight,
            $this->dimDivisor,
            $this->surCharges,
            $this->taxes,
            $this->additionalProperties,
        );
    }
}
