<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Override;
use Prefabcortex\FedexRatesAndTransitTimesApi\Exception\MalformedDataException;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\None;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_array;
use function is_string;
use function sprintf;

final readonly class ShipmentCODDetail implements SelfNormalizingModel
{
    /**
     * @param Option<CODTransportationChargesDetail>                                         $addTransportationChargesDetail
     * @param Option<Party2>                                                                 $codRecipient
     * @param Option<string>                                                                 $remitToName
     * @param Option<ShipmentCODDetailCodCollectionType|UnknownEnumValue<string>>            $codCollectionType
     * @param Option<ContactAndAddress>                                                      $financialInstitutionContactAndAddress
     * @param Option<ShipmentCODDetailReturnReferenceIndicatorType|UnknownEnumValue<string>> $returnReferenceIndicatorType
     * @param array<int|string, mixed>                                                       $additionalProperties
     */
    public function __construct(
        private Option $addTransportationChargesDetail,
        private Option $codRecipient,
        private Option $remitToName,
        private Option $codCollectionType,
        private Option $financialInstitutionContactAndAddress,
        private Option $returnReferenceIndicatorType,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): ShipmentCODDetailBuilder
    {
        return new ShipmentCODDetailBuilder(
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            [],
        );
    }

    /**
     * These are COD Transportation Charges Detail.
     *
     * @return Option<CODTransportationChargesDetail>
     */
    public function getAddTransportationChargesDetail(): Option
    {
        return $this->addTransportationChargesDetail;
    }

    /**
     * Indicate the party to a transaction including the physical address, contact information and
     * account number information.
     *
     * @return Option<Party2>
     */
    public function getCodRecipient(): Option
    {
        return $this->codRecipient;
    }

    /**
     * Specifies the name of person or company receiving the secured or unsecured payment.
     *
     * Example: FedEx
     *
     * @return Option<string>
     */
    public function getRemitToName(): Option
    {
        return $this->remitToName;
    }

    /**
     * Indicate the type of funds FedEx should collect upon shipment delivery.
     *
     * @return Option<ShipmentCODDetailCodCollectionType|UnknownEnumValue<string>>
     */
    public function getCodCollectionType(): Option
    {
        return $this->codCollectionType;
    }

    /**
     * Specify the contact and address details of a location.
     *
     * @return Option<ContactAndAddress>
     */
    public function getFinancialInstitutionContactAndAddress(): Option
    {
        return $this->financialInstitutionContactAndAddress;
    }

    /**
     * Indicate the type of reference information to include on the COD return shipping label.
     *
     * @return Option<ShipmentCODDetailReturnReferenceIndicatorType|UnknownEnumValue<string>>
     */
    public function getReturnReferenceIndicatorType(): Option
    {
        return $this->returnReferenceIndicatorType;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $addTransportationChargesDetail = None::create();
        $codRecipient = None::create();
        $remitToName = None::create();
        $codCollectionType = None::create();
        $financialInstitutionContactAndAddress = None::create();
        $returnReferenceIndicatorType = None::create();
        if (
            array_key_exists('addTransportationChargesDetail', $data)
            && $data['addTransportationChargesDetail'] !== null
        ) {
            $addTransportationChargesDetailRaw = $data['addTransportationChargesDetail'];
            if (!is_array($addTransportationChargesDetailRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "addTransportationChargesDetail" must be object, got %s.',
                        get_debug_type($addTransportationChargesDetailRaw),
                    ),
                );
            }
            /** @var array<string, mixed> $addTransportationChargesDetailRawTyped */
            $addTransportationChargesDetailRawTyped = $addTransportationChargesDetailRaw;
            $addTransportationChargesDetail = Some::create(
                CODTransportationChargesDetail::fromArray($addTransportationChargesDetailRawTyped),
            );
        }
        if (array_key_exists('codRecipient', $data) && $data['codRecipient'] !== null) {
            $codRecipientRaw = $data['codRecipient'];
            if (!is_array($codRecipientRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "codRecipient" must be object, got %s.', get_debug_type($codRecipientRaw)),
                );
            }
            /** @var array<string, mixed> $codRecipientRawTyped */
            $codRecipientRawTyped = $codRecipientRaw;
            $codRecipient = Some::create(Party2::fromArray($codRecipientRawTyped));
        }
        if (array_key_exists('remitToName', $data) && $data['remitToName'] !== null) {
            $remitToNameRaw = $data['remitToName'];
            if (!is_string($remitToNameRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "remitToName" must be string, got %s.', get_debug_type($remitToNameRaw)),
                );
            }
            $remitToName = Some::create($remitToNameRaw);
        }
        if (array_key_exists('codCollectionType', $data) && $data['codCollectionType'] !== null) {
            $codCollectionTypeRaw = $data['codCollectionType'];
            if (!is_string($codCollectionTypeRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "codCollectionType" must be string, got %s.',
                        get_debug_type($codCollectionTypeRaw),
                    ),
                );
            }
            $codCollectionType = Some::create(
                ShipmentCODDetailCodCollectionType::tryFrom($codCollectionTypeRaw)
                    ?? UnknownEnumValue::of($codCollectionTypeRaw),
            );
        }
        if (
            array_key_exists('financialInstitutionContactAndAddress', $data)
            && $data['financialInstitutionContactAndAddress'] !== null
        ) {
            $financialInstitutionContactAndAddressRaw = $data['financialInstitutionContactAndAddress'];
            if (!is_array($financialInstitutionContactAndAddressRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "financialInstitutionContactAndAddress" must be object, got %s.',
                        get_debug_type($financialInstitutionContactAndAddressRaw),
                    ),
                );
            }
            /** @var array<string, mixed> $financialInstitutionContactAndAddressRawTyped */
            $financialInstitutionContactAndAddressRawTyped = $financialInstitutionContactAndAddressRaw;
            $financialInstitutionContactAndAddress = Some::create(
                ContactAndAddress::fromArray($financialInstitutionContactAndAddressRawTyped),
            );
        }
        if (array_key_exists('returnReferenceIndicatorType', $data) && $data['returnReferenceIndicatorType'] !== null) {
            $returnReferenceIndicatorTypeRaw = $data['returnReferenceIndicatorType'];
            if (!is_string($returnReferenceIndicatorTypeRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "returnReferenceIndicatorType" must be string, got %s.',
                        get_debug_type($returnReferenceIndicatorTypeRaw),
                    ),
                );
            }
            $returnReferenceIndicatorType = Some::create(
                ShipmentCODDetailReturnReferenceIndicatorType::tryFrom($returnReferenceIndicatorTypeRaw)
                    ?? UnknownEnumValue::of($returnReferenceIndicatorTypeRaw),
            );
        }
        $additionalProperties = array_diff_key(
            $data,
            [
                'addTransportationChargesDetail' => true,
                'codRecipient' => true,
                'remitToName' => true,
                'codCollectionType' => true,
                'financialInstitutionContactAndAddress' => true,
                'returnReferenceIndicatorType' => true,
            ],
        );

        return new self(
            $addTransportationChargesDetail,
            $codRecipient,
            $remitToName,
            $codCollectionType,
            $financialInstitutionContactAndAddress,
            $returnReferenceIndicatorType,
            $additionalProperties,
        );
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $addTransportationChargesDetailOption = $this->addTransportationChargesDetail;
        if ($addTransportationChargesDetailOption->isDefined()) {
            $addTransportationChargesDetail = $addTransportationChargesDetailOption->get();
            $dataArray['addTransportationChargesDetail'] = $normalizationTarget->model($addTransportationChargesDetail);
        }
        $codRecipientOption = $this->codRecipient;
        if ($codRecipientOption->isDefined()) {
            $codRecipient = $codRecipientOption->get();
            $dataArray['codRecipient'] = $normalizationTarget->model($codRecipient);
        }
        $remitToNameOption = $this->remitToName;
        if ($remitToNameOption->isDefined()) {
            $remitToName = $remitToNameOption->get();
            $dataArray['remitToName'] = $remitToName;
        }
        $codCollectionTypeOption = $this->codCollectionType;
        if ($codCollectionTypeOption->isDefined()) {
            $codCollectionType = $codCollectionTypeOption->get();
            $dataArray['codCollectionType'] = $codCollectionType->value;
        }
        $financialInstitutionContactAndAddressOption = $this->financialInstitutionContactAndAddress;
        if ($financialInstitutionContactAndAddressOption->isDefined()) {
            $financialInstitutionContactAndAddress = $financialInstitutionContactAndAddressOption->get();
            $dataArray['financialInstitutionContactAndAddress'] = $normalizationTarget->model(
                $financialInstitutionContactAndAddress,
            );
        }
        $returnReferenceIndicatorTypeOption = $this->returnReferenceIndicatorType;
        if ($returnReferenceIndicatorTypeOption->isDefined()) {
            $returnReferenceIndicatorType = $returnReferenceIndicatorTypeOption->get();
            $dataArray['returnReferenceIndicatorType'] = $returnReferenceIndicatorType->value;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): ShipmentCODDetailBuilder
    {
        return new ShipmentCODDetailBuilder(
            $this->addTransportationChargesDetail,
            $this->codRecipient,
            $this->remitToName,
            $this->codCollectionType,
            $this->financialInstitutionContactAndAddress,
            $this->returnReferenceIndicatorType,
            $this->additionalProperties,
        );
    }
}
