<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Override;
use Prefabcortex\FedexRatesAndTransitTimesApi\Exception\MalformedDataException;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\None;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

use function array_diff_key;
use function array_is_list;
use function array_key_exists;
use function array_map;
use function get_debug_type;
use function is_array;
use function is_float;
use function is_int;
use function is_string;
use function sprintf;

final readonly class ShipmentLegRateDetail1 implements SelfNormalizingModel
{
    /**
     * @param Option<list<RateDiscount1>>  $discounts
     * @param Option<string>               $pricingCode
     * @param Option<string>               $legDescription
     * @param Option<list<Surcharge1>>     $surcharges
     * @param Option<list<string>>         $specialRatingApplied
     * @param Option<list<Tax1>>           $taxes
     * @param Option<string>               $rateScale
     * @param Option<float>                $totalNetCharge
     * @param Option<float>                $totalBaseCharge
     * @param Option<CurrencyExchangeRate> $currencyExchangeRate
     * @param Option<Weight1>              $totalBillingWeight
     * @param Option<string>               $currency
     * @param array<int|string, mixed>     $additionalProperties
     */
    public function __construct(
        private Option $discounts,
        private Option $pricingCode,
        private Option $legDescription,
        private Option $surcharges,
        private Option $specialRatingApplied,
        private Option $taxes,
        private Option $rateScale,
        private Option $totalNetCharge,
        private Option $totalBaseCharge,
        private Option $currencyExchangeRate,
        private Option $totalBillingWeight,
        private Option $currency,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): ShipmentLegRateDetail1Builder
    {
        return new ShipmentLegRateDetail1Builder(
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            [],
        );
    }

    /**
     * Specifies the list of discounts.
     *
     * <a onclick='loadDocReference("discounts")'>Click here to see Discounts</a>
     *
     * @return Option<list<RateDiscount1>>
     */
    public function getDiscounts(): Option
    {
        return $this->discounts;
    }

    /**
     * Identifies the type of pricing used for this shipment.
     *
     * Example: ACTUAL
     *
     * @return Option<string>
     */
    public function getPricingCode(): Option
    {
        return $this->pricingCode;
    }

    /**
     * Human-readable text describing the shipment leg.
     *
     * Example: legDescription
     *
     * @return Option<string>
     */
    public function getLegDescription(): Option
    {
        return $this->legDescription;
    }

    /**
     * Specifies the list of surcharges.
     *
     * Valid value
     * is:<li>PEAK</li><li>PEAK_ADDTIONAL_HANDLING</li><li>PEAK_OVERSIZE</li><li>PEAK_RESIDENTIAL_DELIVERY</li>
     *
     * @return Option<list<Surcharge1>>
     */
    public function getSurcharges(): Option
    {
        return $this->surcharges;
    }

    /**
     * Indicates which special rating cases applied to this shipment.
     *
     * @return Option<list<string>>
     */
    public function getSpecialRatingApplied(): Option
    {
        return $this->specialRatingApplied;
    }

    /**
     * Specifies the list of taxes.
     *
     * @return Option<list<Tax1>>
     */
    public function getTaxes(): Option
    {
        return $this->taxes;
    }

    /**
     * Indicates the rate scale used.
     *
     * Example: *USER IMS20160104 LD067110
     *
     * @return Option<string>
     */
    public function getRateScale(): Option
    {
        return $this->rateScale;
    }

    /**
     * This shipment's totalNetCharge and totalDutiesTaxesAndFees. Some duties and taxes are only
     * provided if estimated duties and taxes were calculated for this shipment AND duties, taxes
     * and transportation charges are all paid by the same sender's account.
     *
     * Example: 87.5
     *
     * @return Option<float>
     */
    public function getTotalNetCharge(): Option
    {
        return $this->totalNetCharge;
    }

    /**
     * Specifies the total base charge list.
     *
     * Example: 87.5
     *
     * @return Option<float>
     */
    public function getTotalBaseCharge(): Option
    {
        return $this->totalBaseCharge;
    }

    /**
     * Specifies the currency exchange performed on financial amounts for this rate.
     *
     * @return Option<CurrencyExchangeRate>
     */
    public function getCurrencyExchangeRate(): Option
    {
        return $this->currencyExchangeRate;
    }

    /**
     * Sum of billing weight for the shipment.
     *
     * @return Option<Weight1>
     */
    public function getTotalBillingWeight(): Option
    {
        return $this->totalBillingWeight;
    }

    /**
     * Indicate the three-character ISO currency code.
     *
     * Example: USD
     *
     * <a onclick='loadDocReference("currencycodes")'>Click here to see Currency Codes</a>
     *
     * @return Option<string>
     */
    public function getCurrency(): Option
    {
        return $this->currency;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $discounts = None::create();
        $pricingCode = None::create();
        $legDescription = None::create();
        $surcharges = None::create();
        $specialRatingApplied = None::create();
        $taxes = None::create();
        $rateScale = None::create();
        $totalNetCharge = None::create();
        $totalBaseCharge = None::create();
        $currencyExchangeRate = None::create();
        $totalBillingWeight = None::create();
        $currency = None::create();
        if (array_key_exists('totalNetCharge', $data) && is_int($data['totalNetCharge'])) {
            $data['totalNetCharge'] = (float) $data['totalNetCharge'];
        }
        if (array_key_exists('totalBaseCharge', $data) && is_int($data['totalBaseCharge'])) {
            $data['totalBaseCharge'] = (float) $data['totalBaseCharge'];
        }
        if (array_key_exists('discounts', $data) && $data['discounts'] !== null) {
            $discountsRaw = $data['discounts'];
            if (!(is_array($discountsRaw) && array_is_list($discountsRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "discounts" must be list, got %s.', get_debug_type($discountsRaw)),
                );
            }
            $discounts = Some::create(array_map(static function (mixed $value): RateDiscount1 {
                if (!is_array($value)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be object, got %s.', get_debug_type($value)),
                    );
                }
                /** @var array<string, mixed> $valueTyped */
                $valueTyped = $value;

                return RateDiscount1::fromArray($valueTyped);
            }, $discountsRaw));
        }
        if (array_key_exists('pricingCode', $data) && $data['pricingCode'] !== null) {
            $pricingCodeRaw = $data['pricingCode'];
            if (!is_string($pricingCodeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "pricingCode" must be string, got %s.', get_debug_type($pricingCodeRaw)),
                );
            }
            $pricingCode = Some::create($pricingCodeRaw);
        }
        if (array_key_exists('legDescription', $data) && $data['legDescription'] !== null) {
            $legDescriptionRaw = $data['legDescription'];
            if (!is_string($legDescriptionRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "legDescription" must be string, got %s.', get_debug_type($legDescriptionRaw)),
                );
            }
            $legDescription = Some::create($legDescriptionRaw);
        }
        if (array_key_exists('surcharges', $data) && $data['surcharges'] !== null) {
            $surchargesRaw = $data['surcharges'];
            if (!(is_array($surchargesRaw) && array_is_list($surchargesRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "surcharges" must be list, got %s.', get_debug_type($surchargesRaw)),
                );
            }
            $surcharges = Some::create(array_map(static function (mixed $value_1): Surcharge1 {
                if (!is_array($value_1)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be object, got %s.', get_debug_type($value_1)),
                    );
                }
                /** @var array<string, mixed> $value_1Typed */
                $value_1Typed = $value_1;

                return Surcharge1::fromArray($value_1Typed);
            }, $surchargesRaw));
        }
        if (array_key_exists('specialRatingApplied', $data) && $data['specialRatingApplied'] !== null) {
            $specialRatingAppliedRaw = $data['specialRatingApplied'];
            if (!(is_array($specialRatingAppliedRaw) && array_is_list($specialRatingAppliedRaw))) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "specialRatingApplied" must be list, got %s.',
                        get_debug_type($specialRatingAppliedRaw),
                    ),
                );
            }
            $specialRatingApplied = Some::create(array_map(static function (mixed $value_2): string {
                if (!is_string($value_2)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be string, got %s.', get_debug_type($value_2)),
                    );
                }

                return $value_2;
            }, $specialRatingAppliedRaw));
        }
        if (array_key_exists('taxes', $data) && $data['taxes'] !== null) {
            $taxesRaw = $data['taxes'];
            if (!(is_array($taxesRaw) && array_is_list($taxesRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "taxes" must be list, got %s.', get_debug_type($taxesRaw)),
                );
            }
            $taxes = Some::create(array_map(static function (mixed $value_3): Tax1 {
                if (!is_array($value_3)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be object, got %s.', get_debug_type($value_3)),
                    );
                }
                /** @var array<string, mixed> $value_3Typed */
                $value_3Typed = $value_3;

                return Tax1::fromArray($value_3Typed);
            }, $taxesRaw));
        }
        if (array_key_exists('rateScale', $data) && $data['rateScale'] !== null) {
            $rateScaleRaw = $data['rateScale'];
            if (!is_string($rateScaleRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "rateScale" must be string, got %s.', get_debug_type($rateScaleRaw)),
                );
            }
            $rateScale = Some::create($rateScaleRaw);
        }
        if (array_key_exists('totalNetCharge', $data) && $data['totalNetCharge'] !== null) {
            $totalNetChargeRaw = $data['totalNetCharge'];
            if (!(is_float($totalNetChargeRaw) || is_int($totalNetChargeRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "totalNetCharge" must be number, got %s.', get_debug_type($totalNetChargeRaw)),
                );
            }
            $totalNetCharge = Some::create((float) $totalNetChargeRaw);
        }
        if (array_key_exists('totalBaseCharge', $data) && $data['totalBaseCharge'] !== null) {
            $totalBaseChargeRaw = $data['totalBaseCharge'];
            if (!(is_float($totalBaseChargeRaw) || is_int($totalBaseChargeRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "totalBaseCharge" must be number, got %s.', get_debug_type($totalBaseChargeRaw)),
                );
            }
            $totalBaseCharge = Some::create((float) $totalBaseChargeRaw);
        }
        if (array_key_exists('currencyExchangeRate', $data) && $data['currencyExchangeRate'] !== null) {
            $currencyExchangeRateRaw = $data['currencyExchangeRate'];
            if (!is_array($currencyExchangeRateRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "currencyExchangeRate" must be object, got %s.',
                        get_debug_type($currencyExchangeRateRaw),
                    ),
                );
            }
            /** @var array<string, mixed> $currencyExchangeRateRawTyped */
            $currencyExchangeRateRawTyped = $currencyExchangeRateRaw;
            $currencyExchangeRate = Some::create(CurrencyExchangeRate::fromArray($currencyExchangeRateRawTyped));
        }
        if (array_key_exists('totalBillingWeight', $data) && $data['totalBillingWeight'] !== null) {
            $totalBillingWeightRaw = $data['totalBillingWeight'];
            if (!is_array($totalBillingWeightRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "totalBillingWeight" must be object, got %s.',
                        get_debug_type($totalBillingWeightRaw),
                    ),
                );
            }
            /** @var array<string, mixed> $totalBillingWeightRawTyped */
            $totalBillingWeightRawTyped = $totalBillingWeightRaw;
            $totalBillingWeight = Some::create(Weight1::fromArray($totalBillingWeightRawTyped));
        }
        if (array_key_exists('currency', $data) && $data['currency'] !== null) {
            $currencyRaw = $data['currency'];
            if (!is_string($currencyRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "currency" must be string, got %s.', get_debug_type($currencyRaw)),
                );
            }
            $currency = Some::create($currencyRaw);
        }
        $additionalProperties = array_diff_key(
            $data,
            [
                'discounts' => true,
                'pricingCode' => true,
                'legDescription' => true,
                'surcharges' => true,
                'specialRatingApplied' => true,
                'taxes' => true,
                'rateScale' => true,
                'totalNetCharge' => true,
                'totalBaseCharge' => true,
                'currencyExchangeRate' => true,
                'totalBillingWeight' => true,
                'currency' => true,
            ],
        );

        return new self(
            $discounts,
            $pricingCode,
            $legDescription,
            $surcharges,
            $specialRatingApplied,
            $taxes,
            $rateScale,
            $totalNetCharge,
            $totalBaseCharge,
            $currencyExchangeRate,
            $totalBillingWeight,
            $currency,
            $additionalProperties,
        );
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $discountsOption = $this->discounts;
        if ($discountsOption->isDefined()) {
            $discounts = $discountsOption->get();
            $values = [];
            foreach ($discounts as $value) {
                $values[] = $normalizationTarget->model($value);
            }
            $dataArray['discounts'] = $values;
        }
        $pricingCodeOption = $this->pricingCode;
        if ($pricingCodeOption->isDefined()) {
            $pricingCode = $pricingCodeOption->get();
            $dataArray['pricingCode'] = $pricingCode;
        }
        $legDescriptionOption = $this->legDescription;
        if ($legDescriptionOption->isDefined()) {
            $legDescription = $legDescriptionOption->get();
            $dataArray['legDescription'] = $legDescription;
        }
        $surchargesOption = $this->surcharges;
        if ($surchargesOption->isDefined()) {
            $surcharges = $surchargesOption->get();
            $values_1 = [];
            foreach ($surcharges as $value_1) {
                $values_1[] = $normalizationTarget->model($value_1);
            }
            $dataArray['surcharges'] = $values_1;
        }
        $specialRatingAppliedOption = $this->specialRatingApplied;
        if ($specialRatingAppliedOption->isDefined()) {
            $specialRatingApplied = $specialRatingAppliedOption->get();
            $values_2 = [];
            foreach ($specialRatingApplied as $value_2) {
                $values_2[] = $value_2;
            }
            $dataArray['specialRatingApplied'] = $values_2;
        }
        $taxesOption = $this->taxes;
        if ($taxesOption->isDefined()) {
            $taxes = $taxesOption->get();
            $values_3 = [];
            foreach ($taxes as $value_3) {
                $values_3[] = $normalizationTarget->model($value_3);
            }
            $dataArray['taxes'] = $values_3;
        }
        $rateScaleOption = $this->rateScale;
        if ($rateScaleOption->isDefined()) {
            $rateScale = $rateScaleOption->get();
            $dataArray['rateScale'] = $rateScale;
        }
        $totalNetChargeOption = $this->totalNetCharge;
        if ($totalNetChargeOption->isDefined()) {
            $totalNetCharge = $totalNetChargeOption->get();
            $dataArray['totalNetCharge'] = $totalNetCharge;
        }
        $totalBaseChargeOption = $this->totalBaseCharge;
        if ($totalBaseChargeOption->isDefined()) {
            $totalBaseCharge = $totalBaseChargeOption->get();
            $dataArray['totalBaseCharge'] = $totalBaseCharge;
        }
        $currencyExchangeRateOption = $this->currencyExchangeRate;
        if ($currencyExchangeRateOption->isDefined()) {
            $currencyExchangeRate = $currencyExchangeRateOption->get();
            $dataArray['currencyExchangeRate'] = $normalizationTarget->model($currencyExchangeRate);
        }
        $totalBillingWeightOption = $this->totalBillingWeight;
        if ($totalBillingWeightOption->isDefined()) {
            $totalBillingWeight = $totalBillingWeightOption->get();
            $dataArray['totalBillingWeight'] = $normalizationTarget->model($totalBillingWeight);
        }
        $currencyOption = $this->currency;
        if ($currencyOption->isDefined()) {
            $currency = $currencyOption->get();
            $dataArray['currency'] = $currency;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): ShipmentLegRateDetail1Builder
    {
        return new ShipmentLegRateDetail1Builder(
            $this->discounts,
            $this->pricingCode,
            $this->legDescription,
            $this->surcharges,
            $this->specialRatingApplied,
            $this->taxes,
            $this->rateScale,
            $this->totalNetCharge,
            $this->totalBaseCharge,
            $this->currencyExchangeRate,
            $this->totalBillingWeight,
            $this->currency,
            $this->additionalProperties,
        );
    }
}
