<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Override;
use Prefabcortex\FedexRatesAndTransitTimesApi\Exception\MalformedDataException;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\None;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

use function array_diff_key;
use function array_is_list;
use function array_key_exists;
use function array_map;
use function get_debug_type;
use function is_array;
use function is_float;
use function is_int;
use function is_string;
use function sprintf;

final readonly class ShipmentRateDetail implements SelfNormalizingModel
{
    /**
     * @param Option<CurrencyExchangeRate>                                   $currencyExchangeRate
     * @param Option<string>                                                 $currency
     * @param Option<string>                                                 $rateZone
     * @param Option<ShipmentRateDetailRatingBasis|UnknownEnumValue<string>> $ratingBasis
     * @param Option<string>                                                 $pricingCode
     * @param Option<float>                                                  $totalFreightDiscount
     * @param Option<list<string>>                                           $specialRatingApplied
     * @param Option<float>                                                  $totalSurcharges
     * @param Option<list<RateDiscount>>                                     $freightDiscount
     * @param Option<float>                                                  $fuelSurchargePercent
     * @param Option<Weight1>                                                $totalBillingWeight
     * @param Option<Weight1>                                                $totalDimWeight
     * @param Option<int>                                                    $dimDivisor
     * @param Option<list<Surcharge>>                                        $surCharges
     * @param Option<list<Tax>>                                              $taxes
     * @param array<int|string, mixed>                                       $additionalProperties
     */
    public function __construct(
        private Option $currencyExchangeRate,
        private Option $currency,
        private Option $rateZone,
        private Option $ratingBasis,
        private Option $pricingCode,
        private Option $totalFreightDiscount,
        private Option $specialRatingApplied,
        private Option $totalSurcharges,
        private Option $freightDiscount,
        private Option $fuelSurchargePercent,
        private Option $totalBillingWeight,
        private Option $totalDimWeight,
        private Option $dimDivisor,
        private Option $surCharges,
        private Option $taxes,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): ShipmentRateDetailBuilder
    {
        return new ShipmentRateDetailBuilder(
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            [],
        );
    }

    /**
     * Specifies the currency exchange performed on financial amounts for this rate.
     *
     * @return Option<CurrencyExchangeRate>
     */
    public function getCurrencyExchangeRate(): Option
    {
        return $this->currencyExchangeRate;
    }

    /**
     * Indicates the currency associated with the amount.
     *
     * @return Option<string>
     */
    public function getCurrency(): Option
    {
        return $this->currency;
    }

    /**
     * Indicates the rate zone used.
     *
     * @return Option<string>
     */
    public function getRateZone(): Option
    {
        return $this->rateZone;
    }

    /**
     * Allows clients to determine whether to add charges at the package level when Per Piece Rating
     * details are returned.
     *
     * <ul><li>SHIPMENT_WEIGHT_BASED - Indicates shipment weight is used to calculate the rate.</li>
     *
     * <li>FLAT_RATE_PER_PAK - Indicates shipment is rated based on number of packs, weight would be
     * considered for overweight surcharge but not for calculating shipment rate.</li>
     *
     * <li>PACK_WEIGHT_BASED - Indicates individual package weight would be rated and aggregated to
     * get shipment rate weight.</li></ul> Example : SHIPMENT_WEIGHT_BASED.
     *
     * @return Option<ShipmentRateDetailRatingBasis|UnknownEnumValue<string>>
     */
    public function getRatingBasis(): Option
    {
        return $this->ratingBasis;
    }

    /**
     * Indicates the type of pricing code.
     *
     * @return Option<string>
     */
    public function getPricingCode(): Option
    {
        return $this->pricingCode;
    }

    /**
     * Indicates the total discounts used in the rate calculation. Example: 856.32.
     *
     * @return Option<float>
     */
    public function getTotalFreightDiscount(): Option
    {
        return $this->totalFreightDiscount;
    }

    /**
     * Indicates which special rating cases applied to this shipment.
     *
     * @return Option<list<string>>
     */
    public function getSpecialRatingApplied(): Option
    {
        return $this->specialRatingApplied;
    }

    /**
     * This is sum of all surcharges on the package. Example: 586.25.
     *
     * @return Option<float>
     */
    public function getTotalSurcharges(): Option
    {
        return $this->totalSurcharges;
    }

    /**
     * This is total discount used in the rate calculation.
     *
     * <a onclick='loadDocReference("discounts")'>Click here to see Discounts</a>
     *
     * @return Option<list<RateDiscount>>
     */
    public function getFreightDiscount(): Option
    {
        return $this->freightDiscount;
    }

    /**
     * This is fuel surcharge percentage.
     *
     * @return Option<float>
     */
    public function getFuelSurchargePercent(): Option
    {
        return $this->fuelSurchargePercent;
    }

    /**
     * This is total of billing weight for the shipment.
     *
     * @return Option<Weight1>
     */
    public function getTotalBillingWeight(): Option
    {
        return $this->totalBillingWeight;
    }

    /**
     * This is total of dimensional weight for the shipment.
     *
     * @return Option<Weight1>
     */
    public function getTotalDimWeight(): Option
    {
        return $this->totalDimWeight;
    }

    /**
     * Identifies the type of divisor that was applied.
     *
     * Example: 10
     *
     * @return Option<int>
     */
    public function getDimDivisor(): Option
    {
        return $this->dimDivisor;
    }

    /**
     * Indicates the surcharges applied to this shipment.
     *
     * @return Option<list<Surcharge>>
     */
    public function getSurCharges(): Option
    {
        return $this->surCharges;
    }

    /**
     * List of taxes.
     *
     * @return Option<list<Tax>>
     */
    public function getTaxes(): Option
    {
        return $this->taxes;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $currencyExchangeRate = None::create();
        $currency = None::create();
        $rateZone = None::create();
        $ratingBasis = None::create();
        $pricingCode = None::create();
        $totalFreightDiscount = None::create();
        $specialRatingApplied = None::create();
        $totalSurcharges = None::create();
        $freightDiscount = None::create();
        $fuelSurchargePercent = None::create();
        $totalBillingWeight = None::create();
        $totalDimWeight = None::create();
        $dimDivisor = None::create();
        $surCharges = None::create();
        $taxes = None::create();
        if (array_key_exists('totalFreightDiscount', $data) && is_int($data['totalFreightDiscount'])) {
            $data['totalFreightDiscount'] = (float) $data['totalFreightDiscount'];
        }
        if (array_key_exists('totalSurcharges', $data) && is_int($data['totalSurcharges'])) {
            $data['totalSurcharges'] = (float) $data['totalSurcharges'];
        }
        if (array_key_exists('fuelSurchargePercent', $data) && is_int($data['fuelSurchargePercent'])) {
            $data['fuelSurchargePercent'] = (float) $data['fuelSurchargePercent'];
        }
        if (array_key_exists('currencyExchangeRate', $data) && $data['currencyExchangeRate'] !== null) {
            $currencyExchangeRateRaw = $data['currencyExchangeRate'];
            if (!is_array($currencyExchangeRateRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "currencyExchangeRate" must be object, got %s.',
                        get_debug_type($currencyExchangeRateRaw),
                    ),
                );
            }
            /** @var array<string, mixed> $currencyExchangeRateRawTyped */
            $currencyExchangeRateRawTyped = $currencyExchangeRateRaw;
            $currencyExchangeRate = Some::create(CurrencyExchangeRate::fromArray($currencyExchangeRateRawTyped));
        }
        if (array_key_exists('currency', $data) && $data['currency'] !== null) {
            $currencyRaw = $data['currency'];
            if (!is_string($currencyRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "currency" must be string, got %s.', get_debug_type($currencyRaw)),
                );
            }
            $currency = Some::create($currencyRaw);
        }
        if (array_key_exists('rateZone', $data) && $data['rateZone'] !== null) {
            $rateZoneRaw = $data['rateZone'];
            if (!is_string($rateZoneRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "rateZone" must be string, got %s.', get_debug_type($rateZoneRaw)),
                );
            }
            $rateZone = Some::create($rateZoneRaw);
        }
        if (array_key_exists('ratingBasis', $data) && $data['ratingBasis'] !== null) {
            $ratingBasisRaw = $data['ratingBasis'];
            if (!is_string($ratingBasisRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "ratingBasis" must be string, got %s.', get_debug_type($ratingBasisRaw)),
                );
            }
            $ratingBasis = Some::create(
                ShipmentRateDetailRatingBasis::tryFrom($ratingBasisRaw) ?? UnknownEnumValue::of($ratingBasisRaw),
            );
        }
        if (array_key_exists('pricingCode', $data) && $data['pricingCode'] !== null) {
            $pricingCodeRaw = $data['pricingCode'];
            if (!is_string($pricingCodeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "pricingCode" must be string, got %s.', get_debug_type($pricingCodeRaw)),
                );
            }
            $pricingCode = Some::create($pricingCodeRaw);
        }
        if (array_key_exists('totalFreightDiscount', $data) && $data['totalFreightDiscount'] !== null) {
            $totalFreightDiscountRaw = $data['totalFreightDiscount'];
            if (!(is_float($totalFreightDiscountRaw) || is_int($totalFreightDiscountRaw))) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "totalFreightDiscount" must be number, got %s.',
                        get_debug_type($totalFreightDiscountRaw),
                    ),
                );
            }
            $totalFreightDiscount = Some::create((float) $totalFreightDiscountRaw);
        }
        if (array_key_exists('specialRatingApplied', $data) && $data['specialRatingApplied'] !== null) {
            $specialRatingAppliedRaw = $data['specialRatingApplied'];
            if (!(is_array($specialRatingAppliedRaw) && array_is_list($specialRatingAppliedRaw))) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "specialRatingApplied" must be list, got %s.',
                        get_debug_type($specialRatingAppliedRaw),
                    ),
                );
            }
            $specialRatingApplied = Some::create(array_map(static function (mixed $value): string {
                if (!is_string($value)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be string, got %s.', get_debug_type($value)),
                    );
                }

                return $value;
            }, $specialRatingAppliedRaw));
        }
        if (array_key_exists('totalSurcharges', $data) && $data['totalSurcharges'] !== null) {
            $totalSurchargesRaw = $data['totalSurcharges'];
            if (!(is_float($totalSurchargesRaw) || is_int($totalSurchargesRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "totalSurcharges" must be number, got %s.', get_debug_type($totalSurchargesRaw)),
                );
            }
            $totalSurcharges = Some::create((float) $totalSurchargesRaw);
        }
        if (array_key_exists('freightDiscount', $data) && $data['freightDiscount'] !== null) {
            $freightDiscountRaw = $data['freightDiscount'];
            if (!(is_array($freightDiscountRaw) && array_is_list($freightDiscountRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "freightDiscount" must be list, got %s.', get_debug_type($freightDiscountRaw)),
                );
            }
            $freightDiscount = Some::create(array_map(static function (mixed $value_1): RateDiscount {
                if (!is_array($value_1)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be object, got %s.', get_debug_type($value_1)),
                    );
                }
                /** @var array<string, mixed> $value_1Typed */
                $value_1Typed = $value_1;

                return RateDiscount::fromArray($value_1Typed);
            }, $freightDiscountRaw));
        }
        if (array_key_exists('fuelSurchargePercent', $data) && $data['fuelSurchargePercent'] !== null) {
            $fuelSurchargePercentRaw = $data['fuelSurchargePercent'];
            if (!(is_float($fuelSurchargePercentRaw) || is_int($fuelSurchargePercentRaw))) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "fuelSurchargePercent" must be number, got %s.',
                        get_debug_type($fuelSurchargePercentRaw),
                    ),
                );
            }
            $fuelSurchargePercent = Some::create((float) $fuelSurchargePercentRaw);
        }
        if (array_key_exists('totalBillingWeight', $data) && $data['totalBillingWeight'] !== null) {
            $totalBillingWeightRaw = $data['totalBillingWeight'];
            if (!is_array($totalBillingWeightRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "totalBillingWeight" must be object, got %s.',
                        get_debug_type($totalBillingWeightRaw),
                    ),
                );
            }
            /** @var array<string, mixed> $totalBillingWeightRawTyped */
            $totalBillingWeightRawTyped = $totalBillingWeightRaw;
            $totalBillingWeight = Some::create(Weight1::fromArray($totalBillingWeightRawTyped));
        }
        if (array_key_exists('totalDimWeight', $data) && $data['totalDimWeight'] !== null) {
            $totalDimWeightRaw = $data['totalDimWeight'];
            if (!is_array($totalDimWeightRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "totalDimWeight" must be object, got %s.', get_debug_type($totalDimWeightRaw)),
                );
            }
            /** @var array<string, mixed> $totalDimWeightRawTyped */
            $totalDimWeightRawTyped = $totalDimWeightRaw;
            $totalDimWeight = Some::create(Weight1::fromArray($totalDimWeightRawTyped));
        }
        if (array_key_exists('dimDivisor', $data) && $data['dimDivisor'] !== null) {
            $dimDivisorRaw = $data['dimDivisor'];
            if (!is_int($dimDivisorRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "dimDivisor" must be int, got %s.', get_debug_type($dimDivisorRaw)),
                );
            }
            $dimDivisor = Some::create($dimDivisorRaw);
        }
        if (array_key_exists('surCharges', $data) && $data['surCharges'] !== null) {
            $surChargesRaw = $data['surCharges'];
            if (!(is_array($surChargesRaw) && array_is_list($surChargesRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "surCharges" must be list, got %s.', get_debug_type($surChargesRaw)),
                );
            }
            $surCharges = Some::create(array_map(static function (mixed $value_2): Surcharge {
                if (!is_array($value_2)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be object, got %s.', get_debug_type($value_2)),
                    );
                }
                /** @var array<string, mixed> $value_2Typed */
                $value_2Typed = $value_2;

                return Surcharge::fromArray($value_2Typed);
            }, $surChargesRaw));
        }
        if (array_key_exists('taxes', $data) && $data['taxes'] !== null) {
            $taxesRaw = $data['taxes'];
            if (!(is_array($taxesRaw) && array_is_list($taxesRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "taxes" must be list, got %s.', get_debug_type($taxesRaw)),
                );
            }
            $taxes = Some::create(array_map(static function (mixed $value_3): Tax {
                if (!is_array($value_3)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be object, got %s.', get_debug_type($value_3)),
                    );
                }
                /** @var array<string, mixed> $value_3Typed */
                $value_3Typed = $value_3;

                return Tax::fromArray($value_3Typed);
            }, $taxesRaw));
        }
        $additionalProperties = array_diff_key(
            $data,
            [
                'currencyExchangeRate' => true,
                'currency' => true,
                'rateZone' => true,
                'ratingBasis' => true,
                'pricingCode' => true,
                'totalFreightDiscount' => true,
                'specialRatingApplied' => true,
                'totalSurcharges' => true,
                'freightDiscount' => true,
                'fuelSurchargePercent' => true,
                'totalBillingWeight' => true,
                'totalDimWeight' => true,
                'dimDivisor' => true,
                'surCharges' => true,
                'taxes' => true,
            ],
        );

        return new self(
            $currencyExchangeRate,
            $currency,
            $rateZone,
            $ratingBasis,
            $pricingCode,
            $totalFreightDiscount,
            $specialRatingApplied,
            $totalSurcharges,
            $freightDiscount,
            $fuelSurchargePercent,
            $totalBillingWeight,
            $totalDimWeight,
            $dimDivisor,
            $surCharges,
            $taxes,
            $additionalProperties,
        );
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $currencyExchangeRateOption = $this->currencyExchangeRate;
        if ($currencyExchangeRateOption->isDefined()) {
            $currencyExchangeRate = $currencyExchangeRateOption->get();
            $dataArray['currencyExchangeRate'] = $normalizationTarget->model($currencyExchangeRate);
        }
        $currencyOption = $this->currency;
        if ($currencyOption->isDefined()) {
            $currency = $currencyOption->get();
            $dataArray['currency'] = $currency;
        }
        $rateZoneOption = $this->rateZone;
        if ($rateZoneOption->isDefined()) {
            $rateZone = $rateZoneOption->get();
            $dataArray['rateZone'] = $rateZone;
        }
        $ratingBasisOption = $this->ratingBasis;
        if ($ratingBasisOption->isDefined()) {
            $ratingBasis = $ratingBasisOption->get();
            $dataArray['ratingBasis'] = $ratingBasis->value;
        }
        $pricingCodeOption = $this->pricingCode;
        if ($pricingCodeOption->isDefined()) {
            $pricingCode = $pricingCodeOption->get();
            $dataArray['pricingCode'] = $pricingCode;
        }
        $totalFreightDiscountOption = $this->totalFreightDiscount;
        if ($totalFreightDiscountOption->isDefined()) {
            $totalFreightDiscount = $totalFreightDiscountOption->get();
            $dataArray['totalFreightDiscount'] = $totalFreightDiscount;
        }
        $specialRatingAppliedOption = $this->specialRatingApplied;
        if ($specialRatingAppliedOption->isDefined()) {
            $specialRatingApplied = $specialRatingAppliedOption->get();
            $values = [];
            foreach ($specialRatingApplied as $value) {
                $values[] = $value;
            }
            $dataArray['specialRatingApplied'] = $values;
        }
        $totalSurchargesOption = $this->totalSurcharges;
        if ($totalSurchargesOption->isDefined()) {
            $totalSurcharges = $totalSurchargesOption->get();
            $dataArray['totalSurcharges'] = $totalSurcharges;
        }
        $freightDiscountOption = $this->freightDiscount;
        if ($freightDiscountOption->isDefined()) {
            $freightDiscount = $freightDiscountOption->get();
            $values_1 = [];
            foreach ($freightDiscount as $value_1) {
                $values_1[] = $normalizationTarget->model($value_1);
            }
            $dataArray['freightDiscount'] = $values_1;
        }
        $fuelSurchargePercentOption = $this->fuelSurchargePercent;
        if ($fuelSurchargePercentOption->isDefined()) {
            $fuelSurchargePercent = $fuelSurchargePercentOption->get();
            $dataArray['fuelSurchargePercent'] = $fuelSurchargePercent;
        }
        $totalBillingWeightOption = $this->totalBillingWeight;
        if ($totalBillingWeightOption->isDefined()) {
            $totalBillingWeight = $totalBillingWeightOption->get();
            $dataArray['totalBillingWeight'] = $normalizationTarget->model($totalBillingWeight);
        }
        $totalDimWeightOption = $this->totalDimWeight;
        if ($totalDimWeightOption->isDefined()) {
            $totalDimWeight = $totalDimWeightOption->get();
            $dataArray['totalDimWeight'] = $normalizationTarget->model($totalDimWeight);
        }
        $dimDivisorOption = $this->dimDivisor;
        if ($dimDivisorOption->isDefined()) {
            $dimDivisor = $dimDivisorOption->get();
            $dataArray['dimDivisor'] = $dimDivisor;
        }
        $surChargesOption = $this->surCharges;
        if ($surChargesOption->isDefined()) {
            $surCharges = $surChargesOption->get();
            $values_2 = [];
            foreach ($surCharges as $value_2) {
                $values_2[] = $normalizationTarget->model($value_2);
            }
            $dataArray['surCharges'] = $values_2;
        }
        $taxesOption = $this->taxes;
        if ($taxesOption->isDefined()) {
            $taxes = $taxesOption->get();
            $values_3 = [];
            foreach ($taxes as $value_3) {
                $values_3[] = $normalizationTarget->model($value_3);
            }
            $dataArray['taxes'] = $values_3;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): ShipmentRateDetailBuilder
    {
        return new ShipmentRateDetailBuilder(
            $this->currencyExchangeRate,
            $this->currency,
            $this->rateZone,
            $this->ratingBasis,
            $this->pricingCode,
            $this->totalFreightDiscount,
            $this->specialRatingApplied,
            $this->totalSurcharges,
            $this->freightDiscount,
            $this->fuelSurchargePercent,
            $this->totalBillingWeight,
            $this->totalDimWeight,
            $this->dimDivisor,
            $this->surCharges,
            $this->taxes,
            $this->additionalProperties,
        );
    }
}
