<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

/**
 * Builds a {@see ShipmentSpecialServicesRequestedShipmentCODDetail}.
 */
final class ShipmentSpecialServicesRequestedShipmentCODDetailBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<CODTransportationChargesDetail>                                         $addTransportationChargesDetail
     * @param Option<Party2>                                                                 $codRecipient
     * @param Option<string>                                                                 $remitToName
     * @param Option<ShipmentCODDetailCodCollectionType|UnknownEnumValue<string>>            $codCollectionType
     * @param Option<ContactAndAddress>                                                      $financialInstitutionContactAndAddress
     * @param Option<ShipmentCODDetailReturnReferenceIndicatorType|UnknownEnumValue<string>> $returnReferenceIndicatorType
     * @param array<int|string, mixed>                                                       $additionalProperties
     */
    public function __construct(
        private Option $addTransportationChargesDetail,
        private Option $codRecipient,
        private Option $remitToName,
        private Option $codCollectionType,
        private Option $financialInstitutionContactAndAddress,
        private Option $returnReferenceIndicatorType,
        private array $additionalProperties,
    ) {
    }

    /**
     * These are COD Transportation Charges Detail.
     */
    public function setAddTransportationChargesDetail(
        CODTransportationChargesDetail $addTransportationChargesDetail,
    ): self {
        $this->addTransportationChargesDetail = Some::create($addTransportationChargesDetail);

        return $this;
    }

    /**
     * Indicate the party to a transaction including the physical address, contact information and
     * account number information.
     */
    public function setCodRecipient(Party2 $codRecipient): self
    {
        $this->codRecipient = Some::create($codRecipient);

        return $this;
    }

    /**
     * Specifies the name of person or company receiving the secured or unsecured payment.
     *
     * Example: FedEx
     */
    public function setRemitToName(string $remitToName): self
    {
        $this->remitToName = Some::create($remitToName);

        return $this;
    }

    /**
     * Indicate the type of funds FedEx should collect upon shipment delivery.
     */
    public function setCodCollectionType(ShipmentCODDetailCodCollectionType $codCollectionType): self
    {
        $this->codCollectionType = Some::create($codCollectionType);

        return $this;
    }

    /**
     * Specify the contact and address details of a location.
     */
    public function setFinancialInstitutionContactAndAddress(
        ContactAndAddress $financialInstitutionContactAndAddress,
    ): self {
        $this->financialInstitutionContactAndAddress = Some::create($financialInstitutionContactAndAddress);

        return $this;
    }

    /**
     * Indicate the type of reference information to include on the COD return shipping label.
     */
    public function setReturnReferenceIndicatorType(
        ShipmentCODDetailReturnReferenceIndicatorType $returnReferenceIndicatorType,
    ): self {
        $this->returnReferenceIndicatorType = Some::create($returnReferenceIndicatorType);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): ShipmentSpecialServicesRequestedShipmentCODDetail
    {
        return new ShipmentSpecialServicesRequestedShipmentCODDetail(
            $this->addTransportationChargesDetail,
            $this->codRecipient,
            $this->remitToName,
            $this->codCollectionType,
            $this->financialInstitutionContactAndAddress,
            $this->returnReferenceIndicatorType,
            $this->additionalProperties,
        );
    }
}
