<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Override;
use Prefabcortex\FedexRatesAndTransitTimesApi\Exception\MalformedDataException;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\None;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_string;
use function sprintf;

final readonly class SmartPostInfoDetail implements SelfNormalizingModel
{
    /**
     * @param Option<SmartPostInfoDetailAncillaryEndorsement|UnknownEnumValue<string>> $ancillaryEndorsement
     * @param Option<string>                                                           $hubId
     * @param Option<SmartPostInfoDetailIndicia|UnknownEnumValue<string>>              $indicia
     * @param Option<SmartPostInfoDetailSpecialServices|UnknownEnumValue<string>>      $specialServices
     * @param array<int|string, mixed>                                                 $additionalProperties
     */
    public function __construct(
        private Option $ancillaryEndorsement,
        private Option $hubId,
        private Option $indicia,
        private Option $specialServices,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): SmartPostInfoDetailBuilder
    {
        return new SmartPostInfoDetailBuilder(None::create(), None::create(), None::create(), None::create(), []);
    }

    /**
     * Indicate the type of ancillary endorsement. Is required for Presorted Standard but not for
     * returns or parcel select. Note not all are usable for all ancillary endorsements.
     *
     * For more information, refer to the <a href =
     * 'https://www.fedex.com/en-us/shipping/fedex-smartpost/rates-zones.html' target='_blank'>FedEx
     * SmartPost®</a>.
     *
     * @return Option<SmartPostInfoDetailAncillaryEndorsement|UnknownEnumValue<string>>
     */
    public function getAncillaryEndorsement(): Option
    {
        return $this->ancillaryEndorsement;
    }

    /**
     * Specify the four-digit numeric Hub ID value used during rate quote for smartport shipments.
     *
     * <a onclick='loadDocReference("smartposthubids")'>Click here to see Hub Ids</a>
     *
     * @return Option<string>
     */
    public function getHubId(): Option
    {
        return $this->hubId;
    }

    /**
     * Specify the indicia type.
     *
     * Available options include:<ul><li>MEDIA_MAIL</li><li>PARCEL_SELECT (1 LB through 70
     * LB)</li><li>PRESORTED_BOUND_PRINTED_MATTER</li><li>PRESORTED_STANDARD (less than 1
     * LB)</li><li>PARCEL_RETURN</li></ul>
     *
     * @return Option<SmartPostInfoDetailIndicia|UnknownEnumValue<string>>
     */
    public function getIndicia(): Option
    {
        return $this->indicia;
    }

    /**
     * Specify the special handling associated with Smartpost Shipment.
     *
     * <a onclick='loadDocReference("shipmentlevelspecialservicetypes")'>Click here to see Shipment
     * Level Special Service Types</a>
     *
     * @return Option<SmartPostInfoDetailSpecialServices|UnknownEnumValue<string>>
     */
    public function getSpecialServices(): Option
    {
        return $this->specialServices;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $ancillaryEndorsement = None::create();
        $hubId = None::create();
        $indicia = None::create();
        $specialServices = None::create();
        if (array_key_exists('ancillaryEndorsement', $data) && $data['ancillaryEndorsement'] !== null) {
            $ancillaryEndorsementRaw = $data['ancillaryEndorsement'];
            if (!is_string($ancillaryEndorsementRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "ancillaryEndorsement" must be string, got %s.',
                        get_debug_type($ancillaryEndorsementRaw),
                    ),
                );
            }
            $ancillaryEndorsement = Some::create(
                SmartPostInfoDetailAncillaryEndorsement::tryFrom($ancillaryEndorsementRaw)
                    ?? UnknownEnumValue::of($ancillaryEndorsementRaw),
            );
        }
        if (array_key_exists('hubId', $data) && $data['hubId'] !== null) {
            $hubIdRaw = $data['hubId'];
            if (!is_string($hubIdRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "hubId" must be string, got %s.', get_debug_type($hubIdRaw)),
                );
            }
            $hubId = Some::create($hubIdRaw);
        }
        if (array_key_exists('indicia', $data) && $data['indicia'] !== null) {
            $indiciaRaw = $data['indicia'];
            if (!is_string($indiciaRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "indicia" must be string, got %s.', get_debug_type($indiciaRaw)),
                );
            }
            $indicia = Some::create(
                SmartPostInfoDetailIndicia::tryFrom($indiciaRaw) ?? UnknownEnumValue::of($indiciaRaw),
            );
        }
        if (array_key_exists('specialServices', $data) && $data['specialServices'] !== null) {
            $specialServicesRaw = $data['specialServices'];
            if (!is_string($specialServicesRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "specialServices" must be string, got %s.', get_debug_type($specialServicesRaw)),
                );
            }
            $specialServices = Some::create(
                SmartPostInfoDetailSpecialServices::tryFrom($specialServicesRaw)
                    ?? UnknownEnumValue::of($specialServicesRaw),
            );
        }
        $additionalProperties = array_diff_key(
            $data,
            ['ancillaryEndorsement' => true, 'hubId' => true, 'indicia' => true, 'specialServices' => true],
        );

        return new self($ancillaryEndorsement, $hubId, $indicia, $specialServices, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $ancillaryEndorsementOption = $this->ancillaryEndorsement;
        if ($ancillaryEndorsementOption->isDefined()) {
            $ancillaryEndorsement = $ancillaryEndorsementOption->get();
            $dataArray['ancillaryEndorsement'] = $ancillaryEndorsement->value;
        }
        $hubIdOption = $this->hubId;
        if ($hubIdOption->isDefined()) {
            $hubId = $hubIdOption->get();
            $dataArray['hubId'] = $hubId;
        }
        $indiciaOption = $this->indicia;
        if ($indiciaOption->isDefined()) {
            $indicia = $indiciaOption->get();
            $dataArray['indicia'] = $indicia->value;
        }
        $specialServicesOption = $this->specialServices;
        if ($specialServicesOption->isDefined()) {
            $specialServices = $specialServicesOption->get();
            $dataArray['specialServices'] = $specialServices->value;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): SmartPostInfoDetailBuilder
    {
        return new SmartPostInfoDetailBuilder(
            $this->ancillaryEndorsement,
            $this->hubId,
            $this->indicia,
            $this->specialServices,
            $this->additionalProperties,
        );
    }
}
