<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Override;
use Prefabcortex\FedexRatesAndTransitTimesApi\Exception\MalformedDataException;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_string;
use function sprintf;

final readonly class SmsDetail implements SelfNormalizingModel
{
    /** @param array<int|string, mixed> $additionalProperties */
    public function __construct(
        private string $phoneNumber,
        private string $phoneNumberCountryCode,
        private array $additionalProperties,
    ) {
    }

    public static function builder(string $phoneNumber, string $phoneNumberCountryCode): SmsDetailBuilder
    {
        return new SmsDetailBuilder($phoneNumber, $phoneNumberCountryCode, []);
    }

    public function getPhoneNumber(): string
    {
        return $this->phoneNumber;
    }

    public function getPhoneNumberCountryCode(): string
    {
        return $this->phoneNumberCountryCode;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $phoneNumber = null;
        $phoneNumberCountryCode = null;
        if (array_key_exists('phoneNumber', $data)) {
            $phoneNumberRaw = $data['phoneNumber'];
            if (!is_string($phoneNumberRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "phoneNumber" must be string, got %s.', get_debug_type($phoneNumberRaw)),
                );
            }
            $phoneNumber = $phoneNumberRaw;
        }
        if (array_key_exists('phoneNumberCountryCode', $data)) {
            $phoneNumberCountryCodeRaw = $data['phoneNumberCountryCode'];
            if (!is_string($phoneNumberCountryCodeRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "phoneNumberCountryCode" must be string, got %s.',
                        get_debug_type($phoneNumberCountryCodeRaw),
                    ),
                );
            }
            $phoneNumberCountryCode = $phoneNumberCountryCodeRaw;
        }
        $additionalProperties = array_diff_key($data, ['phoneNumber' => true, 'phoneNumberCountryCode' => true]);
        if ($phoneNumber === null) {
            throw new MalformedDataException('Required property "phoneNumber" is missing from the document.');
        }
        if ($phoneNumberCountryCode === null) {
            throw new MalformedDataException(
                'Required property "phoneNumberCountryCode" is missing from the document.',
            );
        }

        return new self($phoneNumber, $phoneNumberCountryCode, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $dataArray['phoneNumber'] = $this->phoneNumber;
        $dataArray['phoneNumberCountryCode'] = $this->phoneNumberCountryCode;
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): SmsDetailBuilder
    {
        return new SmsDetailBuilder($this->phoneNumber, $this->phoneNumberCountryCode, $this->additionalProperties);
    }
}
