<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

/**
 * Builds a {@see Surcharge1}.
 */
final class Surcharge1Builder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<float>            $amount
     * @param Option<string>           $level
     * @param Option<string>           $name
     * @param Option<string>           $description
     * @param Option<string>           $type
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private Option $amount,
        private Option $level,
        private Option $name,
        private Option $description,
        private Option $type,
        private array $additionalProperties,
    ) {
    }

    /**
     * Identifies the total amount of the shipment-level fees and taxes that are not based on
     * transportation charges or commodity-level estimated duties and taxes.
     *
     * Example: 87.5
     */
    public function setAmount(float $amount): self
    {
        $this->amount = Some::create($amount);

        return $this;
    }

    /**
     * The level of surcharge.
     *
     * Example: level
     */
    public function setLevel(string $level): self
    {
        $this->level = Some::create($level);

        return $this;
    }

    /**
     * The localized name of the surcharge.
     *
     * Example: name
     */
    public function setName(string $name): self
    {
        $this->name = Some::create($name);

        return $this;
    }

    /**
     * The description of the surcharge.
     *
     * Example: description
     */
    public function setDescription(string $description): self
    {
        $this->description = Some::create($description);

        return $this;
    }

    /**
     * The type of surcharge.
     *
     * Example: type
     */
    public function setType(string $type): self
    {
        $this->type = Some::create($type);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): Surcharge1
    {
        return new Surcharge1(
            $this->amount,
            $this->level,
            $this->name,
            $this->description,
            $this->type,
            $this->additionalProperties,
        );
    }
}
