<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

/**
 * Builds a {@see Tax1}.
 */
final class Tax1Builder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<float>            $amount
     * @param Option<string>           $name
     * @param Option<string>           $description
     * @param Option<string>           $type
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private Option $amount,
        private Option $name,
        private Option $description,
        private Option $type,
        private array $additionalProperties,
    ) {
    }

    /**
     * Specifies the list of tax amounts.
     *
     * Example : 87.5
     */
    public function setAmount(float $amount): self
    {
        $this->amount = Some::create($amount);

        return $this;
    }

    /**
     * Specifies the localized name of the tax.
     *
     * Example: Name
     */
    public function setName(string $name): self
    {
        $this->name = Some::create($name);

        return $this;
    }

    /**
     * Specifies the description of the Surcharge/Tax.
     *
     * Example: description
     */
    public function setDescription(string $description): self
    {
        $this->description = Some::create($description);

        return $this;
    }

    /**
     * Specifies the type of Surcharge/Tax.
     *
     * Example: type
     */
    public function setType(string $type): self
    {
        $this->type = Some::create($type);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): Tax1
    {
        return new Tax1($this->amount, $this->name, $this->description, $this->type, $this->additionalProperties);
    }
}
