<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Model;

use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Option;
use Prefabcortex\FedexRatesAndTransitTimesApi\Optional\Some;

/**
 * Builds a {@see UploadDocumentReferenceDetail}.
 */
final class UploadDocumentReferenceDetailBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<UploadDocumentReferenceDetailDocumentType|UnknownEnumValue<string>> $documentType
     * @param Option<string>                                                             $customerReference
     * @param Option<string>                                                             $description
     * @param Option<string>                                                             $documentId
     * @param array<int|string, mixed>                                                   $additionalProperties
     */
    public function __construct(
        private Option $documentType,
        private Option $customerReference,
        private Option $description,
        private Option $documentId,
        private array $additionalProperties,
    ) {
    }

    /**
     * These are the type of document specified in the PendingShipment request.
     */
    public function setDocumentType(UploadDocumentReferenceDetailDocumentType $documentType): self
    {
        $this->documentType = Some::create($documentType);

        return $this;
    }

    /**
     * Customer Reference.
     */
    public function setCustomerReference(string $customerReference): self
    {
        $this->customerReference = Some::create($customerReference);

        return $this;
    }

    /**
     * Indicate description of the shipping documents produced for the shipper by FedEx (see
     * ShippingDocumentSpecification) which should be copied back to the shipper in the shipment
     * result data.
     */
    public function setDescription(string $description): self
    {
        $this->description = Some::create($description);

        return $this;
    }

    /**
     * Specify the document ID for the uploaded document.
     */
    public function setDocumentId(string $documentId): self
    {
        $this->documentId = Some::create($documentId);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): UploadDocumentReferenceDetail
    {
        return new UploadDocumentReferenceDetail(
            $this->documentType,
            $this->customerReference,
            $this->description,
            $this->documentId,
            $this->additionalProperties,
        );
    }
}
