<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Exception;

use Override;
use Prefabcortex\FedexRatesAndTransitTimesApi\Http\ErrorMessage;
use Prefabcortex\FedexRatesAndTransitTimesApi\Model\ErrorResponseVO401;
use Psr\Http\Message\ResponseInterface;

final class RateAndTransitTimesUnauthorizedException extends UnauthorizedException
{
    public function __construct(
        private readonly ErrorResponseVO401 $errorResponseVO401,
        private readonly ResponseInterface $response,
        private readonly string $rawResponse,
    ) {
        parent::__construct(ErrorMessage::describe($rawResponse, 'Unauthorized'));
    }

    public function getErrorResponseVO401(): ErrorResponseVO401
    {
        return $this->errorResponseVO401;
    }

    #[Override]
    public function getResponse(): ResponseInterface
    {
        return $this->response;
    }

    #[Override]
    public function getRawResponse(): string
    {
        return $this->rawResponse;
    }
}
