<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Validator;

use Override;
use Prefabcortex\FedexRatesAndTransitTimesApi\Model\BatteryClassificationDetail;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;

/**
 * The rules a document for {@see BatteryClassificationDetail} has to satisfy.
 */
final class BatteryClassificationDetailConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'material' => new Optional([...BatteryClassificationDetailMaterialConstraint::constraints()]),
                'regulatorySubType' => new Optional([
                    ...BatteryClassificationDetailRegulatorySubTypeConstraint::constraints(),
                ]),
                'packing' => new Optional([...BatteryClassificationDetailPackingConstraint::constraints()]),
            ], null, null, true),
        ];
    }
}
