<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Validator;

use Override;
use Prefabcortex\FedexRatesAndTransitTimesApi\Model\BrokerDetailRateReply;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Required;

/**
 * The rules a document for {@see BrokerDetailRateReply} has to satisfy.
 */
final class BrokerDetailRateReplyConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'broker' => new Required([new NotNull(), ...BrokerDetailBrokerRateReplyConstraint::constraints()]),
                'type' => new Required([...BrokerDetailRateReplyTypeConstraint::constraints()]),
                'brokerAddress' => new Optional([new NotNull(), ...BrokeraddressConstraint::constraints()]),
            ], null, null, true),
        ];
    }
}
