<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Validator;

use Override;
use Prefabcortex\FedexRatesAndTransitTimesApi\Model\Commit;
use Symfony\Component\Validator\Constraints\All;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see Commit} has to satisfy.
 */
final class CommitConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'daysInTransit' => new Optional([...CommitDetail1DaysInTransitConstraint::constraints()]),
                'guaranteedType' => new Optional([...CommitDetail1GuaranteedTypeConstraint::constraints()]),
                'smartPostCommitTime' => new Optional([new Type(['string']), new NotNull()]),
                'dateDetail' => new Optional([new NotNull(), ...DateDetailConstraint::constraints()]),
                'delayDetails' => new Optional([new NotNull(), ...DelayDetailConstraint::constraints()]),
                'saturdayDelivery' => new Optional([new Type(['bool']), new NotNull()]),
                'alternativeCommodityNames' => new Optional([
                    new All([new Type(['string'])]),
                    new Type(['array']),
                    new NotNull(),
                ]),
                'transitDays' => new Optional([new NotNull(), ...TransitDaysConstraint::constraints()]),
                'label' => new Optional([new Type(['string']), new NotNull()]),
                'commitMessageDetails' => new Optional([new Type(['string']), new NotNull()]),
                'commodityName' => new Optional([new Type(['string']), new NotNull()]),
            ], null, null, true),
        ];
    }
}
