<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Validator;

use Override;
use Prefabcortex\FedexRatesAndTransitTimesApi\Model\Contact;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see Contact} has to satisfy.
 */
final class ContactConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'personName' => new Optional([new Type(['string']), new NotNull()]),
                'emailAddress' => new Optional([new Type(['string']), new NotNull()]),
                'phoneNumber' => new Optional([new Type(['string']), new NotNull()]),
                'phoneExtension' => new Optional([new Type(['string']), new NotNull()]),
                'faxNumber' => new Optional([new Type(['string']), new NotNull()]),
                'companyName' => new Optional([new Type(['string']), new NotNull()]),
            ], null, null, true),
        ];
    }
}
