<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Validator;

use Override;
use Prefabcortex\FedexRatesAndTransitTimesApi\Model\DeliveryOnInvoiceAcceptanceDetailRecipient;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Required;

/**
 * The rules a document for {@see DeliveryOnInvoiceAcceptanceDetailRecipient} has to satisfy.
 */
final class DeliveryOnInvoiceAcceptanceDetailRecipientConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'address' => new Required([
                    new NotNull(),
                    ...DeliveryOnInvoiceAcceptanceDetailRecipientAddressConstraint::constraints(),
                ]),
                'contact' => new Required([
                    new NotNull(),
                    ...DeliveryOnInvoiceAcceptanceDetailRecipientContactConstraint::constraints(),
                ]),
                'accountNumber' => new Optional([new NotNull(), ...AccountNumberConstraint::constraints()]),
            ], null, null, true),
        ];
    }
}
