<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Validator;

use Override;
use Prefabcortex\FedexRatesAndTransitTimesApi\Model\Dimensions;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Required;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see Dimensions} has to satisfy.
 */
final class DimensionsConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'length' => new Required([new Type(['integer']), new NotNull()]),
                'width' => new Required([new Type(['integer']), new NotNull()]),
                'height' => new Required([new Type(['integer']), new NotNull()]),
                'units' => new Required([new Type(['string']), new NotNull()]),
            ], null, null, true),
        ];
    }
}
