<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Validator;

use Override;
use Prefabcortex\FedexRatesAndTransitTimesApi\Model\EdtTaxDetail;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see EdtTaxDetail} has to satisfy.
 */
final class EdtTaxDetailConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'edtTaxType' => new Optional([new Type(['string']), new NotNull()]),
                'amount' => new Optional([new Type(['number']), new NotNull()]),
                'taxableValue' => new Optional([new Type(['number']), new NotNull()]),
                'name' => new Optional([new Type(['string']), new NotNull()]),
                'description' => new Optional([new Type(['string']), new NotNull()]),
                'formula' => new Optional([new Type(['string']), new NotNull()]),
                'effectiveDate' => new Optional([new Type(['string']), new NotNull()]),
            ], null, null, true),
        ];
    }
}
