<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Validator;

use Override;
use Prefabcortex\FedexRatesAndTransitTimesApi\Model\EmailNotificationRecipientNotificationType;
use Symfony\Component\Validator\Constraints\Choice;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Type;

use function array_map;

/**
 * The rules a document for {@see EmailNotificationRecipientNotificationType} has to satisfy.
 */
final class EmailNotificationRecipientNotificationTypeConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new Type(['string']),
            new Choice(
                null,
                array_map(static fn ($c) => $c->value, EmailNotificationRecipientNotificationType::cases()),
            ),
            new NotNull(),
        ];
    }
}
