<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Validator;

use Override;
use Prefabcortex\FedexRatesAndTransitTimesApi\Model\HomeDeliveryPremiumDetail;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see HomeDeliveryPremiumDetail} has to satisfy.
 */
final class HomeDeliveryPremiumDetailConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'shipTimestamp' => new Optional([new Type(['string']), new NotNull()]),
                'homedeliveryPremiumType' => new Optional([
                    ...HomeDeliveryPremiumDetailHomedeliveryPremiumTypeConstraint::constraints(),
                ]),
            ], null, null, true),
        ];
    }
}
