<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Validator;

use Override;
use Prefabcortex\FedexRatesAndTransitTimesApi\Model\PackageSpecialServicesRequested;
use Symfony\Component\Validator\Constraints\All;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see PackageSpecialServicesRequested} has to satisfy.
 */
final class PackageSpecialServicesRequestedConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'specialServiceTypes' => new Optional([
                    new All([new Type(['string'])]),
                    new Type(['array']),
                    new NotNull(),
                ]),
                'signatureOptionType' => new Optional([
                    ...PackageSpecialServicesRequestedSignatureOptionTypeConstraint::constraints(),
                ]),
                'alcoholDetail' => new Optional([new NotNull(), ...AlcoholDetailConstraint::constraints()]),
                'dangerousGoodsDetail' => new Optional([
                    new NotNull(),
                    ...DangerousGoodsDetailConstraint::constraints(),
                ]),
                'packageCODDetail' => new Optional([new NotNull(), ...PackageCODDetailConstraint::constraints()]),
                'pieceCountVerificationBoxCount' => new Optional([new Type(['integer']), new NotNull()]),
                'batteryDetails' => new Optional([
                    new All([...BatteryClassificationDetailConstraint::constraints()]),
                    new Type(['array']),
                    new NotNull(),
                ]),
                'dryIceWeight' => new Optional([new NotNull(), ...Weight1_2Constraint::constraints()]),
                'standaloneBatteryDetails' => new Optional([
                    new All([...StandaloneBatteryDetailsConstraint::constraints()]),
                    new Type(['array']),
                    new NotNull(),
                ]),
            ], null, null, true),
        ];
    }
}
