<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Validator;

use Override;
use Prefabcortex\FedexRatesAndTransitTimesApi\Model\PackageCODDetail;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;

/**
 * The rules a document for {@see PackageCODDetail} has to satisfy.
 */
final class PackageCODDetailConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'codCollectionAmount' => new Optional([new NotNull(), ...Money1Constraint::constraints()]),
                'codCollectionType' => new Optional([...PackageCODDetailCodCollectionTypeConstraint::constraints()]),
            ], null, null, true),
        ];
    }
}
