<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Validator;

use Override;
use Prefabcortex\FedexRatesAndTransitTimesApi\Model\ParsedPersonName;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see ParsedPersonName} has to satisfy.
 */
final class ParsedPersonNameConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'firstName' => new Optional([new Type(['string']), new NotNull()]),
                'lastName' => new Optional([new Type(['string']), new NotNull()]),
                'middleName' => new Optional([new Type(['string']), new NotNull()]),
                'suffix' => new Optional([new Type(['string']), new NotNull()]),
            ], null, null, true),
        ];
    }
}
