<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Validator;

use Override;
use Prefabcortex\FedexRatesAndTransitTimesApi\Model\PayorResponsibleParty;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Required;

/**
 * The rules a document for {@see PayorResponsibleParty} has to satisfy.
 */
final class PayorResponsiblePartyConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'address' => new Optional([new NotNull(), ...Address2Constraint::constraints()]),
                'contact' => new Optional([new NotNull(), ...Contact2Constraint::constraints()]),
                'accountNumber' => new Required([new NotNull()]),
            ], null, null, true),
        ];
    }
}
