<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Validator;

use Override;
use Prefabcortex\FedexRatesAndTransitTimesApi\Model\RateDiscount1;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see RateDiscount1} has to satisfy.
 */
final class RateDiscount1Constraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'amount' => new Optional([new Type(['number']), new NotNull()]),
                'name' => new Optional([new Type(['string']), new NotNull()]),
                'description' => new Optional([new Type(['string']), new NotNull()]),
                'type' => new Optional([new Type(['string']), new NotNull()]),
                'percent' => new Optional([new Type(['number']), new NotNull()]),
            ], null, null, true),
        ];
    }
}
