<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Validator;

use Override;
use Prefabcortex\FedexRatesAndTransitTimesApi\Model\RateOutputVO;
use Symfony\Component\Validator\Constraints\All;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see RateOutputVO} has to satisfy.
 */
final class RateOutputVOConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'rateReplyDetails' => new Optional([
                    new All([...RateReplyDetailConstraint::constraints()]),
                    new Type(['array']),
                    new NotNull(),
                ]),
                'quoteDate' => new Optional([new Type(['string']), new NotNull()]),
                'isEncoded' => new Optional([new Type(['bool']), new NotNull()]),
                'alerts' => new Optional([
                    new All([...AlertConstraint::constraints()]),
                    new Type(['array']),
                    new NotNull(),
                ]),
            ], null, null, true),
        ];
    }
}
