<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Validator;

use Override;
use Prefabcortex\FedexRatesAndTransitTimesApi\Model\RatedShipmentDetailPickupRateDetail;
use Symfony\Component\Validator\Constraints\All;
use Symfony\Component\Validator\Constraints\Choice;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see RatedShipmentDetailPickupRateDetail} has to satisfy.
 */
final class RatedShipmentDetailPickupRateDetailConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'rateType' => new Optional([...RatedShipmentDetailPickupRateDetailRateTypeConstraint::constraints()]),
                'rateScale' => new Optional([new Type(['string']), new NotNull()]),
                'rateZone' => new Optional([new Type(['string']), new NotNull()]),
                'ratingBasis' => new Optional([
                    ...RatedShipmentDetailPickupRateDetailRatingBasisConstraint::constraints(),
                ]),
                'pricingCode' => new Optional([
                    ...RatedShipmentDetailPickupRateDetailPricingCodeConstraint::constraints(),
                ]),
                'minimumChargeType' => new Optional([
                    ...RatedShipmentDetailPickupRateDetailMinimumChargeTypeConstraint::constraints(),
                ]),
                'currencyExchangeRate' => new Optional([
                    new NotNull(),
                    ...CurrencyExchangeRateConstraint::constraints(),
                ]),
                'specialRatingApplied' => new Optional([
                    new All([
                        new Type(['string']),
                        new Choice(null, ['FEDEX_ONE_RATE', 'FIXED_FUEL_SURCHARGE', 'IMPORT_PRICING']),
                    ]),
                    new Type(['array']),
                    new NotNull(),
                ]),
                'fuelSurchargePercent' => new Optional([new Type(['number']), new NotNull()]),
                'pickupBaseChargeDescription' => new Optional([
                    ...RatedShipmentDetailPickupRateDetailPickupBaseChargeDescriptionConstraint::constraints(),
                ]),
                'totalBaseCharge' => new Optional([new NotNull(), ...Money1Constraint::constraints()]),
                'totalFreightDiscounts' => new Optional([new NotNull(), ...Money1Constraint::constraints()]),
                'totalNetFreight' => new Optional([new NotNull(), ...Money1Constraint::constraints()]),
                'totalSurcharges' => new Optional([new NotNull(), ...Money1Constraint::constraints()]),
                'totalNetFedExCharge' => new Optional([new NotNull(), ...Money1Constraint::constraints()]),
                'totalTaxes' => new Optional([new NotNull(), ...Money1Constraint::constraints()]),
                'totalNetCharge' => new Optional([new NotNull(), ...Money1Constraint::constraints()]),
                'totalRebates' => new Optional([new NotNull(), ...Money1Constraint::constraints()]),
                'totalDutiesAndTaxes' => new Optional([new NotNull(), ...Money1Constraint::constraints()]),
                'totalAncillaryFeesAndTaxes' => new Optional([new NotNull(), ...Money1Constraint::constraints()]),
                'totalDutiesTaxesAndFees' => new Optional([new NotNull(), ...Money1Constraint::constraints()]),
                'totalNetChargeWithDutiesAndTaxes' => new Optional([new NotNull(), ...Money1Constraint::constraints()]),
                'freightDiscounts' => new Optional([
                    new All([...RateDiscount2Constraint::constraints()]),
                    new Type(['array']),
                    new NotNull(),
                ]),
                'rebates' => new Optional([
                    new All([...RebateConstraint::constraints()]),
                    new Type(['array']),
                    new NotNull(),
                ]),
                'surcharges' => new Optional([
                    new All([...Surcharge2Constraint::constraints()]),
                    new Type(['array']),
                    new NotNull(),
                ]),
                'taxes' => new Optional([
                    new All([...Tax2Constraint::constraints()]),
                    new Type(['array']),
                    new NotNull(),
                ]),
                'dutiesAndTaxes' => new Optional([
                    new All([...EdtCommodityTaxConstraint::constraints()]),
                    new Type(['array']),
                    new NotNull(),
                ]),
                'ancillaryFeesAndTaxes' => new Optional([
                    new All([...AncillaryFeeAndTaxConstraint::constraints()]),
                    new Type(['array']),
                    new NotNull(),
                ]),
                'variableHandlingCharges' => new Optional([
                    new NotNull(),
                    ...VariableHandlingCharges1Constraint::constraints(),
                ]),
                'totalVariableHandlingCharges' => new Optional([
                    new NotNull(),
                    ...VariableHandlingCharges1Constraint::constraints(),
                ]),
            ], null, null, true),
        ];
    }
}
