<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Validator;

use Override;
use Prefabcortex\FedexRatesAndTransitTimesApi\Model\RequestedShipmentSpecialServicesRequested;
use Symfony\Component\Validator\Constraints\All;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see RequestedShipmentSpecialServicesRequested} has to satisfy.
 */
final class RequestedShipmentSpecialServicesRequestedConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'returnShipmentDetail' => new Optional([
                    new NotNull(),
                    ...ShipmentSpecialServicesRequestedReturnShipmentDetailConstraint::constraints(),
                ]),
                'deliveryOnInvoiceAcceptanceDetail' => new Optional([
                    new NotNull(),
                    ...DeliveryOnInvoiceAcceptanceDetailConstraint::constraints(),
                ]),
                'internationalTrafficInArmsRegulationsDetail' => new Optional([
                    new NotNull(),
                    ...InternationalTrafficInArmsRegulationsDetailConstraint::constraints(),
                ]),
                'holdAtLocationDetail' => new Optional([
                    new NotNull(),
                    ...HoldAtLocationDetailConstraint::constraints(),
                ]),
                'shipmentCODDetail' => new Optional([
                    new NotNull(),
                    ...ShipmentSpecialServicesRequestedShipmentCODDetailConstraint::constraints(),
                ]),
                'shipmentDryIceDetail' => new Optional([
                    new NotNull(),
                    ...ShipmentDryIceDetailConstraint::constraints(),
                ]),
                'internationalControlledExportDetail' => new Optional([
                    new NotNull(),
                    ...InternationalControlledExportDetailConstraint::constraints(),
                ]),
                'homeDeliveryPremiumDetail' => new Optional([
                    new NotNull(),
                    ...HomeDeliveryPremiumDetailConstraint::constraints(),
                ]),
                'specialServiceTypes' => new Optional([
                    new All([new Type(['string'])]),
                    new Type(['array']),
                    new NotNull(),
                ]),
            ], null, null, true),
        ];
    }
}
