<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Validator;

use Override;
use Prefabcortex\FedexRatesAndTransitTimesApi\Model\ShipmentRateDetail;
use Symfony\Component\Validator\Constraints\All;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see ShipmentRateDetail} has to satisfy.
 */
final class ShipmentRateDetailConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'currencyExchangeRate' => new Optional([
                    new NotNull(),
                    ...CurrencyExchangeRateConstraint::constraints(),
                ]),
                'currency' => new Optional([new Type(['string']), new NotNull()]),
                'rateZone' => new Optional([new Type(['string']), new NotNull()]),
                'ratingBasis' => new Optional([...ShipmentRateDetailRatingBasisConstraint::constraints()]),
                'pricingCode' => new Optional([new Type(['string']), new NotNull()]),
                'totalFreightDiscount' => new Optional([new Type(['number']), new NotNull()]),
                'specialRatingApplied' => new Optional([
                    new All([new Type(['string'])]),
                    new Type(['array']),
                    new NotNull(),
                ]),
                'totalSurcharges' => new Optional([new Type(['number']), new NotNull()]),
                'freightDiscount' => new Optional([
                    new All([...RateDiscountConstraint::constraints()]),
                    new Type(['array']),
                    new NotNull(),
                ]),
                'fuelSurchargePercent' => new Optional([new Type(['number']), new NotNull()]),
                'totalBillingWeight' => new Optional([new NotNull(), ...Weight1Constraint::constraints()]),
                'totalDimWeight' => new Optional([new NotNull(), ...Weight1Constraint::constraints()]),
                'dimDivisor' => new Optional([new Type(['integer']), new NotNull()]),
                'surCharges' => new Optional([
                    new All([...SurchargeConstraint::constraints()]),
                    new Type(['array']),
                    new NotNull(),
                ]),
                'taxes' => new Optional([
                    new All([...TaxConstraint::constraints()]),
                    new Type(['array']),
                    new NotNull(),
                ]),
            ], null, null, true),
        ];
    }
}
