<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexRatesAndTransitTimesApi\Validator;

use Override;
use Prefabcortex\FedexRatesAndTransitTimesApi\Model\ShipmentCODDetail;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see ShipmentCODDetail} has to satisfy.
 */
final class ShipmentCODDetailConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'addTransportationChargesDetail' => new Optional([
                    new NotNull(),
                    ...CODTransportationChargesDetailConstraint::constraints(),
                ]),
                'codRecipient' => new Optional([new NotNull(), ...Party2Constraint::constraints()]),
                'remitToName' => new Optional([new Type(['string']), new NotNull()]),
                'codCollectionType' => new Optional([...ShipmentCODDetailCodCollectionTypeConstraint::constraints()]),
                'financialInstitutionContactAndAddress' => new Optional([
                    new NotNull(),
                    ...ContactAndAddressConstraint::constraints(),
                ]),
                'returnReferenceIndicatorType' => new Optional([
                    ...ShipmentCODDetailReturnReferenceIndicatorTypeConstraint::constraints(),
                ]),
            ], null, null, true),
        ];
    }
}
